Tweetボタンを追加した
momocus/sakazuki pull request #108
Opened 2020-12-22 14:36 UTC by yonta

close #34

![image](https://user-images.githubusercontent.com/849256/102899006-adbfef00-44ad-11eb-8dc3-ccbcc8444405.png)

![image](https://user-images.githubusercontent.com/849256/102899048-b7e1ed80-44ad-11eb-921f-dfc690f423f7.png)

### やったこと

- 酒のshowにTweetボタンを追加した
    - Tweetボタンを押すツイッターの投稿画面に飛ぶ
    - Tweet内容には酒の名前、蔵の名前、色、香り、味が入る。
    - Tweet内容には`#Sakazuki`のハッシュタグが入る
    - Twitterの仕様から、末尾にいらない#が入る

### やってないこと

- gemのtweet-buttonは使わなかった
    - tweet-buttonはLink Shareのみ対応しており、ハッシュタグShareに対応していない
    - tweet-buttonは使うと巨大な<html>を生成するため、かなり巨大なタグが生成される
- ja.ymlを使って記述しているが、日本語のみに対応している。
    - "萩野酒造さんの萩の鶴"と"Haginotsuru of Hagino Shuzo"のように、英語だと文章の順番が変わるため面倒。

2020-12-24 05:45 UTC, momocus requested changes
昨日追加ありがと。いくつか修正してね。

2020-12-26 08:03 UTC, yonta commented on app/helpers/tweet_helper.rb
> +  def add_postfix(text, postfix, period = "")
prefix!

2020-12-26 08:03 UTC, yonta commented on app/helpers/tweet_helper.rb
> +    hashed_twitter = "https://twitter.com/intent/tweet?button_hashtag=Sakazuki&ref_src=twsrc%5Etfw"
URLにした。Androidは死んだ。

2020-12-26 08:03 UTC, yonta commented on app/helpers/tweet_helper.rb
> +  # PREFIXEにPERIODがない場合は自動で付加する。
コメント自体がリファクタで消した

2020-12-26 08:04 UTC, yonta commented on app/helpers/tweet_helper.rb
> +  def add_prefix(text, prefix, period = "")
suffix!

2020-12-26 08:04 UTC, yonta commented on app/helpers/tweet_helper.rb
> +  def add_prefix(text, prefix, period = "")
add_periodで別関数にした

2020-12-26 08:21 UTC, yonta commented on app/helpers/tweet_helper.rb
> +    text = add_postfix(text, kura.gsub("株式会社", "㈱").to_s, t("helpers.tweet.honorific_title"))
切り出した。
㈱しかしてなかったのも増やして、あれこれ囲み文字に変換するようにした。

2020-12-28 07:46 UTC, momocus approved these changes
💯

2020-12-28 07:46 UTC, merged