Responsive image size
momocus/sakazuki pull request #111
Opened 2020-12-30 05:20 UTC by momocus

### やったこと

- show, editビューの画像サイズをレスポンシブにした
  - 横に三枚くらい並ぶのがいい感じだったのでcol-3で指定
![image](https://user-images.githubusercontent.com/6294782/103331250-57077600-4aa8-11eb-820c-a42f97772fda.png)
![image](https://user-images.githubusercontent.com/6294782/103331318-b1a0d200-4aa8-11eb-9eff-15fd8f0e97b1.png)

### できなかったこと

- indexビューの画像サイズをレスポンシブにできなかった
  - 親要素（Col）にheight制限がないので、
  - https://getbootstrap.jp/docs/4.2/content/images/

2021-01-05 09:44 UTC, yonta requested changes
✍

2021-01-05 09:44 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +  @extend .col-3;
特殊なことしてないので、ただの`col-3`を使えばよいと思う

2021-01-05 09:44 UTC, yonta commented on app/views/sakes/_form.html.erb
> +            <%= cl_image_tag(photo.image.url, { class: "show_image" }) %>
ここの`()`も`{}`もいらんかったわ
あとでいらないカッコ消すコミットしておく。

2021-01-05 09:44 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
1回しか使わないやつなら名前つけせずに、bootstrapの名前使えばよいと思う。
定義を見に行くだけ手間。

2021-01-05 09:44 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
今さら気づいたんだけど、俺なんで命名にアンダースコア使ったんだろう。
CSSはハイフン使えるからそっちでいいのに。はて。

2021-01-05 09:44 UTC, yonta commented on app/uploaders/image_uploader.rb
> -  version :thumb do
リサイズをまったくせずにHTML上でフィットだけするということでいいのかな。
クソデカイメージをアップロードするとページ読み込みが激重になりそう。
現状よりは大きいサイズでサムネイルを作っておくほうがいいのでは。
formもindexもサムネイル用画像を表示したほうが良いと思う。

2021-01-05 09:44 UTC, yonta commented on app/views/sakes/index.html.erb
> +          <%= cl_image_tag(sake.photos.first.image.url, { class: "thumb_image" }) if sake.photos.any? %>
`img-fluid`よりもサムネイル用にbootstrapで用意されている`img-thumbnail`を使うべき。
https://getbootstrap.jp/docs/4.5/content/images/#image-thumbnails

2021-01-05 09:44 UTC, yonta commented on app/views/sakes/index.html.erb
> +          <%= cl_image_tag(sake.photos.first.image.url, { class: "thumb_image" }) if sake.photos.any? %>
縦長の画像がくるとformもindexも表示が崩れる。
サムネイル作るときにいい感じに中央を固定比でトリミングできないかな。
別Issueでもよい。

![image](https://user-images.githubusercontent.com/849256/103630950-bd4b3780-4f85-11eb-8c01-ead9e592f635.png)

![image](https://user-images.githubusercontent.com/849256/103630929-b6242980-4f85-11eb-9d76-c379cd4d6925.png)

2021-01-05 09:47 UTC, yonta commented on app/views/sakes/_form.html.erb
>              <%= check_box_tag photo.chackbox_name, "delete", nil, { class: "form-check-input" } %>
bootstrapが用意しているチェックボックスの水平配置を使うとより良いと思う。

https://getbootstrap.jp/docs/4.5/components/forms/#inline

2021-01-05 09:55 UTC, yonta commented on app/views/sakes/_form.html.erb
> +            <%= cl_image_tag(photo.image.url, { class: "show_image" }) %>
括弧なるべく省略していいのではという気持ちになりつつあるけど、書いたほうがいい気もしてきて何もわからん

2021-01-05 10:12 UTC, yonta requested changes

2021-01-05 10:12 UTC, yonta commented on app/views/sakes/_form.html.erb
> +            <%= cl_image_tag(photo.image.url, { class: "show_image" }) %>
https://github.com/cookpad/styleguide/blob/master/ruby.ja.md#%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%97
COOKPADがスタイルガイド出してた。
参考になるなー。
メソッド呼び出しは括弧をつける、ただしDSLのときは省略する、というの参考になる。

2021-01-05 10:12 UTC, yonta commented on app/views/sakes/_form.html.erb
> +            <%= cl_image_tag(photo.image.url, { class: "show_image" }) %>
`form.label`は`ActionView`で定義されているけど、ほぼDSLではという気もする。
Rails提供のメソッドは括弧省略もありかなと思う。

2021-01-05 12:41 UTC, momocus commented on app/views/sakes/_form.html.erb
> +            <%= cl_image_tag(photo.image.url, { class: "show_image" }) %>
クックパッドのスタイルガイドよさげですね。
括弧は書いたほうがわかりやすいと思う。

2021-01-05 12:41 UTC, momocus commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
cssではアンダースコアよりハイフンで単語区切るのが主流なん？

2021-01-05 20:09 UTC, momocus commented on app/views/sakes/index.html.erb
> +          <%= cl_image_tag(sake.photos.first.image.url, { class: "thumb_image" }) if sake.photos.any? %>
表示を崩さないするための手段として、トリミングする方法と、デバイスによって高さ制限（max-height）を切り替える方法のふたつがある。どっちがいいかな。

（トリミングするにしても、画像の高さはデバイスによって変えたいかも？）

2021-01-05 20:11 UTC, momocus commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
htmlにsytle属性ベタ書きするの、他のところではやってないけどやっていいの？

2021-01-05 20:13 UTC, momocus commented on app/javascript/src/stylesheet/application.scss
> +  @extend .col-3;
show_imageって名前をつけず、htmlの方にclass: col-3って書くってこと？

2021-01-06 04:37 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +  @extend .col-3;
イエス。
そもそも`col-3`に「横幅3のカラム」って意味があるし、それ以上の情報が増えていないし、別名つけてもあとから読むときに手間になるだけだと思う。

あとここ、`show_body`（実態は`col-N`）の中に`show_image`書いている。
colの中にcol書いているので配置が崩れている。
正しくは新しく`row`を作ってその中に`col-N`をいれないといけない。

2021-01-06 04:38 UTC, yonta commented on app/views/sakes/_form.html.erb
> +            <%= cl_image_tag(photo.image.url, { class: "show_image" }) %>
:+1:

2021-01-06 04:39 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
ハイフンもアンダースコアも使えるけど、bootstrapがハイフンだしハイフン統一でいいと思う。
名前によってハイフンとアンダースコアが違うとか使いづらい。
さらに、ハイフンとアンダースコアだけ違う別名とかつけれちゃって混乱するし。
あとでハイフン統一しておくわ。

2021-01-06 05:04 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
特に禁止はしてないし、内容の再利用性も低いし、ベタ書きでいいと思う。

2021-01-06 05:05 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
統一した。masterにrebaseしておいて。
アンダーバーを使っていたのは、Railsの`field_with_error`に引っ張られていたようだ。
これ以外は別にハイフンでいいと思う。

2021-01-06 05:06 UTC, yonta commented on app/views/sakes/index.html.erb
> +          <%= cl_image_tag(sake.photos.first.image.url, { class: "thumb_image" }) if sake.photos.any? %>
トリミング横長固定（16:9か1:1あたり）で、デバイスによって変えないが良さそうだと思う

2021-01-06 05:08 UTC, yonta commented on app/views/sakes/_form.html.erb
> +            <%= cl_image_tag(photo.image.url, { class: "show_image" }) %>
OK、括弧ありにしよう。
COOKPADの通りActionControllerだけ括弧なしにしておくか。

2021-01-11 13:23 UTC, momocus commented on app/javascript/src/stylesheet/application.scss
> +  @extend .col-3;
show_image 廃止しました
colとrowの配置見直しました

2021-01-11 13:23 UTC, momocus commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
thumb_image廃止しました

2021-01-11 13:24 UTC, momocus commented on app/javascript/src/stylesheet/application.scss
> +.thumb_image {
masterにrebaseしました

2021-01-11 13:24 UTC, momocus commented on app/uploaders/image_uploader.rb
> -  version :thumb do
おっしゃる通りなので元のバージョンに戻して、サムネイル用にリサイズ&トリミングするようにしました

2021-01-11 13:25 UTC, momocus commented on app/views/sakes/index.html.erb
> +          <%= cl_image_tag(sake.photos.first.image.url, { class: "thumb_image" }) if sake.photos.any? %>
img-thumbnail使うようにしました

2021-01-11 13:29 UTC, momocus commented on app/views/sakes/index.html.erb
> +          <%= cl_image_tag(sake.photos.first.image.url, { class: "thumb_image" }) if sake.photos.any? %>
こんな感じでできました
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/6294782/104188284-57b2eb80-545c-11eb-8ac2-017a0b457c94.png">

2021-01-11 13:31 UTC, momocus commented on app/views/sakes/_form.html.erb
>              <%= check_box_tag photo.chackbox_name, "delete", nil, { class: "form-check-input" } %>
やりました。その節はご協力ありがとうございます。
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/6294782/104188504-aeb8c080-545c-11eb-98e0-205ac7203e64.png">

2021-01-12 10:00 UTC, yonta requested changes
revertするならコミット削除しちゃうほうが好き。
確かにログは残るからこのままでいいよ。

コメントしたので見て。

2021-01-12 14:16 UTC, momocus commented on app/views/sakes/index.html.erb
> +        <%# Hack: 画像を置くセルの縦横比がだいたい2:1、画像自体の縦横比が1:1なので、画像の横幅を50%にすることで行が縦長になるのを防ぐ %>
suggestionありがとう。適用しました。

2021-01-12 14:24 UTC, momocus commented on app/views/sakes/_form.html.erb
> +          <div class="form-check form-check-inline col-5">
ﾌｧｰありがとう。Bootstrapなんもわからんゴ。

2021-01-12 14:41 UTC, merged