酒一覧をより見やすくする機能強化 作り直し
momocus/sakazuki pull request #118
Opened 2021-01-11 08:37 UTC by yonta

Fix #80

### 行ったこと

- 空き瓶をデフォルトでは非表示にした
    - 古い機能の在庫表示は削除した
- 酒のデフォルト表示を新しい順にした
    - idによる降順でソートされる
- 酒のソート機能を追加した
    - 特定名称、都道府県、開封状態の昇順でソートできる

### まだできていないこと

- テーブルヘッダーで昇順降順の変更
    - 現状の酒一覧のテーブルがレスポンシブデザインかつ構造が複雑なテーブルになっている
    - そのためうまくテーブルにヘッダーがつけられない
- モデルへのインデックスの付加
    - 昇順降順を頻繁かつ大量のモデルに使うなら、モデルへインデックスを付加して高速化する必要がある
    - https://techracho.bpsinc.jp/hachi8833/2018_01_11/50793

2021-01-11 09:27 UTC, momocus requested changes
若干気になるとこあるからRequestChangeで出すけどそのままマージしてもいいくらいですボーテ

2021-01-11 09:27 UTC, momocus commented on app/views/sakes/index.html.erb
> +                { class: "btn btn-info" }) %>
並べ替えボタンは表の右上の方にあるほうがいいな。
楽天の並べ替えボタン真似したらよさげ。
https://search.rakuten.co.jp/search/mall/コットンワンピース/?s=2

難しかったら別Issueでおけ

2021-01-11 09:27 UTC, momocus commented on app/views/sakes/index.html.erb
> +  <%= link_to(t(".all_bottles"),
テーブルの上に表示した方がいいんじゃない？
登録ボタンもだけど

2021-01-11 09:27 UTC, momocus commented on app/controllers/sakes_controller.rb
> +    sort_key = empty_to_default(params[:sort], "id").intern
デフォルトID順は大変ボーテ

2021-01-11 09:27 UTC, momocus commented on app/views/sakes/show.html.erb
> +              { class: "btn btn-primary mx-2" }) %>
グッドデザイン賞受賞

2021-01-11 15:05 UTC, yonta commented on app/models/search/sake.rb
>        results
現状は在庫なしの検索が使えなくなっている。
やるにはURIを自分で作って叩かないといけない。
そもそも現状で検索使っていないので、えらさー入れるときに考えよう。

2021-01-11 15:07 UTC, yonta commented on app/views/sakes/index.html.erb
> +                { class: "btn btn-info" }) %>
確かにプルダウンという手があるか。
とりあえず酒indexには情報が少なく、並び替えが3つしか無い。
プルダウンじゃなく右のほうに配置を試みよう。

2021-01-11 15:08 UTC, yonta commented on app/views/sakes/index.html.erb
> +  <%= link_to(t(".all_bottles"),
空き瓶表示はめったに使わない機能だし、あえて下に配置。
登録ボタンはいい感じに上に置きたい。
登録ボタンはnavにいれるのを検討すべきかも。
今回は対処しない。

2021-01-12 06:07 UTC, yonta commented on app/views/sakes/index.html.erb
> +                { class: "btn btn-info" }) %>
aaefd3c で対応

2021-01-12 13:56 UTC, momocus commented on app/models/search/sake.rb
>        results
り

2021-01-12 13:56 UTC, momocus commented on app/views/sakes/index.html.erb
> +  <%= link_to(t(".all_bottles"),
り

2021-01-12 13:57 UTC, momocus commented on app/views/sakes/index.html.erb
> +                { class: "btn btn-info" }) %>
サイッコーにクールなデザインになったね！　実にボーテ！

2021-01-12 13:57 UTC, merged