Ransackを使って空き瓶表示機能を作成した
momocus/sakazuki pull request #142
Opened 2021-01-27 17:39 UTC by yonta

### 使い方

- 空き瓶にチェックを入れる
- 検索すると、空き瓶も表示される
    - 空き瓶は普段使わないので、「チェックを入れる」→「検索する」、の2段階でアクセスさせる形式にした
- その後、検索や空き瓶表示の状態を引き継いでソートもできる

### やったこと

- 古い空き瓶リンクを削除
- Ransackでデフォルトのidソートと空き瓶表示機能を実現
- Ransackのリファクタ
    - 検索クエリにわかりやすい別名をつけた
    - Ransackの検索クエリに間違いがあると実行時エラーになるようにした
- 必要なかったERBLintの設定を消した

2021-01-28 08:03 UTC, momocus commented on app/views/sakes/index.html.erb
> +                          id: "all_bottle_level" }, "-1", "2") %>
この-1と2はなんの魔法？

2021-01-28 09:23 UTC, momocus requested changes
めっちゃいい感じに動いてました。ボーテ！
コーディングについて細かな指摘をしたので、修正お願いします。

2021-01-28 09:39 UTC, yonta commented on app/views/sakes/index.html.erb
> +                          id: "all_bottle_level" }, "-1", "2") %>
確かに。変数作ろう。

2021-01-28 16:02 UTC, yonta commented on app/views/sakes/index.html.erb
> +                          id: "all_bottle_level" }, "-1", "2") %>
nil使った

2021-01-29 06:31 UTC, momocus approved these changes
💯

2021-01-29 06:31 UTC, merged