ページネーションをつける
momocus/sakazuki pull request #143
Opened 2021-01-29 08:55 UTC by momocus

### やったこと

テーブルの上部と下部にページネーションをつけた

2021-01-30 06:06 UTC, yonta requested changes
デザインを諦めないで

2021-01-30 06:06 UTC, yonta commented on config/initializers/kaminari_config.rb
> +  config.params_on_first_page = false
defaultと同じ設定値ならわざわざ書かなくていいと思う

2021-01-30 06:06 UTC, yonta commented on config/initializers/kaminari_config.rb
> +# frozen_string_literal: true
文字列がないのにfrozen stringが必要なの？

2021-01-30 06:06 UTC, yonta commented on config/initializers/kaminari_config.rb
> +  config.params_on_first_page = false
https://github.com/kaminari/kaminari#general-configuration-options

2021-01-31 06:29 UTC, momocus commented on config/initializers/kaminari_config.rb
> +# frozen_string_literal: true
削除しました

2021-01-31 06:30 UTC, momocus commented on config/initializers/kaminari_config.rb
> +  config.params_on_first_page = false
default値のものを削除しました

2021-01-31 09:14 UTC, momocus commented on app/javascript/src/stylesheet/application.scss
> +  justify-content: center;
以下の通り変更しました。

- 変更内容
  - Index上部が煩雑だったため、上部のページネーションは削除して、下部だけに表示するようにした。
  - 前後のページへのリンクが小さくクリックしづらかったため、「<前へ」「次へ>」とした。
  - githubのIssuues等のページネーションに倣い、最初の2ページと末尾の2ページ、現在のページと前後の2ページを数字で表示するようにした。これに伴い、先頭ページへのジャンプ「<<」と末尾ページへのジャンプ「>>」ボタンは削除した。
  - 閲覧する端末によってデザインが崩れないよう、画面サイズ応じて表示を切り替えるようにした。画面サイズが小さい時は「<前へ」「次へ>」だけ表示する。

タブレットやPCでの表示
  ![image](https://user-images.githubusercontent.com/6294782/106376914-9cd39900-63dc-11eb-9c85-e005b715018e.png)

モバイル表示
![image](https://user-images.githubusercontent.com/6294782/106376907-97764e80-63dc-11eb-965f-52cacd1db1eb.png)

2021-01-31 09:14 UTC, momocus commented on app/views/kaminari/_first_page.html.erb
> +  <%= link_to_unless current_page.first?, t("views.pagination.first"), url, remote: remote, class: "page-link" %>
修正しました

2021-01-31 09:15 UTC, momocus commented on app/views/kaminari/_next_page.html.erb
> +                                                                          class: "page-link" %>
修正しました。
改行に意味がなかったため１行に書きました。

2021-02-02 08:11 UTC, yonta approved these changes
ボーテ！💯！

2021-02-02 08:11 UTC, yonta commented on app/controllers/sakes_controller.rb
> +                      .page(params[:page])
メソッドチェーンが短いので1行で書いた

```suggestion
    @sakes = @searched.result(distinct: true).page(params[:page])
```

2021-02-02 08:11 UTC, yonta commented on config/locales/views/ja.yml
> +      last: ">>"
`first`と`last`はもう使われてない

```suggestion
```

2021-02-02 09:49 UTC, merged

2021-02-08 15:43 UTC, yonta commented
close #134