酒作成でログインしたときインデクスに戻されないようにした
momocus/sakazuki pull request #182
Opened 2021-05-24 15:29 UTC by momocus

fix #171

2021-06-02 00:37 UTC, iteduki commented
テスト用に使う識別子はdata属性を使うのがいいと思います
https://speakerdeck.com/yasaichi/tokyurubykaigi12

2021-06-12 03:46 UTC, yonta commented
仕様追加、PR #190 で実装された「開ける」「空にする」のページ遷移先をshowページからindexページにする

2021-06-13 12:09 UTC, momocus commented
> 仕様追加、PR #190 で実装された「開ける」「空にする」のページ遷移先をshowページからindexページにする

PRあまり大きくしたくないので分けます -> #197

2021-06-13 12:16 UTC, momocus commented
@yonta 
ruby3に上げたmasterにrebaseしました。
レビューお願いします。

2021-06-14 05:10 UTC, yonta requested changes

2021-06-14 05:10 UTC, yonta commented on spec/system/sign_in_redirect_spec.rb
> +    it "redirect to edit_sake_path after user sign-in" do
`after sign in`だけでよく、userって書かなくていいと思う

2021-06-14 05:10 UTC, yonta commented on spec/system/sign_in_redirect_spec.rb
> +  context "when non-signed-in user tries to new-sake" do
```suggestion
  context "when not signed user tries to create new sake" do
```

2021-06-14 05:10 UTC, yonta commented on spec/system/sign_in_redirect_spec.rb
> +  context "when user presses sign-in button on sake show page" do
`user presses`だけど、これだとuserの目的がボタンを押すことと読み取れる。
でもこのテストは、「酒showページでユーザがログインしたときの動作」なのでuserの目的はログイン。

```suggestion
  context "when user sign in from sake show page" do
```

2021-06-14 05:10 UTC, yonta commented on spec/system/sign_in_redirect_spec.rb
> +end
PR内容にあった「評価ボタン」とかの仕様は現状の動作でいいと思う。
それらのボタンに対するテストもここに書くか、統合テストとして`sign_in_redirect_via_drink_button_spec.rb`とかに別ファイルで書くべき。

2021-06-14 07:05 UTC, momocus commented on app/controllers/application_controller.rb
> +  end
ブラウザによってRequest.referrerは対応していないから使わないって[ここ](https://github.com/heartcombo/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update)に書いてあったから使わなかった。
けど👆のMozillaのページを見るに、我々が使うブラウザは対応してそうね。
安全なものを使うべきという意見には賛成なので、referer使った実装に変更します。

2021-06-14 09:19 UTC, momocus commented on app/controllers/application_controller.rb
> +  end
deviseのafter_sign_in_path_forメソッドを使ってrequest.refererの値をセットしようと試みたが、request.refererの値がなぜかsign_inページになってうまくいかなかった。
deviseの[SessionsController](https://www.rubydoc.info/github/plataformatec/devise/Devise/SessionsController)をオーバーライドしたらどうにかできるとは思うが、実装コストが重くなる。

このため、RESTfulではありませんが、[Deviseのおすすめの方法](https://github.com/heartcombo/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update)に倣った実装とする。

2021-06-14 09:21 UTC, momocus commented on app/controllers/application_controller.rb
> +  end
ユーザーの居たパスを保存していいか判定する部分（`if request.get?...`）が何しているかわかりにくいとの指摘を受けたので、切り出してメソッド化します。

2021-06-14 10:30 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +    it "redirect to edit_sake_path after user sign-in" do
接続詞の後の主語を省略できるのは、前の文と主語が同じときだけだけのはず。
適当な英文を書かせることを許すなら、いっそ日本語で書くことを許してくれ。

2021-06-14 12:37 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +    it "redirect to edit_sake_path after user sign-in" do
afterは前置詞としても使えるのでafter 名詞 って使っていい

2021-06-14 12:42 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +  context "when user presses sign-in button on sake show page" do
when user signs in from header button on sake show page
「酒Showページのヘッダーボタンでユーザーがログインしたとき」にします。
理由：酒Showページからログインする方法が2つ（ヘッダーのサインインを押すor酒編集ボタンを押す）あって、どちらの方法かによって挙動が異なるため。

2021-06-14 14:06 UTC, momocus commented on app/controllers/application_controller.rb
> +  end
fixed in ec3a110

2021-06-14 14:07 UTC, momocus commented on spec/rails_helper.rb
> +  config.include(SignInModule)
fixed in f84b756

2021-06-14 14:08 UTC, momocus commented on spec/support/sign_in_module.rb
> +  def fill_sign_column(user)
signin_process_on_signin_page としました b2196b6

2021-06-14 14:08 UTC, momocus commented on spec/support/sign_in_module.rb
> +  # Sign inページにてemail、passwordを入力し、サインインする
Fixed in b2196b6

2021-06-14 14:08 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +  let!(:user) { FactoryBot.create(:user) }
Fixed in 54ad8d6

2021-06-14 14:09 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +  context "when non-signed-in user tries to edit-sake" do
Fixed in 5c30803

2021-06-14 14:09 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +    it "redirects user to new_user_session_path" do
Fixed in 5c30803

2021-06-14 14:10 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +    it "redirect to edit_sake_path after user sign-in" do
Fixed in 5c30803

2021-06-14 14:10 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +  context "when non-signed-in user tries to new-sake" do
Fixed in 5c30803

2021-06-14 14:10 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +  context "when user presses sign-in button on sake show page" do
Fixed in 5c30803

2021-06-14 14:34 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +end
Issue 立てました #204

2021-06-14 14:35 UTC, momocus commented on spec/system/sign_in_redirect_spec.rb
> +    it "redirects user to new_user_session_path" do
Fixed in 5c30803

2021-06-15 03:00 UTC, yonta approved these changes
GJ

2021-06-15 03:00 UTC, yonta commented on spec/system/sign_in_redirect_spec.rb
> +    it "redirects user to root url (does not occur redirection loop)" do
```suggestion
    it "redirects to root url (does not occur redirection loop)" do
```

2021-06-15 03:02 UTC, merged