BY に和暦を追加
momocus/sakazuki pull request #184
Opened 2021-06-05 10:06 UTC by exoego

Closes #170 

* `form.date_select` では、ラベルのフォーマットをカスタマイズできるようですが、和暦を埋め込むようなことはできなさそうでした。
  このため、`<select>` を組み立てるヘルパーメソッドを定義しました。
* 西暦→和暦変換には https://github.com/tomiacannondale/era_ja を使いました。

# 📸 
### 登録ページ
![image](https://user-images.githubusercontent.com/127635/120887924-8eb6b300-c630-11eb-8142-b36bf074a9d1.png)
![image](https://user-images.githubusercontent.com/127635/120887931-95ddc100-c630-11eb-95d8-254ab5efb467.png)

### 詳細ページ（修正なし）
![image](https://user-images.githubusercontent.com/127635/120888008-097fce00-c631-11eb-84ac-cb13f564e229.png)

2021-06-05 12:02 UTC, yonta commented
GitHub、仕様が変わって初コントリビューターに対して自動GitHub Actionがオフになっているのね。
exoegoさんのGitHub Actionを有効にしました:+1:

2021-06-05 12:02 UTC, yonta commented
Oooops
PR毎にボタン押す必要あるのか。
Learn more見てこよ

2021-06-05 12:22 UTC, yonta requested changes
PRありがたや～～～。修正依頼です。

2021-06-05 12:22 UTC, yonta commented on app/views/sakes/_form.html.erb
> +                                        begin_year=Date.current.year) %>
これだと酒詳細から編集を押すと、登録されている内容がフォームに反映されないですね。

例えば、
- 登録で「製造年月日」で「2010年」をセレクト
- 「更新する」ボタンで登録する
- 酒の詳細ページで「鉛筆マーク」の編集ボタンを押す
- 酒の「製造年月日」が登録内容によらず「2021」になってしまう

これは「製造年月日」も「BY」も一緒の問題を抱えていますね。

2021-06-05 12:22 UTC, yonta commented on app/views/sakes/_form.html.erb
> +                                        begin_year = Date.current.year) %>
現状は<https://github.com/momocus/sakazuki/blob/master/app/javascript/src/typescript/async_bindume_date.ts>を使って、id被りの2つのdateフォームを同期してます。

2021-06-05 12:22 UTC, yonta commented on app/views/sakes/_form.html.erb
> +                                        begin_year = Date.current.year) %>
どうするのがいいんだろね。

2021-06-05 12:28 UTC, yonta commented on app/views/sakes/_form.html.erb
> +                                        begin_year=Date.current.year) %>
Railsデフォルトじゃないカスタムフォームを、Railsデフォルトの機能といい感じにするの難しい。

2021-06-05 12:38 UTC, exoego commented on app/helpers/sakes_helper.rb
> +  # @param [Date] date
Yes.
JetBrains IDE がサポートしています

2021-06-05 12:48 UTC, exoego commented on app/helpers/sakes_helper.rb
> +    [date.year, " / ", date.to_era("%O%-E年")].join("")
Fixed in https://github.com/momocus/sakazuki/pull/184/commits/5eda822f2d6b14c78bbf32cf7f464b6cda80e4a1

2021-06-05 12:48 UTC, exoego commented on app/views/sakes/_form.html.erb
> +                                        begin_year=Date.current.year) %>
Fixed in https://github.com/momocus/sakazuki/pull/184/commits/72dcf9484b544fa7d9bdb284b504793ab7aa09fe

2021-06-05 12:53 UTC, exoego commented on app/helpers/sakes_helper.rb
> +    select_tag id, options_for_select(options, selected: selected_year), class: "form-control", name: name
Fixed in https://github.com/momocus/sakazuki/pull/184/commits/c11b026952607f82047482970c89ca60f1b54793

2021-06-05 16:45 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  # @param [Date] date
よさげ～～～。
今はRuby3にあげようとしてるんで、その型でも足りないときはYARD導入しよ。
Thx!

2021-06-05 17:22 UTC, yonta commented
他PRをマージしたので、今後は自動でGitHub Actionsが回ってくれるはず。

あと詳細ページに関してはとりあえず和暦なしでいいかなぁ。
酒瓶に和暦しか書いてないものがけっこうあって、その入力が手間だったので。

2021-06-05 18:29 UTC, yonta requested changes
見逃しているミスがあったわー

2021-06-05 18:29 UTC, yonta commented on app/helpers/sakes_helper.rb
> +      [with_japanese_era(to_by(Date.new(year + 1))), year]
ここにBYの計算が出てくるのはおかしいですね。

BYは酒造年度（Brewery Year）という概念で、製造年月とは違うものです。
例えば、BY2020は2020/7/1～2021/6/30となります。

2021-06-05 18:29 UTC, yonta commented on app/views/sakes/_form.html.erb
> +      <input type="hidden" id="sake_<%= :brew_year %>_3i" name="sake[<%= :brew_year %>(3i)]" value="1">
デフォルト値の設定は[sakes_controller.rb](https://github.com/momocus/sakazuki/blob/9c714ad1ee8aa073842e1b03ecc543d7e03be68e/app/controllers/sakes_controller.rb#L44)でセットしているからいらない気がする。
間違ってたらごめんなさい。

2021-06-05 18:29 UTC, yonta commented on app/views/sakes/_form.html.erb
> +      <%= year_select_with_japanese_era(id = "sake_brew_year_1i",
このままだと、「製造年月」は正しい数値ですが、「BY」のほうは未来の数値を選べてしまう。
例えば今は6月なのでBY2020（BY令和2年）の日本酒しか存在しませんが、選択肢には「BY2021 / 令和3年」が出てしまう。
これは避けたいです。

おそらく`year_select_with_japanese_era`のBY計算をなくす修正をしてから、こんな引数でいける気がする。
```ruby
begin_year = to_by(Date.current.year)
```

2021-06-05 18:44 UTC, yonta commented on app/views/sakes/_form.html.erb
> +      <input type="hidden" id="sake_<%= :brew_year %>_3i" name="sake[<%= :brew_year %>(3i)]" value="1">
間違ってたわ、なのでこの行は必要。
代わりにsakes_controller.rbの`@sake.brew_year = to_by(Time.zone.today)`を消さないとだ。
Railsのデフォルトselectフォームじゃないと、この初期化方法はうまくいかないようだ。

2021-06-05 19:02 UTC, yonta reviewed
要らなくなったTypeScript処理を削除したので、以下のコミットをcherry-pickしてください。

commit 06616a97ff39c2df416e0724345f2f48bf8b93f3

2021-06-05 21:00 UTC, exoego commented on app/views/sakes/_form.html.erb
> +      <%= year_select_with_japanese_era(id = "sake_brew_year_1i",
BYは常に前年までを表示するということですか？
今日が2021/12/31で、BYが2021の前半のどこかということはない？

2021-06-06 03:43 UTC, yonta commented on app/views/sakes/_form.html.erb
> +      <%= year_select_with_japanese_era(id = "sake_brew_year_1i",
現在の日付が1/1-6/30までは前年までを表示して、1/1-12/31では今年を含んで表示されたい。

例えば今日6/6での酒登録は、製造年月は2021年が含まれるけど、BYは2020まで。
来月の7/1になったら、BYにも2021が選択肢にでるようになってました。

2021-06-06 14:48 UTC, yonta commented on app/views/sakes/_form.html.erb
> +      <%= year_select_with_japanese_era(id = "sake_brew_year_1i",
あ、BYはそもそも月という概念がないです

2021-06-12 12:36 UTC, exoego commented on app/views/sakes/_form.html.erb
> +      <%= year_select_with_japanese_era(id = "sake_brew_year_1i",
https://github.com/momocus/sakazuki/pull/184/commits/fbb7b70621ff58f71c13202e914d7785c803226f でいいかな？

2021-06-12 12:36 UTC, exoego commented on app/helpers/sakes_helper.rb
> +      [with_japanese_era(to_by(Date.new(year + 1))), year]
to-by 削除しました

2021-06-12 12:36 UTC, exoego commented on app/views/sakes/_form.html.erb
> +      <input type="hidden" id="sake_<%= :brew_year %>_3i" name="sake[<%= :brew_year %>(3i)]" value="1">
removed in https://github.com/momocus/sakazuki/pull/184/commits/df4b87bfd7107b58bdcca1cd8bf997ec351ea4c1

2021-06-13 12:28 UTC, yonta commented on spec/helpers/sakes_helper_spec.rb
> +
```suggestion
```

2021-06-13 12:28 UTC, yonta commented on app/helpers/sakes_helper.rb
> +      [with_japanese_era(to_by(Date.new(year + 1))), year]
:+1:

2021-06-13 12:28 UTC, yonta commented on app/views/sakes/_form.html.erb
> +      <%= year_select_with_japanese_era(id = "sake_brew_year_1i",
🙌

2021-06-13 12:29 UTC, yonta approved these changes
最高！
過去の動作通りに和暦が追加された。やったー！

2021-06-13 12:30 UTC, merged