Chore: Cookpad Style Guide 現時点の最新コミットを inherit
momocus/sakazuki pull request #188
Opened 2021-06-05 12:54 UTC by exoego

https://github.com/momocus/sakazuki/pull/184#discussion_r645980452
> いちおうCookpad Styleguidに従っていきたい気持ち。

2021-06-05 17:08 UTC, yonta commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
なるほど！
rubocop.ymlをinheritすればよいのか、最高。

ところで[cookpad/global-style-guides](https://github.com/cookpad/global-style-guides)と[cookpad/styleguide](https://github.com/cookpad/styleguide)とがあって、違いが何もわからなかった。
styleguideのほうがコミットは新しいけど、global-style-guidesのほうを採用したほうがいいの？

2021-06-05 18:49 UTC, momocus requested changes
rubocopの設定をinheritできること知りませんでした！　すごく便利！！！

2021-06-05 18:49 UTC, momocus commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
rubocopをかけると下記３つのファイルが生成されました。
```sh
.rubocop-https---raw-githubusercontent-com-cookpad-global-style-guides-8221378c9104362be782ec42365ebedb4a4f8863--rubocop-performance-yml
.rubocop-https---raw-githubusercontent-com-cookpad-global-style-guides-8221378c9104362be782ec42365ebedb4a4f8863--rubocop-rails-yml
.rubocop-https---raw-githubusercontent-com-cookpad-global-style-guides-8221378c9104362be782ec42365ebedb4a4f8863--rubocop-ruby-yml
```
[Rubocop Docs](https://docs.rubocop.org/rubocop/configuration.html#inheriting-configuration-from-a-remote-url)によると、inherit_fromで指定したファイルのキャッシュとのことです。
gitで追跡する必要がないので、`.rubocop-https---*`をgitignoreに追加してください。

2021-06-05 18:49 UTC, momocus commented on .rubocop.yml
> +
`erblint --lint-all --autocorrect`もお願いします

2021-06-05 19:38 UTC, yonta commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
クソなが名前キャッシュファイル、コンソールでめちゃ障害になるからなんとかしたいな。

2021-06-05 22:04 UTC, exoego commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
memo: CacheRootDirectory 設定で ./ignore あたりにキャッシュファイルを移動する

2021-06-06 03:48 UTC, exoego commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
```yaml
AllCops:
  CacheRootDirectory: ".rubocop-cache"
```
などとしたところ、キャッシュディレクトリは作られた。
が、このディレクトリは rubocop の lint の結果のキャッシュだけで、 remote からダウンロードしてきたファイルは相変わらずレポジトリのルートに置かれてしまった。

2021-06-06 03:51 UTC, exoego commented on .rubocop.yml
> +
Fixed in https://github.com/momocus/sakazuki/pull/188/commits/50953caf6ead155630678a9d02e74c22c7cbc6c0

2021-06-06 03:52 UTC, exoego commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
とりあえず gitignore するようにしました
https://github.com/momocus/sakazuki/pull/188/commits/bc3e2722629216f285c5ffa62b6378653a9e93fa

2021-06-06 03:55 UTC, exoego commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
あー、どっちもそれなりにメンテされてるみたいですね。
名前から想像すると global-... は Cookpad 海外版、そうでないやつは日本版とかかな？
global-... のほうが ruby/rails/performance と観点ごとにファイルが分割されてて、良さそうな気がしました。
どっちを使いたいとかあればそれに合わせます。

2021-06-06 03:59 UTC, yonta commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
おけー。
コンソールの見た目の問題なので、手元のlsコマンドの設定でなんとかするほうがよいな！

2021-06-06 04:03 UTC, yonta commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
style-guideのが圧倒的スターだった。
個人的にstyle-guideのほうを見てたので、こっちのがいいかなあ。

2021-06-06 04:09 UTC, exoego commented on spec/rails_helper.rb
> +  Rails.logger.debug e.to_s.strip
Note) この変更大丈夫かな？
CI でテストが通ってるから大丈夫っぽいか

2021-06-06 04:12 UTC, yonta commented on spec/rails_helper.rb
> +  Rails.logger.debug e.to_s.strip
見た目は同じくコンソール出力に見える。
記憶の片隅にはいれときます。

2021-06-06 04:13 UTC, exoego commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
スターの多い方にしました

2021-06-06 04:14 UTC, yonta commented on .rubocop.yml
> +  - https://raw.githubusercontent.com/cookpad/global-style-guides/8221378c9104362be782ec42365ebedb4a4f8863/.rubocop.performance.yml
手動変更めっちゃしてくれたあとにすまねえすまねえ

2021-06-06 18:40 UTC, momocus commented on spec/rails_helper.rb
> +  Rails.logger.debug e.to_s.strip
すみません見落としてました。
確認したところ、エラー内容が標準出力に出力されず、ログファイルに出力されるようになってました。
またcookpad/styleguide を適用した場合、`puts e.to_s.strip` はrubocopで検出されませんでした。

2021-06-06 19:36 UTC, momocus commented
ご対応いただいたあとに大変申し訳ないのですが……

cookpad/styleguideをinheritしてbranch rootにrubocopかけたところ、何も検出されませんでした。
よってこのPR内での変更は、rubocop.ymlに関するものだけ残してRevertしていいのかと思いました。

また、どちらのスタイルガイドをinheritしても、[#184(comment)](https://github.com/momocus/sakazuki/pull/184#discussion_r645980452)の発端であるカッコの省略は検出できないことに気づきました。

2021-06-06 19:56 UTC, yonta commented
今回のPRでコーディング規約には甘さがあるし、Rubocopの設定も見直さないといけないことがわかりましたね。
ここまでくるとPRのみで終わりではなく、じゃなく別なIssueとして立て直して、真剣に考えたほうがいいかも。

2021-06-06 19:58 UTC, momocus commented
メソッド呼び出しの括弧の省略を禁止するにはRubocopの[Style/MethodCallWithArgsParentheses](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MethodCallWithArgsParentheses)を有効にすると良さそうでした。ただし、単純に有効化するだけだと誤検出が多かったです。いくつかオプションを精査する必要があります。

で、ここまで調べてしまったので、RubocopのStyle/MethodCallWithArgsParenthesesを適用するのは私がやろうかなと思っています。いいでしょうか？

このPR #188 自体は、CookpadのスタイルガイドをinheritしたらCloseしたい気持ちです。

2021-06-07 04:01 UTC, exoego commented
> このPR #188 自体は、CookpadのスタイルガイドをinheritしたらCloseしたい気持ちです。

こちらの PR で revert や force-push してもいいのですが、経緯として残し、https://github.com/momocus/sakazuki/pull/191 を作りました。

2021-06-07 04:01 UTC, closed without merging