Add: 酒を評価するボタンを追加した
momocus/sakazuki pull request #190
Opened 2021-06-06 15:58 UTC by yonta

close #185

### 今まで

酒を開けると、評価もしないといけなかった。

### これから

酒を開けるのと評価するのを分けた。
酒indexには酒を開けるボタンと、開けて評価するボタンを追加した。
また、開けているが未評価の酒には評価するボタンが表示される。

2021-06-06 16:02 UTC, yonta commented
テストが落ちるのでさらにやる

2021-06-11 12:36 UTC, momocus requested changes
おつです。Request changesあります。

2021-06-11 12:36 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +    # describe "empty bottle column" do end
visitにparam渡す方法わかったとのことなので、やるならやって。やらないならIssue立てといて。

2021-06-12 03:46 UTC, yonta commented on app/views/sakes/_update-sake-bottle-button.html.erb
> +                "data-testid": "open-button-#{sake.id}", }) %>
#182 で対応して

2021-06-12 03:47 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +        end.to change(sealed_sake, :bottle_level).from("sealed").to("opened")
ここCapybaraの範囲内だし{}使いたくない気持ちもある

2021-06-12 03:47 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +        end.to change(sealed_sake, :bottle_level).from("sealed").to("opened")
いや、普通に`expect()`使ってたわ

2021-06-12 04:07 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +        end.to change(sealed_sake, :bottle_level).from("sealed").to("opened")
5fb0592e2267d77139567fced1e09275a65144c1 で修正

2021-06-12 04:09 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +    # describe "empty bottle column" do end
commit 0ae18219b05c8cf8fc41fb8348c959f3114f2240 でやった

2021-06-12 04:15 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  end
commit 4fca9fb8a2932cb0fd2bb3c3194fa8f95ec66ac4 にて対応

2021-06-12 04:16 UTC, yonta commented
対応した

2021-06-12 06:07 UTC, momocus commented on app/views/sakes/_update-sake-bottle-button.html.erb
> +                "data-testid": "open-button-#{sake.id}", }) %>
#182 はログイン動作後のリダイレクトなので、別Issue立てといた-> #197

2021-06-12 06:26 UTC, momocus approved these changes
テストまでばっちりで素晴らしい

2021-06-12 06:26 UTC, merged