サインインリダイレクトとdrink buttonの結合テストを追加
momocus/sakazuki pull request #205
Opened 2021-06-15 04:20 UTC by yonta

close #204

### その他やったこと

- raiseにメッセージを書いた
  - 書け、無名メッセージ絶対許さない

2021-06-15 09:20 UTC, momocus requested changes
メッセージなしのraise書いた件は本当に申し訳ございません。

2021-06-15 09:20 UTC, momocus commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  describe "open button of sealed sake" do
2つ目のbefore文は削除して、`discribe`の引数に`js:true`オプション渡してあげるのがよさげ。
```rb
describe "open button of sealed sake", js: true do
  ...
end
```
Capybara.rbで`Capybara.javascript_driver = :selenium_headless`を指定しているから、これでいいはず。
https://github.com/teamcapybara/capybara/blob/master/README.md#using-capybara-with-rspec

2021-06-15 09:20 UTC, momocus commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  describe "empty button" do
同上。`js: true`を渡そう。

2021-06-15 09:24 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +      # クエリ "?sake[bottle_level]=opened" 部を無視する
1はいらない。それはdrink-buttonテストに含まれる。
2、3はあってもいい。書くか。

2021-06-15 09:26 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  describe "open button of sealed sake" do
そう思うじゃん。
以前、`js: true`したら効かなかった。
原因はわからない。
まあ念の為もう一度やってみるか。

2021-06-18 09:21 UTC, momocus commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  describe "open button of sealed sake" do
このへんうまくいかないのはCapybaraの設定かRspecの設定が間違ってるせいっぽい。
このPRではこのままにしといて、別Issueで扱うのがよいと思う。

2021-06-18 09:25 UTC, momocus commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  describe "open button of sealed sake" do
#209 立てました。

2021-06-19 02:53 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +      # クエリ "?sake[bottle_level]=opened" 部を無視する
やっぱりいらない。それはリダイレクト関係なくdrink-buttonの機能しか言っていない

2021-06-19 03:00 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  before do
Fix by #d12f50066f6ea07bc1a267e1a137eeabf752bca4

ただし、rack_testとselenium_headlessはログイン状態を共有していないようなので、不格好なコードにはなる。

2021-06-19 03:01 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +      visit sakes_path
Fix by #d12f50066f6ea07bc1a267e1a137eeabf752bca4

2021-06-19 03:02 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  describe "open button of sealed sake" do
👍

2021-06-19 04:45 UTC, momocus commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +      # クエリ "?sake[bottle_level]=opened" 部を無視する
りょ

2021-06-19 04:52 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +      sign_out(user)
fix by 19ab2f8ed510980f40504a1e5cdc410436ddebe8

2021-06-19 05:20 UTC, momocus commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +  before do
#209 でどうにかしよう

2021-06-19 05:21 UTC, momocus approved these changes
👍

2021-06-19 05:21 UTC, merged

2021-06-19 06:00 UTC, yonta commented on spec/system/signin_redirect_integrating_drinkbutton_spec.rb
> +      # クエリ "?sake[bottle_level]=opened" 部を無視する
書いてmasterにいれちった
52cf5fab20f40aedb3798d4645263dffe7d48f79