Bootstrap5化:rocket:
momocus/sakazuki pull request #218
Opened 2021-06-22 09:52 UTC by yonta

close #194 

やったぞ！Bootstrap5だ！

### やったこと

- Bootstrap5の導入
  - 使っていないBootstrap5プラグインJSは読み込んでおらず、コメントアウトしたJSを追加してある。
  - 特定のプラグインが依存する@popperjs/coreパッケージも入れていない
- Bootstrap5に対応した
  - 変更が多いので頑張った、大幅にerbが変更してある

2021-06-22 16:12 UTC, momocus requested changes
おつかれさまです。Bootstrap5めっちゃいいね！
修正してほしいところいくつかあるから、もうちょっとだけ頑張っておくれ🙏

2021-06-23 07:58 UTC, yonta commented on app/views/devise/confirmations/new.html.erb
> +  <div class="devise-row mt-2 justify-content-center">
commit 71b70dce3d4c441b8d00c27773426ed25a0076b1 で対応

2021-06-24 05:31 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.index-sake-name-link {
commit  448a4f2228dfc915e37fce94dc8ae5f1f2a1308f で対応

2021-06-24 05:35 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.form-half-form-lg {
`-lg`はbootstrapと同じ画面サイズがlg以上なら有効の意。
formはHTMLの用語で、テキスト・セレクタ・各種インプットの総称。

二段組フォームの意があるとよいな。

2021-06-24 05:35 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.form-half-form-lg {
`two-columns-form`かな

2021-06-24 05:56 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.form-half-form-lg {
commit 7c06b54fbe63fb27ba49addd7e1c6a12e430ed29 で対応

2021-06-24 05:57 UTC, yonta commented on app/javascript/src/stylesheet/application.scss
> +.form-half-form {
このスタイルは年月日限定のスタイルではない。
スタイルの意味を踏襲した名前付のほうがよい。

2021-06-24 09:36 UTC, momocus approved these changes
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

2021-06-24 09:37 UTC, merged