日本酒の在庫量を表示するようにした
momocus/sakazuki pull request #227
Opened 2021-07-05 09:43 UTC by yonta

### やったこと

- 日本酒の量を尺貫法で酒indexに表示した
  - これで在庫が一瞬で丸わかり
  - 買いすぎも飲みすぎも防げるね
- 開封済みの酒瓶は半量を計算することにし、ざっくり計算にした。

![Uploading image.png…]()

### びこー

- ここに表記でいいのか？

2021-07-07 18:53 UTC, momocus requested changes
呑兵衛にとってとても大切な機能ですね。ありがとう。

2021-07-07 18:53 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  def to_shakkan(amount)
180000mlのときに"1石0斗0升0合"になる。"1石"にしたい。
180180mlなら"1石1合"というように、値が0になる桁の単位は表示したくない。
0mlのときは悩みどころ。何も表示しないか、0合って表示するか。どっちがいいかな？

2021-07-07 18:53 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  UNITS = %w[合 升 斗 石]
`private`の中に入れても定数はprivateにならないんだってさ。
pryとかで`SakesHelper::UNITS`したら外部から参照できちゃうことがわかるよ。

定数をprivateで使いたいときは[private_constant](https://docs.ruby-lang.org/ja/latest/method/Module/i/private_constant.html)を使ってね。

2021-07-07 18:53 UTC, momocus commented on app/models/sake.rb
> +  def self.alcohol_stock(include_empty: false)
include_empty: true のユースケースがわからん。いらなくない？

2021-07-07 18:53 UTC, momocus commented on app/views/sakes/index.html.erb
> +<h2><%= "#{t('.title')} - #{to_shakkan(Sake.alcohol_stock)}" %></h2>
主張が強くて笑った。どこにどう表示するかは後で考えようね。
![image](https://user-images.githubusercontent.com/6294782/124813307-aff81f80-df9f-11eb-8edc-b0e3ea24d6f9.png)

2021-07-08 11:14 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def to_shakkan(amount)
いい指摘。
0mlのときは0合表示、1斗0合の0合は表示したくないね。
なおそ。

2021-07-08 11:14 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  UNITS = %w[合 升 斗 石]
知らんかったからたすかる～

2021-07-08 11:15 UTC, yonta commented on app/models/sake.rb
> +  def self.alcohol_stock(include_empty: false)
`alcohol_stock(include_empty: true) - alcohol_stock`すると飲んだ量出せるなぁとか、空き瓶込みで表示してるときは残量も全体表示したいなぁと。
書いてて、空き瓶込みの検索のときは空き瓶込みで出すほうが親切っぽいから実装するわ。

2021-07-08 11:15 UTC, yonta commented on app/views/sakes/index.html.erb
> +<h2><%= "#{t('.title')} - #{to_shakkan(Sake.alcohol_stock)}" %></h2>
それ。いいデザイン頼む。
日本酒リストにTooltipとToastとか普段は隠れているやつでいい表示ほしい。

2021-07-08 14:32 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  UNITS = %w[合 升 斗 石]
commit 5507c1db0e966476e63d42ca7622360a39f39249 で対応

2021-07-08 14:32 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def to_shakkan(amount)
commit 01344e6a5b0b8eadae0a3a071cc13b117ff46cae で対応

2021-07-08 14:42 UTC, yonta commented on app/models/sake.rb
> +  def self.alcohol_stock(include_empty: false)
隠し機能的に空き瓶込みで検索したら総量表示にしてみた。
そのうちかっこいいビューつけるときにまた考えよう

2021-07-08 14:44 UTC, yonta commented on app/models/sake.rb
> +  def self.alcohol_stock(include_empty: false)
commit f367810f67277bde763cbefa72d4809ffd3875f8 で対応

2021-07-09 06:52 UTC, momocus requested changes

2021-07-09 06:52 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  def to_shakkan(amount)
180ml未満のとき無になる
![image](https://user-images.githubusercontent.com/6294782/125034996-3d389280-e0cc-11eb-99f3-9c3ee6b12df0.png)

2021-07-09 06:55 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def to_shakkan(amount)
ああああああああああああああああ！！！！！！！！！😱

2021-07-09 06:58 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def to_shakkan(amount)
commit fd15bae3beab8750b913ce947f1c01a0d75c0440 で対応

2021-07-09 06:59 UTC, momocus approved these changes
👍

2021-07-09 07:00 UTC, merged