Indexで開封する・空にするボタンを押したあとIndexにリダイレクトするようにした
momocus/sakazuki pull request #234
Opened 2021-07-13 11:12 UTC by momocus

Close #197

- Indexで開封する・空にするボタンを押したあとIndexにリダイレクトするようにした。
- ユーザーが誤って開封する・空にするボタンを押してしまったときには修正できるように、酒編集後に表示するflashメッセージに酒詳細ページへのリンクを入れた。
![image](https://user-images.githubusercontent.com/6294782/125441627-3638eb51-f453-4321-8efe-913b7ac23371.png)
- おまけに、酒作成や削除時のFlashメッセージに酒の名前を表示するようにした。
![image](https://user-images.githubusercontent.com/6294782/125442142-546ea587-0334-4d13-b0ee-65ba99da5257.png)

2021-07-13 15:34 UTC, yonta requested changes
気づいたら21件レビューつけてた

2021-07-13 15:34 UTC, yonta commented on app/controllers/sakes_controller.rb
> +  # 上記のどちらにも当てはまらない場合: ユーザーが直前にいたページにリダイレクト
YARDはアブスト、詳細を区切ると判定してくれるよ
```suggestion
  # update後のリダイレクト処理
  #
  # 編集画面からupdateする場合: 詳細ページにリダイレクト
  # HTTP_REFERERが設定されていない場合: 詳細ページにリダイレクト
  # 上記のどちらにも当てはまらない場合: ユーザーが直前にいたページにリダイレクト
```

2021-07-13 15:34 UTC, yonta commented on app/controllers/sakes_controller.rb
> +  # 上記のどちらにも当てはまらない場合: ユーザーが直前にいたページにリダイレクト
あとコロン使うよりも文章を書いたほうがいい。

```ruby
# ○○の場合は△△される。
# ××の場合は□□される
```

でいいと思う

2021-07-13 15:34 UTC, yonta commented on app/controllers/sakes_controller.rb
> +  # @return [Boolean] 編集画面からUpdateが行われた
true/falseのときは、true なら○○、や、○○のときにtrue、って書いたほうがいい。
どっちがtrueかが大事だが、どちらの場合がtrueかの考えには個人差がある。
ので、それを明示したほうがいい。

2021-07-13 15:34 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    request.referer && request.referer.match?("\/sakes/.*\/edit")
```suggestion
    request.referer && request.referer.match?("\/sakes\/[0-9]+\/edit")
```

2021-07-13 15:34 UTC, yonta commented on app/controllers/sakes_controller.rb
> +  def redirect_after_update
コメントを見ると3パターン書いてある。
けど、処理を見ると一致シてないように見える。
1なら詳細にリダイレクト、その他はユーザが直前にいたページにリダイレクト、に見える。

2021-07-13 15:34 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +        end
`accespt_confirm`したあとに`wait_for_alert`入れたほうが良さそう。

最初のテストはアラート出る前に判定して間違ったテストかもしれない。
他のテストはalertを探しに行ってるから、偶然waitしているだけ。

2021-07-13 15:34 UTC, yonta commented on app/views/layouts/_flashes.html.erb
> +  <div class="alert alert-<%= bootstrap_alert(message_type) %>" data-testid="alert">
alertというクラス名と重複する名前よりも、flash-messageとか名前はどうだろう。
findがtestidに限らず、classやidを全探索しちゃう仕様だった気がする。
上からのメッセージを意味してて、より良いと思う。

2021-07-13 15:34 UTC, yonta commented on app/views/sakes/_form.html.erb
> +      <%= form.submit(class: "btn btn-primary mx-3", "data-testid": "submit") %>
ここも同上。
submitボタンにsubmitと名前をつけても、判別がつかない。
form-submitとか、submit-update-sakeとか

2021-07-13 15:34 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +        expect(find(:test_id, "alert")).to have_link(sealed_sake.name, href: sake_path(sealed_sake.id))
このテスト、きれいでよい。
文面が変わっても本質的なリンクを持っていることを要求してて、変更に強いテスト。

2021-07-13 15:34 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +      it "redirects to index page" do
indexにいたのにredirectsか？いや確かにredirectしてるけど、うーん？、と思ってしまった。
`it "keeps index page" do`とか？

2021-07-13 15:34 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +      it "redirects to index page" do
下記にも書いたけど、index -> index遷移でredirectなんだけどredirectと言われるとはて

2021-07-13 15:34 UTC, yonta commented on spec/system/drink_buttons_spec.rb
>          end
ここも`wait_for_alert`が必要

2021-07-13 15:34 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +      it "has link to the updated sake" do
itが示すのは`describe "clicking open button of sealed bottle", js: true do`のクリック動作かそれによるページのことなので、以下のように書くといいと思う。
```suggestion
      it "has flash message which has link to the updated sake" do
```
もしくは、`it "makes flash message which....`とか

2021-07-13 15:34 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +      it "has link to the updated sake" do
同上

2021-07-13 15:34 UTC, yonta commented on spec/system/sake_update_spec.rb
> +
```suggestion
```

2021-07-13 15:34 UTC, yonta commented on spec/system/sake_update_spec.rb
> +    it "redirect to sake page" do
はー、indexとshowでどこにredirectされるか違うのか。
めっちゃ良く出来てる。よき！:+1:

2021-07-13 16:40 UTC, momocus commented on app/controllers/application_controller.rb
> +  # @param path [String]
`@param id [Type] description` の順が公式の推しっぽいし、idとdescriptionの区別がしやすくてわかりやすい。
ほかのところも後で直そう。→ #237

2021-07-13 16:48 UTC, momocus commented on app/controllers/application_controller.rb
> +  def alert_link_tag(text, path)
helperはviewから呼び出すメソッドを書くところなので違う。
将来ほかのコントローラーでも使えた方が便利かもと思ってapplication_controllerに入れたけど、今んとこ将来使う予定はないしsakes_controller内のprivateメソッドでもいいかも。

2021-07-13 17:01 UTC, momocus commented on app/controllers/sakes_controller.rb
> +  def redirect_after_update
コメントに書いた動作はあってる。内部の処理は↓のような分岐になっている。

- 編集画面からupdateする場合
  - 詳細ページにリダイレクト
- 編集画面からupdateしない場合
  - HTTP_REFERERが設定されている
    - ユーザーが直前にいたページにリダイレクト 
  - HTTP_REFERERが設定されていない
    - 詳細ページにリダイレクト

2021-07-13 17:03 UTC, momocus commented on app/controllers/application_controller.rb
> +  def alert_link_tag(text, path)
モジュール化して app/controllers/concerns に入れておくといいかも。

2021-07-13 17:17 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +      it "has link to the updated sake" do
thx
DeepL先生に聞いたらwhich has よりcontaining のほうがよさそうだった

2021-07-13 17:17 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +        expect(find(:test_id, "alert")).to have_link(sealed_sake.name, href: sake_path(sealed_sake.id))
照れるわ

2021-07-13 17:18 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +      it "redirects to index page" do
reloadにするわ

2021-07-13 17:54 UTC, momocus commented on app/controllers/application_controller.rb
> +  # @param path [String]
Fixed at 00ed514c2d77721fb737e9a1b8bb4c92ff267651

2021-07-13 17:54 UTC, momocus commented on app/controllers/application_controller.rb
> +  # @param path [String]
説明を追加した
Fixed at 00ed514

2021-07-13 17:55 UTC, momocus commented on app/controllers/sakes_controller.rb
> +          flash[:notice] = t("controllers.sake.success.update", name: alert_link_tag(@sake.name, sake_path(@sake)))
Fixed at f49959bee4b2d5df28cac5f69c434097ff7b5896

2021-07-13 17:56 UTC, momocus commented on app/controllers/sakes_controller.rb
> +  # 上記のどちらにも当てはまらない場合: ユーザーが直前にいたページにリダイレクト
Fixed at 1b289e470e461c311efc009ec14364ee87d63734

2021-07-13 17:57 UTC, momocus commented on app/controllers/sakes_controller.rb
> +  # @return [Boolean] 編集画面からUpdateが行われた
Fixed at 1b289e4

2021-07-13 17:57 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +        end
Fixed at 237c6a400fe466b1bceecccdc15becf429107f0b

2021-07-13 18:01 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +      it "redirects to index page" do
reloadにしました
Fixed at 237c6a4

2021-07-13 18:01 UTC, momocus commented on spec/system/drink_buttons_spec.rb
>          end
Fixed at 237c6a4

2021-07-13 18:01 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +      it "has link to the updated sake" do
Fixed at 237c6a4

2021-07-13 18:03 UTC, momocus commented on app/controllers/sakes_controller.rb
> +          flash[:notice] = t("controllers.sake.success.create", name: @sake.name)
しょうがないにゃあ🐈
やります

2021-07-13 18:04 UTC, momocus commented on spec/system/sake_update_spec.rb
> +    it "redirect to sake page" do
もっと褒めて

2021-07-13 18:07 UTC, momocus commented on config/locales/controllers/application.ja.yml
> +        destroy: "%{name}を削除しました。"
半角スペース入れた
Fixed at 9e6ad3da55124687c294ad05c44c2a1df7bd96b2

2021-07-14 06:01 UTC, yonta commented on app/controllers/application_controller.rb
> +  # @param path [String]
exampleもついてgood

2021-07-14 06:05 UTC, yonta commented on app/controllers/application_controller.rb
> +  def alert_link_tag(text, path)
とりあえずprivateにしとこ。
concernsはまた別な使いみちもあるけど、controller向けのhelper入れるのにもよさそうね。
覚えておいて、よりcontrollerが長くなったら考えよ。

2021-07-14 06:12 UTC, momocus commented on app/controllers/application_controller.rb
> +  def alert_link_tag(text, path)
Fixed at 8b260aa

2021-07-14 06:20 UTC, momocus commented on app/views/sakes/_form.html.erb
> +      <%= form.submit(class: "btn btn-primary mx-3", "data-testid": "submit") %>
form-submitにしました。_formはupdateだけでなくcreateの時にも使われるため。
Fixed at 22c0442

2021-07-14 06:20 UTC, momocus commented on app/views/layouts/_flashes.html.erb
> +  <div class="alert alert-<%= bootstrap_alert(message_type) %>" data-testid="alert">
Fixed at 22c0442

2021-07-14 06:20 UTC, momocus commented on spec/system/sake_update_spec.rb
> +
Fixed at 22c0442

2021-07-14 07:30 UTC, momocus commented on app/controllers/sakes_controller.rb
> +          flash[:notice] = t("controllers.sake.success.create", name: @sake.name)
Fixed at cb7ed3036c44f0e80df27a984f7afa2a5cc5b01f

2021-07-14 08:27 UTC, yonta commented on app/controllers/sakes_controller.rb
> +          flash[:notice] = t("controllers.sake.success.create", name: @sake.name)
😺:+1:

2021-07-14 08:29 UTC, yonta reviewed
もう少しだけ

2021-07-14 08:29 UTC, yonta commented on spec/system/sake_create_spec.rb
> +      fill_in("name-textfield", with: sake_name)
ここもdata-testidで名前つけちゃっていいね

2021-07-14 08:29 UTC, yonta commented on spec/system/sake_update_spec.rb
> +      expect(find(".alert")).to have_link(sake_name, href: sake_path(sake_id))
CSSのclass nameよりもdata-testidのほうをテストでは優先的に使って。
そのほうが変更に強いテストになってよりよい。
せっかくflash-messageって名前つけたので使ってあげて。

2021-07-14 09:21 UTC, momocus commented on spec/system/sake_update_spec.rb
> +      expect(find(".alert")).to have_link(sake_name, href: sake_path(sake_id))
Fixed at 0045eb2
wait_for_alertも修正しました

2021-07-14 09:22 UTC, momocus commented on spec/system/sake_create_spec.rb
> +      fill_in("name-textfield", with: sake_name)
Fixed at 0045eb2

2021-07-14 10:48 UTC, yonta approved these changes

2021-07-14 10:48 UTC, merged