Webpackerの構成を正した
momocus/sakazuki pull request #243
Opened 2021-07-31 08:50 UTC by yonta

masterテストしたらうっかりクローズされたので再作成

close #241 

### やったこと

- Sprocketsの完全削除と無効化
  - フォルダを残しておいたら、間違ったファイル配置がされるので完全に無効化した
  - Sprocketsは使わず、JS/style/imageのような静的ファイルはwebpackerを使って管理する
- logoファイルの移動
  - webpacker管理化にした
- webpacker管理フォルダ構成の変更
- webpackerのpack_tagの呼び出しを正した
  - 今まで複数回呼んでいたが、公式ドキュメントにやるなって書いてあった
  - `content_for`を使ってページごとに呼び出すpack_tagをうまく変更した
  - js/styleは`<head>`タグ内に置くようにした
    - それに伴い、一部TSをDOMが読み込まれてから動作するように変更した

### やらなかったこと

- スタイルは別ファイルに分けなかった
  - 結局どのページでも読み込まれるbootstrapのファイルサイズが大きいため、分けても効果が薄い
  - 名前空間を分けることはできるが、それ以上に複数回bootstrapが読み込まれることによる転送ファイルサイズ増加が大きい
  - webpackでうまくやる手段がありそうだけど、わかっていない

2021-07-31 10:24 UTC, momocus commented
Docker環境にて、railsサーバー起動後ブラウザでアクセスすると下記エラーが出ました。
```
Webpacker::Manifest::MissingEntryError at /
Webpacker can't find common.js in /sakazuki/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
```

2021-08-02 14:09 UTC, yonta commented
直したはず！

2021-08-04 10:58 UTC, momocus requested changes
Webpacker完全に理解しててすごい

2021-08-04 10:58 UTC, momocus commented on app/views/layouts/application.html.erb
> +    <% if yield(:pack_style).empty? %>
content_for? メソッドを使おう
https://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for-3F

2021-08-04 10:58 UTC, momocus commented on app/views/layouts/application.html.erb
> +    <% if yield(:pack_js).empty? %>
同上

2021-08-06 07:38 UTC, yonta commented on app/views/layouts/application.html.erb
> +    <% if yield(:pack_style).empty? %>
commit 6305458e90383a1f95c315cedfa6c236ad07db55 で対応

2021-08-06 07:38 UTC, yonta commented on app/views/layouts/application.html.erb
> +    <% if yield(:pack_js).empty? %>
commit 6305458e90383a1f95c315cedfa6c236ad07db55 で対応

2021-08-06 16:57 UTC, momocus approved these changes
👍

2021-08-06 16:58 UTC, merged