Dockerfileをheredoc対応した
momocus/sakazuki pull request #249
Opened 2021-08-25 16:48 UTC by yonta

heredoc書けるようになったよ！

### heredocを使うと

- &&\地獄から抜けれる
- RUNをまとめてスッキリ書ける

### やったこと

- RUNをheredoc化
- apt installの順番を、基本コマンドとSAKAZUKI依存パッケージで分けた
- SAKAZUKI依存パッケージのapt installの順番をセットアップ順に揃えた
- aptのクリーニング作業を1つにまとめた
- nodeのバージョンを次期LTSの14で固定した
  - 12もLTS、新しいLTS出たので更新した。

### 参考

- https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/

2021-08-25 16:49 UTC, yonta commented
hadolintがheredoc対応していないので、Checkが失敗するはず。
なので、このPRはhadolintのバージョンアップ待ち。

2021-09-15 09:15 UTC, yonta commented
Issue立てたら対応してもらえた。
GitHub ActionsのHadolintのリリースに取り込んでもらえるか待ち

2022-02-05 20:00 UTC, yonta commented
memo: hadolint v2.8.0から対応。hadolint-action v1.6.0はhadolint v2.7.0なので非対応。

2022-11-08 03:10 UTC, yonta commented
hadolint-actionが対応したのでいけるぞ！

2022-11-10 12:41 UTC, yonta commented
コンフリクトしてる〜〜〜

2022-11-19 08:45 UTC, momocus requested changes
Dockerfileがすっきりして素晴らしい。
&& \の消し忘れがありましたので、修正してね。

2022-11-19 08:45 UTC, momocus commented on Dockerfile
>      > /etc/apt/sources.list.d/pgdg.list && \
```suggestion
    > /etc/apt/sources.list.d/pgdg.list
```

2022-11-19 08:58 UTC, momocus approved these changes

2022-11-19 09:01 UTC, merged