酒Showページのh1見出しを酒の名前にした
momocus/sakazuki pull request #282
Opened 2021-09-15 10:29 UTC by momocus

Close #269

酒Showページのh1見出しを酒の名前にした。
![image](https://user-images.githubusercontent.com/6294782/133416691-4753e7e4-3463-41ff-b6db-45893bd39033.png)

visibility:hiddenのdivタグ作ってwait_for_page用のdata-tesidをつけたけど、これでいいかな？

2021-09-15 17:54 UTC, yonta requested changes

2021-09-15 17:54 UTC, yonta commented on app/views/sakes/show.html.erb
> +<h1 data-testid="sake-name"><%= @sake.name %></h1>
`hidden`な`div`使わずに、`h1`にまとめていいと思う。
`sake-name`を呼び出すテストのほうを`sake_path(@sake)`を使って名前を探すように変更すればいいんじゃないかな。

2021-09-17 18:21 UTC, momocus commented on app/views/sakes/show.html.erb
> +<h1 data-testid="sake-name"><%= @sake.name %></h1>
Fixed at 78dfb3c
hiddenなdivは使うのをやめました。
`sake-name`は削除して、テストのときはh1タグを指定して酒の名前を取得するようにしました。

2021-09-17 20:25 UTC, yonta approved these changes
Great!!!

2021-09-17 20:26 UTC, merged