ドリンクボタンで瓶を開けたり空にしたとき専用のフラッシュメッセージにした
momocus/sakazuki pull request #299
Opened 2021-10-01 06:42 UTC by momocus

Close #238

![image](https://user-images.githubusercontent.com/6294782/135576419-697ca833-bb7e-40ae-8f26-a3c489f60e83.png)
![image](https://user-images.githubusercontent.com/6294782/135576454-9224b242-cb50-4f33-a2ed-d54148012a66.png)

2021-10-01 08:29 UTC, yonta requested changes
開封・空にしたは親切なメッセージなのでぜひほしい！

2021-10-01 08:29 UTC, yonta commented on config/locales/controllers/application.ja.yml
> +        empty: "%{name} を空にしました。"
新機能だけどテストはしない？
この後、drink-buttonのリファクタとともに書けばいいか。

2021-10-01 08:29 UTC, yonta commented on app/controllers/sakes_controller.rb
> -    if update_from_edit?
変更されたのにYARDコメントが古いまま

2021-10-01 08:29 UTC, yonta commented on app/controllers/sakes_controller.rb
> +  # indexからbottle_levelを変更するとき、bottle_levelの値によってフラッシュメッセージを切り替える
YARDコメントなら、1行要約のあとに空行をいれて。

2021-10-01 08:29 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    if  update_from?("index") && params.dig(:sake, :bottle_level)
ifのあとが2スペースになっている。
rufoとかrubocopとかのautoformatterを入れるといいよ。
autoformatterがあれば、保存時とかに自動でフォーマット崩れを直してくれる。

2021-10-01 08:29 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    if  update_from?("index") && params.dig(:sake, :bottle_level)
条件分岐がよくわからない。
patchでemptyに変更されたら、とかで書けないかな。

書けないならHACKなどのコメントがいる複雑さだと思う。
indexページからdrink-buttonでしか更新しない、という前提で動いている。
そのため、index以外にdrink-buttonを設置しても動かないとか、怪しい点が結構ある。

2021-10-01 08:29 UTC, yonta commented on app/controllers/sakes_controller.rb
> +      flash[:success] = t("controllers.sake.success.update", name: alert_link_tag(@sake.name, sake_path(@sake)))
else以後が一緒なんで、digだけの条件分岐でまとめられる

2021-10-02 06:59 UTC, momocus commented
やり方を変えるのでこのプルリクエストはクローズします。
request.refereでボタンが押されたか推測するのはやめ、
drink-buttonにparamsを追加して、コントローラでどのボタンが押されたか判別できるようにします。

2021-10-02 06:59 UTC, closed without merging