ドリンクボタンで瓶を開けたり空にしたとき専用のフラッシュメッセージにした v2
momocus/sakazuki pull request #305
Opened 2021-10-02 08:38 UTC by momocus

Close #238

ドリンクボタンで瓶を開けたり空にしたとき専用のフラッシュメッセージにした
ymlの構成を変更し、Sakesコントローラで翻訳したいときに文字を省略できるようにした。

2021-10-02 09:18 UTC, yonta requested changes
flash-drink-burron2、ぶろん、ぶろん……

2021-10-02 09:18 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    case params.dig(:button)
`button`って一般的すぎるから、`drink-button`のほうが良さそう。
`drink_button`でもよい。使いやすい方を。

2021-10-02 09:18 UTC, yonta commented on app/controllers/sakes_controller.rb
> +      flash[:success] = t(".success", name: alert_link_tag(@sake.name, sake_path(@sake)))
`t()`への引数だけをcaseで変えて、case後にflashするほうがまとまるね。

```ruby
flash[:success] = t(message_key, name: alert_link_tag(@sake.name, sake_path(@sake)))
```

2021-10-02 09:18 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      success: "%{name} を削除しました。"
素晴らしい。
controllerでも省略可能だったんだね。

だったら、`controller/application.ja.yml`もリファクタリングしていいな。
あっちの置き場がおかしいから。

2021-10-03 12:30 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    case params.dig(:button)
いや、flash-createとか、なにが起こるかを名前にしたほうがいいかも。

2021-10-04 08:21 UTC, momocus commented on app/controllers/sakes_controller.rb
> +    case params.dig(:button)
Fixed at 6c1bf8d
viewで何のために指定するかわかりやすいように、`flash_message_type`という名前にしました。

2021-10-04 08:22 UTC, momocus commented on app/controllers/sakes_controller.rb
> +      flash[:success] = t(".success", name: alert_link_tag(@sake.name, sake_path(@sake)))
Fixed at 6c1bf8d

2021-10-04 08:23 UTC, momocus commented on config/locales/controllers/sakes.ja.yml
> +      success: "%{name} を削除しました。"
Fixed at ad45a90

2021-10-04 08:34 UTC, yonta approved these changes
GJ

2021-10-04 08:34 UTC, merged