酒瓶の開封と空にした日時を保存するようにした
momocus/sakazuki pull request #324
Opened 2021-10-12 06:55 UTC by yonta

**dbのmigrateが必要 `rails db:migrate:with_data`**

close #285 （仕様もここに書いてある）

おっきくなっちゃった…

## やったこと

- 酒モデルを変えて開封日・空日を記録できるようにした
- 酒の作成・開封・空・更新日に関するテストを追加した
  - showのviewテストと、systemテスト
- 酒を作成・更新したときに開封日・空日を記録するようにした
  - after_actionを使って実現している
- 酒showで作成・開封・空・更新日を表示するようにした

## 気になること、やってないこと

- showのデザインはこれでいいか
- opened_at、emptied_atはformに用意しておらず、手動で書き換えできないようにしてある

2021-11-09 06:53 UTC, momocus requested changes

2021-11-09 06:53 UTC, momocus commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
`bundle exec rails db:migrate`したらこの行が消される。
do~end文の中でなにもしてないし、そもそも要らないやつ？

2021-11-09 07:05 UTC, yonta commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
これの前にまず #331 を見てこのブランチにマージしておくれやす

2021-11-09 07:11 UTC, yonta commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
これは削除したdata_migrateジェムが生成するやつだから消し忘れだな。消さないと。

2021-11-10 11:09 UTC, momocus commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
#331 マージしました

2021-11-10 13:49 UTC, yonta commented on db/schema.rb
> +    t.datetime "emptied_at", precision: 6
バリデーションがマージされた

2021-11-10 13:49 UTC, yonta commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
thx。
指摘対応する。

2021-11-10 14:12 UTC, yonta commented on db/schema.rb
> +  create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|
commit acf56a43d91dffb75aeb9008ea8d2917cd2af757 で対応

2021-11-11 10:13 UTC, momocus approved these changes

2021-11-11 10:13 UTC, merged

2021-11-12 00:00 UTC, yonta commented
Heroku上でもmigrateお願いします