Google AdSenseを追加した
momocus/sakazuki pull request #357
Opened 2021-11-25 09:29 UTC by yonta

- Refactor: dotenvファイルの必須でない項目をコメントアウトした
- Add: dotenvファイルにAdSenseの設定例を追加した
- Add: production環境でAdSenseタグを挿入されるようにした
- Add: READMEにAdSenseの設定方法を追記

2021-11-27 09:24 UTC, momocus approved these changes
💰👅💰

2021-11-27 09:34 UTC, momocus requested changes
コンフリクトしてるのでmasterにrebaseしてください。
#348 でReadme.mdをautofixしているのとコンフリクトしたみたい。

2021-11-27 09:39 UTC, yonta commented
rebaseした

2021-11-28 08:53 UTC, momocus approved these changes
👍

2021-11-28 08:53 UTC, merged