環境変数FB_APP_IDを削除した
momocus/sakazuki pull request #365
Opened 2021-11-30 09:43 UTC by yonta

シェアするだけなのにAPP_IDなんて使うわけないじゃない！

## やったこと

- FB_APP_IDの使用をやめた
- Tweetボタンとfacebookシェアボタンをまとめて1つのテンプレートビューにした

## 参考

- https://developers.facebook.com/docs/plugins/share-button?locale=ja_JP
- https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

2021-11-30 09:44 UTC, yonta commented
「シェアボタン設定ツール」だとAPP_IDを使われる。
一方で、「全コードサンプル」では使っていない。
これでいいじゃん！

- https://developers.facebook.com/docs/plugins/share-button?locale=ja_JP

2021-11-30 09:46 UTC, yonta commented
`<script>...`をヘルパーで書くのが難しいのでrenderにする。

具体的には、`tag.script(".....")`で書くと、内部のダブルクオートやアンパサンドがエスケープされる。
回避する方法はありそうだが、そもそもヘルパーにする理由がない。
renderによるテンプレートで分離すればよい。

2021-11-30 09:47 UTC, yonta commented
Twitterのドキュメント見てたら、指定するURLが更新されている。
ついでに直しとこ。

- https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

2021-11-30 09:47 UTC, yonta commented
Masterでこっそりテストした。
ちゃんと`FB_APP_ID`なしでも動作した！

2021-11-30 09:49 UTC, yonta commented
さておき、GitHub ActionsのTestが遅い。
Webpackerのassetのビルドがまあまあ長い。

いい感じの記事見つけたので、このキャッシュも次に試してみたいな。

- https://dev.to/codefund/ci-for-ruby-on-rails-github-actions-3mn1

2021-12-01 10:30 UTC, momocus requested changes
コードがすっきりしたね👍

2021-12-01 10:30 UTC, momocus commented on app/views/sakes/_sns-share-button.html.erb
> -  share
消していいんだ

2021-12-01 10:30 UTC, momocus commented on app/views/sakes/_sns-share-button.html.erb
> +  data-layout="button_count">
```suggestion
  data-layout="button">
```
twitterの方はカウント出していないので、facebookもカウント消しましょう。

2021-12-02 03:25 UTC, yonta commented on app/views/sakes/_sns-share-button.html.erb
> -  share
書いておくと、JSロード前に文字列が描画される。
「Tweet」のほうは`<a>`タグになってるので、文字列があるとJSがロードされなくてもリンクがクリックできる。
一方でfacebookのほうがただの`<div>`タグなので、JSになんかあったときに文字列があっても何もできない。
のでそもそも文字列を表示させないほうがよかった。

2021-12-02 03:29 UTC, yonta commented on app/views/sakes/_sns-share-button.html.erb
> +  data-layout="button_count">
はい

2021-12-02 08:17 UTC, momocus approved these changes

2021-12-02 08:17 UTC, merged