Update: 酒showのデザインを一新した
momocus/sakazuki pull request #381
Opened 2022-01-27 05:16 UTC by yonta

酒showのデザインを一新するぞ！！！！

## やったこと

- 酒showをめちゃ変えた

## このPRは？

- new-designの進捗報告、ブランチからブランチへのマージのPR

## 何を見てほしい？

- showデザインへのレビュー
- Rubyの補助関数のレビュー

## まだやってないこと

- デザインのDRY

2022-01-29 08:58 UTC, momocus requested changes
おしゃれになったね！

2022-01-29 08:58 UTC, momocus commented on config/locales/views/sake.ja.yml
> +      tokutei_meisho_none: 特定名称なし
edit画面のlabelinfoとtasteinfoが翻訳されなくなったぞ
![image](https://user-images.githubusercontent.com/6294782/151653404-e4e00ee2-b336-40f8-af81-e8b7d6769e8d.png)

2022-01-29 08:58 UTC, momocus commented on app/views/sakes/show.html.erb
> +  <div class="col-lg-6 mt-lg-0 order-lg-2 col-12 mt-4 order-1">
lgディスプレイで味香りグラフが下に寄ってるのが気になる。
![image](https://user-images.githubusercontent.com/6294782/151653697-4c87da52-a8fc-4a65-ac7c-eaa65e407862.png)

こんなかんじにできない？↓
![show_view](https://user-images.githubusercontent.com/6294782/151653733-19e7be8c-a701-4794-92cf-b295693c7133.png)

2022-01-29 08:58 UTC, momocus commented on app/views/sakes/show.html.erb
> +      <div class="offset-lg-2 mb-lg-0 col-9 mb-2 fs-5">
泡のところに枠とラベルがないぞ
![image](https://user-images.githubusercontent.com/6294782/151654087-f9b87f2d-ed2c-4a6e-b108-08847e5ec9b2.png)

2022-01-29 08:58 UTC, momocus commented on app/views/sakes/show.html.erb
> +<h2 class="mt-4 fs-3"><%= t(".review") %></h2>
左側のラベルと、右側の内容の対応がわかりづらい。
![image](https://user-images.githubusercontent.com/6294782/151654311-8dbb6412-bce8-4c44-bc20-a9c505e7300a.png)

材料とかの欄と同じようにアンダーラインで揃えてみるのはどう？↓ペイントで描いてみた
![image](https://user-images.githubusercontent.com/6294782/151654617-f755ddfc-28c0-4f4e-840f-5f89a28b64e9.png)

2022-01-29 08:58 UTC, momocus commented on app/views/sakes/show.html.erb
> +    </div>
このへんとっ散らかってる感じを受ける。
![image](https://user-images.githubusercontent.com/6294782/151654744-5188e38a-3e40-4bb4-89ad-8194b2387d09.png)

けど具体的にどうしたらいいのかアイデアがない。
Edit画面との兼ね合いもあるだろうし、とりあえず今はこのままでいいか。

2022-01-31 08:03 UTC, yonta commented on config/locales/views/sake.ja.yml
> +      tokutei_meisho_none: 特定名称なし
fix commit bfde6f28f43e92861a2df026c23b4dd8817dca2a

2022-01-31 08:03 UTC, yonta commented on app/views/sakes/show.html.erb
> +  <div class="col-lg-6 mt-lg-0 order-lg-2 col-12 mt-4 order-1">
味と香りのグラフなので、味と香りの横に置いている。
見た目、香り、味、メモで分類している

2022-01-31 08:11 UTC, yonta commented on app/views/sakes/show.html.erb
> +      <div class="offset-lg-2 mb-lg-0 col-9 mb-2 fs-5">
ここ、「炭酸」とか「微炭酸」とか書かせる欄だから、ラベルいらなくね？という気持ち。
味の補助情報として味の下にラベルなしでくっつける感じにしたい。

2022-01-31 08:13 UTC, yonta commented on app/views/sakes/show.html.erb
> +<h2 class="mt-4 fs-3"><%= t(".review") %></h2>
これは強いリジェクト。

材料のように決まった項目をアンダーラインというルール。
なので色やにごりをとりあえずアンダーラインにして、後で別な見やすい表記を探すのはあり。

でも味と香りは定型句でなく文章。
しかも何行になるかわからない。
これは箱スタイルのほうが表示に適してると思う。

2022-01-31 08:19 UTC, yonta commented on app/views/sakes/show.html.erb
> +    </div>
何もわからんけどあんまよくないのはわかる。
どうにかしたい。

2022-02-01 17:33 UTC, yonta commented on app/views/sakes/show.html.erb
> +    </div>
ここは置いておいて、これを参考に先にindex作ったほうがいいかも。
indexとshowのデザインをある程度揃えたほうがわかりやすい気がしてきた。

2022-02-08 10:25 UTC, yonta commented
新しくできた！もう一回Request Review送る。

2022-02-09 10:00 UTC, yonta commented on app/views/sakes/show.html.erb
> +    </div>
新たなPRで更新しました

2022-02-09 10:00 UTC, yonta commented on app/views/sakes/show.html.erb
> +<h2 class="mt-4 fs-3"><%= t(".review") %></h2>
新たなPRで更新しました。
全部箱スタイルにした。

2022-02-09 10:01 UTC, yonta commented on app/views/sakes/show.html.erb
> +      <div class="offset-lg-2 mb-lg-0 col-9 mb-2 fs-5">
新たなPRで修正。
全部箱にした。

色、香り、炭酸はよりよいデザインや入力系にしたいけど、それは別なIssue #46 の出番。

2022-02-09 10:03 UTC, yonta commented on app/views/sakes/show.html.erb
> +  <div class="col-lg-6 mt-lg-0 order-lg-2 col-12 mt-4 order-1">
ここを揃えるのに意味があるからだめです。

![image](https://user-images.githubusercontent.com/849256/153175260-77e82934-0c97-42d4-a0a5-45b3117938a9.png)

2022-02-11 10:05 UTC, merged