酒の好みを評価できるようにした
momocus/sakazuki pull request #382
Opened 2022-01-28 09:38 UTC by yonta

close 369

** db migrateが必要！**

好みの酒を記録できるぞ！！

## やったこと

- 酒モデルにratingカラムを追加
- 酒showページに☆で評価を表示
- 酒formで☆で評価を入力できる
  - ☆入力にはrater-jsを使った

## やってないこと

- rater-jsの☆をbootstrap-icon化
  - bootstrap-iconsのstar.svgの読み込みがRails6だとやっかい
  - Rails7化してから考える、Rails7でもやっかいかもしれない。

2022-01-29 07:56 UTC, momocus requested changes
★★★★☆

2022-01-29 07:56 UTC, momocus commented on spec/views/sakes/show.html.erb_spec.rb
> +  let(:rating_sake) { FactoryBot.create(:sake, rating: 3) }
`no_rating_sake`と`rating_sake`は`describe "rating"`でしか使わないから、`describe "rating"`の中で定義したほうがいいんじゃない？

2022-01-29 07:56 UTC, momocus commented on spec/factories/sakes.rb
> +#  rating           :integer          default(0), not null
ratingに対するvalidationがあった方がいいんでない？

https://railsguides.jp/active_record_validations.html#numericality

2022-01-30 04:55 UTC, yonta commented on spec/views/sakes/show.html.erb_spec.rb
> +  let(:rating_sake) { FactoryBot.create(:sake, rating: 3) }
まじだー。
`let`は先頭宣言しないとRubocopに怒られると思ってた。
`describe`配下にも書いておｋなんだ。やったぜ。

2022-01-30 04:58 UTC, yonta commented on spec/views/sakes/show.html.erb_spec.rb
> +  let(:rating_sake) { FactoryBot.create(:sake, rating: 3) }
commit a4086f51bbfc5ccc25daff13cdef7834d471caf7

2022-01-30 04:59 UTC, yonta commented on spec/factories/sakes.rb
> +#  rating           :integer          default(0), not null
他の酒モデルのバリデーションもつけないとね。
Issue #384 立てサンクス～

2022-01-30 05:33 UTC, yonta commented on spec/factories/sakes.rb
> +#  rating           :integer          default(0), not null
commit 17fa64746cb028b038ceb1c778b00c2c35f30f9b で対応。

devツールで無理やり好みの値に6とか入力すると、下記のように意味がわからないi18n都合のエラーメッセージが出る。
とはいえ、普通に入力する方法はないので、今回は対処しない。

![image](https://user-images.githubusercontent.com/849256/151688010-33305fd0-fead-4239-bd44-262d71fca7ba.png)

2022-02-02 02:27 UTC, momocus approved these changes
★★★★★

2022-02-02 02:27 UTC, merged

2022-02-02 02:46 UTC, momocus commented
本番環境のmigrateもしますた（｀・ω・´）b