お品書きビューを追加
momocus/sakazuki pull request #385
Opened 2022-01-29 10:54 UTC by momocus

### やったこと
- お品書きのビューを追加した（テスト未）
- ビューで使う、下記二つのメソッドを追加した（テスト済）
  - 酒一合当たりの値段を表示するための`selling_price`メソッド
  - 酒が新着かどうかを判定する`new_arrival?`メソッド

https://github.com/momocus/sakazuki/wiki/%E3%81%8A%E5%93%81%E6%9B%B8%E3%81%8D

### このあとやること

- お品書きのビューに対するテスト
- トップページからお品書きページへアクセスできるようリンクを貼る（ハンバーガーメニューに入れるつもり）
  - リンクからアクセスできるかのテスト 

### レビューしてほしいとこ

- お品書きのビューのデザイン
- `selling_price`メソッドと`new_arrival?`メソッドのコード

2022-01-29 17:37 UTC, yonta reviewed
まだViewが見切れていない。
明日も見る。

2022-01-29 17:37 UTC, yonta commented on app/models/sake.rb
> +  OPENED_NEW_LIMIT = 14.days
`private_constant`されてない

2022-01-29 17:37 UTC, yonta commented on app/models/sake.rb
> +  # @return [Boolean] 未開封または1週間以内に購入ならture、さもなくばfalse
YARDドキュメントとコードの内容があっていない。

2022-01-29 17:37 UTC, yonta commented on app/models/sake.rb
> +                  end
ワンライナーでやろうとせず、一時変数`new_limit`を作ったほうが見やすいと思う

2022-01-29 17:37 UTC, yonta commented on app/packs/entrypoints/sakes/drink_menu.js
> +// empty entry point
GOOOOD

2022-01-29 17:37 UTC, yonta commented on app/packs/entrypoints/sakes/drink_menu.scss
> +$accent: #b7282e;
将来的にアクセントカラーをどう取り扱うか考えないといけないね。
今はこのままでいいと思う。

現状、bootstrapにはアクセントカラーをいれていない。

1. bootstrapのprimaryに紺色、secondaryに茜色をいれる。今のsecondaryはlightにする。
2. bootstrapの名前に合わせた`accent-text`などのアクセントカラークラスをたくさん定義する

2022-01-29 17:37 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +                  { class: "text-decoration-none text-dark name-link" }) %>
`{}`いらなくない？

2022-01-29 17:37 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +      <%= link_to(sake.name.to_s, sake_path(sake.id),
`sake.name.to_s`ってstringをstringにしてない？

2022-01-29 17:37 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  # 値段が計算できない場合は"時価"を返す
メソッド概要は1行で。概要のあとは空行いれる。

2022-01-29 17:37 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def selling_price(price, size)
priceを返すなら返り値の型はIntegerかFloat。
Floatにして失敗したときは`NaN`を返すのが妥当だと思う。

2022-01-29 17:37 UTC, yonta commented on spec/helpers/sakes_helper_spec.rb
> +      # 利率を1.5にしてテスト
なんで1.5にするの？
3のままテストしないの？

可変だとしたら別利率のテストは有用。
今回は3固定なのでシンプルなヘルパーテストでいいと思う。

2022-01-29 17:37 UTC, yonta commented on spec/helpers/sakes_helper_spec.rb
> +    end
0mlのテストがない。
たぶんコケるよね。

2022-01-29 17:37 UTC, yonta commented on spec/models/sake_spec.rb
> +    end
先と同上。
変えるインタフェースのない変数を、どうして変えてテストするの？

2022-01-29 17:51 UTC, yonta reviewed
思いつき

2022-01-29 17:51 UTC, yonta commented on app/models/sake.rb
> +  # @return [Boolean] 未開封または1週間以内に購入ならture、さもなくばfalse
これで仕様は本当にいい？
例えば、土曜の朝に登録して、2週間後の土曜の夜には、同じ土曜だけど新規じゃなくなる。
日の途中の利用中にNewだったり違うかったりするの不思議になりそう。
日時だけで比較するために、時間をうまく0にする必要があると思う。

2022-01-30 04:53 UTC, yonta requested changes
崩れてしまった

2022-01-30 04:53 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +    <div class="col-auto" style="max-width: 60%;">
max60%使用すると、スマホの画面サイズが小さいと崩れる。
スマホのときにmaxを減らすか、スマホのときは新着のフォントサイズを小さくする必要がある。
もしくは全体のフォントサイズを小さくする。

![image](https://user-images.githubusercontent.com/849256/151687128-7fb0a4b7-bc29-4adf-8b02-aeea7b0e51c1.png)

2022-02-02 02:32 UTC, momocus commented on app/packs/entrypoints/sakes/drink_menu.scss
> +@import url("https://fonts.googleapis.com/css2?family=Yuji+Syuku&display=swap");
yeah

2022-02-02 02:40 UTC, momocus commented on app/packs/entrypoints/sakes/drink_menu.scss
> +  font-family: "Yuji Syuku", serif;
Yuji SyukuとYuji Boku（とYuji Mai）、漢字のフォントは一緒で、ひらがなやカタカナが違うのよね。
漢字とひらがな/かたかなの統一感があるのがいいなと思って、Yuji Syukuにしたわ。
![image](https://user-images.githubusercontent.com/6294782/152084819-b744e433-f795-4fcb-8648-e8d859d5e553.png)

2022-02-02 02:47 UTC, momocus commented on app/models/sake.rb
> +  OPENED_NEW_LIMIT = 14.days
oops

2022-02-02 02:48 UTC, momocus commented on app/models/sake.rb
> +  # @return [Boolean] 未開封または1週間以内に購入ならture、さもなくばfalse
oops

2022-02-02 06:31 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +      # 利率を1.5にしてテスト
テストを書いたときは利率を1.5にしてた。あとで利率は変えるかもなーと思ってstub_constしてた。

でも現状、利率の値を3変えたあとちゃんと動いているかわからないね。
定数値に応じて計算結果が変わることをテストするため、利率1.5のテストは残しておいて、利率3のテストを追加しようと思う。

2022-02-02 06:32 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +    end
ｱｰ

2022-02-02 06:35 UTC, momocus commented on spec/models/sake_spec.rb
> +    end
これから使ってみて変える可能性が高い定数なので、stub_constしておいて、定数値の変更してもテスト書き直さなくていいようにしている。
同上で、定数値を変えたときのテストも書く。

2022-02-02 06:40 UTC, momocus commented on app/models/sake.rb
> +  # @return [Boolean] 未開封または1週間以内に購入ならture、さもなくばfalse
created_atをto_dateして、日付だけで比較するようにします

2022-02-02 06:41 UTC, momocus commented on app/views/sakes/drink_menu.html.erb
> +    <div class="col-auto" style="max-width: 60%;">
😢

2022-02-02 06:42 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  def selling_price(price, size)
売値の計算と、お品書き用の文字列の整形という二つの役割がこのメソッドにあるのがよくないね。
メソッドを分割します。

2022-02-02 07:26 UTC, momocus commented on app/views/sakes/drink_menu.html.erb
> +      <%= link_to(sake.name.to_s, sake_path(sake.id),
ほんまや

2022-02-02 07:33 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  private_constant :INTEREST_RATE
Fixed at 156479f769255a8010c08ac01798c9fb1635d9b2

2022-02-02 07:34 UTC, momocus commented on app/models/sake.rb
> +  OPENED_NEW_LIMIT = 14.days
Fixed at 9d64ec159a9b63bf1564ba54542ec1f119cb2dad

2022-02-02 07:35 UTC, momocus commented on app/models/sake.rb
> +  # @return [Boolean] 未開封または1週間以内に購入ならture、さもなくばfalse
Fixed at 145904ff37a78784c321f8ca95e9286da16a1d63

2022-02-02 07:35 UTC, momocus commented on app/models/sake.rb
> +                  end
Fixed at 145904ff37a78784c321f8ca95e9286da16a1d63

2022-02-02 07:36 UTC, momocus commented on app/models/sake.rb
> +  # @return [Boolean] 未開封または1週間以内に購入ならture、さもなくばfalse
Fixed at c9b01aad77e32c1ab0dca8f8ef8e7394ef5fb99b

2022-02-02 08:17 UTC, yonta commented on app/packs/entrypoints/sakes/drink_menu.scss
> +  font-family: "Yuji Syuku", serif;
並べてくれて見やすい。漢字崩すと見づらいし、Bokuくらいでもいいかなとも思う。
とりあえずShukuで実装でもいいかなぁ。

2022-02-02 08:20 UTC, yonta commented on app/models/sake.rb
> +  # @return [Boolean] 未開封または1週間以内に購入ならture、さもなくばfalse
そもそも`OPENED_NEW_LIMIT`に分離する必要なくない？

2022-02-02 09:18 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  def selling_price(price, size)
Fixed at e98854f88a1b4d958140d8617a46e4ccca003867 2a21bb6a918e883a4abf8c562e032372f31bef65

2022-02-02 09:20 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +    end
Fixed at e98854f
売値の計算メソッドはSakeモデルのメソッドにしました。
Sake.selling_priceメソッドのテストに0mlのテストを追加しました。

2022-02-02 09:22 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  # 値段が計算できない場合は"時価"を返す
Fixed at e98854f 2a21bb6
このメソッドは2つに分割して、それぞれでYARDコメント書きました。

2022-02-03 05:50 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +                  { class: "text-decoration-none text-dark name-link" }) %>
治ってない

2022-02-03 06:26 UTC, yonta reviewed
現状でさらに見た

2022-02-03 06:26 UTC, yonta commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
`ceil(-1)`の返り値はIntegerクラスだから`to_i`の必要はない。

2022-02-03 06:26 UTC, yonta commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
それっぽい数値並べたい。
```suggestion
    upcasted = (price.to_f / size * 180 * INTEREST_RATE).ceil(-2)
    upcasted > 0 ? upcasted - 20 : nil
```

2022-02-03 06:26 UTC, yonta commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
0円のときそのまま0円がメニューに並んでしまう。
0円は時価にしといたほうがよさそう。

2022-02-03 06:26 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +    <div class="col-auto" style="max-width: 60%;">
未完

2022-02-03 06:26 UTC, yonta commented on app/models/sake.rb
> +    created_at.to_date >= Time.zone.today.ago(new_limit)
```suggestion
    new_limit = sealed? ? 28 : 14
    Time.zone.today - created_at.to_date >= new_limit
```

2022-02-03 06:26 UTC, yonta commented on spec/helpers/sakes_helper_spec.rb
> +        expect(price_tag(1234)).to eq("1234円")
i18n化されてない

2022-02-03 06:26 UTC, yonta commented on spec/models/sake_spec.rb
> +      stub_const("#{described_class}::OPENED_NEW_LIMIT", 7.days)
stub_constしない

2022-02-03 06:26 UTC, yonta commented on spec/models/sake_spec.rb
> +      it { expect(sake.selling_price).to eq(470) }
`it "returns nil/470" do`と書いてね

2022-02-03 16:50 UTC, momocus commented on spec/models/sake_spec.rb
> +    end
Fixed at 6a4482814f5a6841e284b314b2d84af9dfe4ff4f

ユーザーに変えさせるつもりがない値なので、定数じゃなくて内部変数にしました。
値を変えたくなったらテストも書き替えよ。

2022-02-03 16:50 UTC, momocus commented on app/models/sake.rb
> +  private_constant :OPENED_NEW_LIMIT
Fixed at 6a4482814f5a6841e284b314b2d84af9dfe4ff4f

2022-02-03 16:52 UTC, momocus commented on spec/models/sake_spec.rb
> +      stub_const("#{described_class}::OPENED_NEW_LIMIT", 7.days)
Fixed at 6a4482814f5a6841e284b314b2d84af9dfe4ff4f

2022-02-03 16:57 UTC, momocus commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
「それっぽい数値」の仕様を言語化して

2022-02-03 16:58 UTC, momocus commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
たしかに
貰いもんの酒とかありうるしね

2022-02-03 17:10 UTC, momocus commented on app/helpers/sakes_helper.rb
> +    selling_price.to_s + t("activerecord.attributes.sake.price_unit")
showでも使ってるしあとでやろう。  -> #396

2022-02-05 17:46 UTC, momocus commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
Fixed at 5006ced94944cdbdc5e764fb01c31fb8673bf902

2022-02-05 17:47 UTC, momocus commented on spec/models/sake_spec.rb
> +      it { expect(sake.selling_price).to eq(470) }
Fixed at 1de30c2fa36b5fff920cdc7263824fffceb9fc2d

2022-02-05 17:48 UTC, momocus commented on app/views/sakes/drink_menu.html.erb
> +      <%= link_to(sake.name.to_s, sake_path(sake.id),
Fixed at 3f61a1729de6b760f8761d90c08ca43a6e8e9b4f

2022-02-05 17:48 UTC, momocus commented on app/views/sakes/drink_menu.html.erb
> +                  { class: "text-decoration-none text-dark name-link" }) %>
Fixed at 3f61a1729de6b760f8761d90c08ca43a6e8e9b4f

2022-02-05 18:14 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +        expect(price_tag(1234)).to eq("1234円")
Fixed at 10147ba832461ef3b38ac23b9bc1e834a0df942e

2022-02-05 18:14 UTC, yonta commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
例えば80円揃いの値段。
他には100円単位。

現状の値段は450とか430とか600とかバラバラで細かすぎて、よいと思わない。

2022-02-05 18:14 UTC, momocus commented on app/helpers/sakes_helper.rb
> +    selling_price.to_s + t("activerecord.attributes.sake.price_unit")
Fixed at 10147ba832461ef3b38ac23b9bc1e834a0df942e

2022-02-05 18:17 UTC, momocus commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
Fixed at 5006ced94944cdbdc5e764fb01c31fb8673bf902

2022-02-08 11:07 UTC, momocus commented on app/views/sakes/drink_menu.html.erb
> +    <div class="col-auto" style="max-width: 60%;">
モバイル表示のデザインをちゃんと考えます！　Bootstrap公式が「モバイルを第一に」って言ってるの、無視しちゃってたわ 😢 
コミット増えてきたので、次のプルリクでやります。

2022-02-08 11:17 UTC, momocus commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
ホームパーティー時のお品書きなら計算しやすさのために100円単位がいいかもね。
居酒屋なら、価格を安く見せる目的で80円に揃えたいかも。

今んとこホームパーティーで使うのが一番の目的だから、100円単位にします。

2022-02-08 15:57 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +      # 利率を1.5にしてテスト
Fixed at 4541f1a785798a29b6c64492de63e76f12a943d9

2022-02-08 15:57 UTC, momocus commented on app/models/sake.rb
> +    (price.to_f / size * 180 * INTEREST_RATE).ceil(-1).to_i
Updated at 4541f1a785798a29b6c64492de63e76f12a943d9

2022-02-08 16:24 UTC, yonta commented
コード感覚取り戻していこ

2022-02-08 16:27 UTC, yonta approved these changes
コード感覚取り戻していこ

2022-02-08 16:27 UTC, merged