味香りグラフのリセットを今までの別ボタンを止め既存点をクリックに変えた'
momocus/sakazuki pull request #388
Opened 2022-01-31 15:58 UTC by yonta

ださいリセットボタンとおさらば、ratingとの統一感をとるぞ！

## やったこと

- 味香りグラフのリセットボタンを削除した
- 既存点クリックを味香りグラフのリセットにした
- こっそり味香りグラフのバグ修正
  - 動作は問題なかった
- ESLintの設定を変え、TSの`_variable_name`の未使用を許可した
  - 今まで設定済みと勘違いしていた

2022-02-03 14:52 UTC, momocus requested changes

2022-02-03 14:52 UTC, momocus commented on app/packs/src/typescript/taste_graph.ts
> +  private data: GraphP
データ変換前後の型が同じで、何も変換されていないように見える。
domのグラフポイント型とDBに保管するようのグラフポイント型を分けた方がいい。
ってよんたさんが言ってました。

2022-02-08 12:04 UTC, yonta commented on app/packs/src/typescript/taste_graph.ts
> +  private data: GraphP
やりました。
commit e8727ab25734c5d5fd7d5a0a1742fe6700e66bce

2022-02-08 17:04 UTC, momocus requested changes
すばらしい。型が分けられてコードがかなり分かりやすくなった。
aromaのtypoだけ修正してください。

2022-02-08 17:04 UTC, momocus commented on app/packs/src/typescript/input_taste_graph.ts
> +  const y = isNaN(data.arroma) ? "" : data.arroma.toString()
x arroma
o aroma

2022-02-09 08:17 UTC, yonta commented on app/packs/src/typescript/input_taste_graph.ts
> +  const y = isNaN(data.arroma) ? "" : data.arroma.toString()
そうではないですね。

今までは`GraphP`という`{x: number, y: number} | null`という型を使っていた。
`number`型の値には`NaN`が含まれるけど、運用で`NaN`が入らないようにしいた。
けど型上はありうる値として、`NaN`チェックと`null`チェックの両方が必要だった。

けどグラフには`null`が必要だけど、DOMの値を表すのに`null`はいらない。
のでこのコミットでDOMの値には新たな`DomValues`という型を割り当てた。
これは`{taste: number, aroma: number}`という型で、`NaN`を使っていいことにした。
なので`NaN`をそのまま値として使っていいため、`NaN`チェックが減ったの。

2022-02-09 08:18 UTC, yonta commented on app/packs/src/typescript/taste_graph.ts
> +    : { taste: NaN, arroma: NaN }
🤝

2022-02-09 08:18 UTC, yonta commented on app/packs/src/typescript/input_taste_graph.ts
> +  const y = isNaN(data.arroma) ? "" : data.arroma.toString()
ｳﾜｱｱｱｱｱｱｱｱｱｱｱｱｱ

2022-02-09 08:42 UTC, yonta commented on app/packs/src/typescript/input_taste_graph.ts
> +  const y = isNaN(data.arroma) ? "" : data.arroma.toString()
commit 6d284e863bf328a299b76f2daa727a95f8d8d8a6 対応

2022-02-12 08:54 UTC, momocus approved these changes

2022-02-12 08:54 UTC, momocus commented on app/packs/src/typescript/input_taste_graph.ts
> +  const y = isNaN(data.arroma) ? "" : data.arroma.toString()
oh

2022-02-12 08:54 UTC, merged