酒showデザイン変更に伴いRSpecのテストを修正した
momocus/sakazuki pull request #404
Opened 2022-02-11 10:16 UTC by yonta

## このPRは？

ブランチの途中報告。
new-designのRSpecが落ちてたのを修正したよ。

## 何をしたのか概要

- 落ちたテストを修正
  - 酒showのviewスペック
  - 酒の日付に関するテスト

## 酒showのviewスペックで変更した点

- 酒の日付の表示
- 酒ratingのスター表示

## 酒の日付に関するテスト

1. 酒showのviewスペックと重複したテストを削除
2. 酒の日付に関する仕様を考え直し、テストを変更
  - 酒の瓶状態を変更したときに、購入・開封・空の日付がどう変化すべき・変化しないべきか、を記述した。 

## 今後の予定

- 酒showのデザインをリファクタ
  - スタイルシート化してクラスをスッキリさせる
- 酒showだけでmasterマージを目指す
  - 酒indexやフォームの変更は別Issue、別PRにしたほうがよさそう。

2022-02-12 09:48 UTC, momocus requested changes
今回の変更範囲じゃないとこへの指摘でごめんね

2022-02-12 09:48 UTC, momocus commented on app/views/sakes/_show_abstract.html.erb
>          <%= "#{time_ago_in_words(latest_at(@sake), include_seconds: true)}前に#{t(".#{@sake.bottle_level}")}" %>
見逃してたけど「前に」がべた書きなのよくない。

2022-02-12 09:52 UTC, momocus commented on spec/views/sakes/show.html.erb_spec.rb
> +    date_format = %r{\d{4}/\d{2}/\d{2}}
日本語じゃないと日付のフォーマットが変わると思うけど、テストはこれでいい？

2022-02-12 10:08 UTC, yonta commented on app/views/sakes/_show_abstract.html.erb
>          <%= "#{time_ago_in_words(latest_at(@sake), include_seconds: true)}前に#{t(".#{@sake.bottle_level}")}" %>
ほんとだ。

 commit db2ab399bca41f111908859780ace229261646eb で対応

2022-02-12 10:13 UTC, yonta commented on spec/views/sakes/show.html.erb_spec.rb
> +    date_format = %r{\d{4}/\d{2}/\d{2}}
天才かよ。
"2022/10/03"とか"2022-10-03"とか"03-10-2022"とか"03/10/2022"とかあるな。

2022-02-12 10:38 UTC, yonta commented on spec/views/sakes/show.html.erb_spec.rb
> +    date_format = %r{\d{4}/\d{2}/\d{2}}
commit 753ef335e524993b871c3e01d9d944528e227cb9 で対応

2022-02-14 07:08 UTC, momocus approved these changes
👍

2022-02-14 07:08 UTC, merged