BY不明の酒を編集してもちゃんとBY不明のままにした
momocus/sakazuki pull request #410
Opened 2022-02-14 14:15 UTC by yonta

fix #403

見つからないPR 403

## やったこと

- 酒formの瓶詰め日、BYをRSpecで記述した
- BYを勝手に変えるバグを修正した
  - BYはnil値を許可するため、nilのとき新規酒なのかnil BYの酒なのか判定を間違えていた
- 日本元号つきselect関数を大幅にリファクタした
  - これからは普通のformのようにclassやdata-testidを付加できるぞ！

2022-02-15 05:54 UTC, momocus requested changes

2022-02-15 05:54 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  def select_year_with_japanese_era(latest_year:, selected: latest_year, include_nil: nil, **args)
このメソッドに対するspecはないの？

2022-02-15 05:54 UTC, momocus commented on spec/system/sake_form_date_select_spec.rb
> +    end
"when new sake before 7/1"と"when new sake after 7/1"について。
7/1の前後でBYが違う値になることを期待しているんだけと思うけど、両方ともit "selects this BY"と書かれているから違いが分からない。

2022-02-15 05:54 UTC, momocus commented on app/controllers/sakes_controller.rb
> +    @sake.brew_year = to_by(Time.current)
BYに限らず、newの時にフィールドに入ってるデフォルト値についてとか、editの時に変な値で上書きされないかのテストっているんやろな……。

2022-02-15 05:54 UTC, momocus commented on spec/system/sake_form_date_select_spec.rb
> +  # HACK: sakes_helperのprivate methodであるwith_japanese_eraを使う
`with_japanese_era`メソッドはprivateだからテストしないって方針だっけ？　そしたらこのテストの中で`with_japanese_era`を呼び出すのはよくないんじゃない。

2022-02-15 06:27 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  START_YEAR_LIMIT = 30
？？？？
変える気がないから定数なんだが。
変えるほうが変数。

2022-02-15 06:28 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def select_year_with_japanese_era(latest_year:, selected: latest_year, include_nil: nil, **args)
ないね。
selectを生成するけど、どういうテストの書き方なんだろほい。

2022-02-15 06:31 UTC, yonta commented on spec/system/sake_form_date_select_spec.rb
> +    end
たしかに

2022-02-15 06:33 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    @sake.brew_year = to_by(Time.current)
たしかに。

1. systemスペックでnew画面で想定したデフォルト値が入ってて他が空か。
2. systemスペックでnew画面・edit画面で書き換えて正しい値が入るか
3. systemスペックでnew画面で名前だけ入れてほぼ空データの酒が正しくできるか
4. systemスペックでedit画面開いて即更新して、何も変わらないか

あたりのテスト追加しないと怪しいよね。

つまり、現状の`def new`はレガシー

2022-02-15 06:39 UTC, yonta commented on spec/system/sake_form_date_select_spec.rb
> +  # HACK: sakes_helperのprivate methodであるwith_japanese_eraを使う
privateはテストしない。
privateをテストする必要があるなら方針がおかしいと思う。

`with_japanese_era`使ってるけど、これは悩みどころ。
固定フォーマットにするとi18nされてないよねー、eraのi18nってなんだ？はてという気持ち

`with_japanese_era`をprivateじゃなくしてテストを書くのもあり。
けど誰も使ってない関数をprivateじゃなくする価値は？という気持ち。

現状のようにHACKコメントをつけて使っておくくらいがバランスいいと思う。

2022-02-15 06:41 UTC, yonta commented on spec/system/sake_form_date_select_spec.rb
> +    end
commit 47e8b30bccddfbe0a0ee2aa9ccf561ddce9526c9

2022-02-15 07:00 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def select_year_with_japanese_era(latest_year:, selected: latest_year, include_nil: nil, **args)
生成されるタグは`ActiveSupport::SafeBuffer`というStringを拡張（？）しているクラス。
eq判定はできるけど、フォーマットされる可能性もあるし、文字列でのテストは避けたい。

systemスペックでselectの持つ内容をテストするとか？

2022-02-15 07:01 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    @sake.brew_year = to_by(Time.current)
今回は対応しない。
スペック追加はIssue立て始めると無限に立てれるから、他のときかなぁ。

2022-02-15 07:25 UTC, momocus commented on app/controllers/sakes_controller.rb
> +    @sake.brew_year = to_by(Time.current)
せやな

2022-02-15 07:31 UTC, momocus commented on spec/system/sake_form_date_select_spec.rb
> +  # HACK: sakes_helperのprivate methodであるwith_japanese_eraを使う
コードがi18n対応してないんだから、テストもi18n対応してなくて（固定フォーマットで）いいんじゃない。
コードをi18n対応したいというなら止めないが。

2022-02-15 07:31 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  START_YEAR_LIMIT = 30
ｿｳﾈ…

2022-02-15 07:46 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def select_year_with_japanese_era(latest_year:, selected: latest_year, include_nil: nil, **args)
commit c62e24845ccb03aef4eaa36a5006ada3cdafaf0e で対応した

2022-02-15 07:58 UTC, momocus commented on app/helpers/sakes_helper.rb
> +    options += [[include_nil, nil]] if include_nil
ArrayじゃなくてHashを使えるなら使おう。多分計算が速い。

2022-02-15 13:33 UTC, yonta commented on spec/system/sake_form_date_select_spec.rb
> +  # HACK: sakes_helperのprivate methodであるwith_japanese_eraを使う
方針変えたので`with_japanese_era`が公開関数になりました。
そのためテストも書きました。

2022-02-15 13:34 UTC, yonta commented on app/helpers/sakes_helper.rb
> +    options += [[include_nil, nil]] if include_nil
commit bd148505de1f7b67f604ccfaaf9ac24cb55e9b80
で対応したけど消した

2022-02-15 13:37 UTC, yonta commented
/fix

2022-02-15 14:09 UTC, yonta commented
コンフリクトするわ、わら。

2022-02-15 14:09 UTC, yonta commented
rebaseとらい！！！

2022-02-15 14:11 UTC, yonta commented
なんとかしたわ

2022-02-15 15:24 UTC, momocus approved these changes
おつおつ
あともうちょっと！

2022-02-15 15:24 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +      end
to_byのテストはあるから、ここのテストは要らない

2022-02-15 15:24 UTC, momocus commented on app/helpers/sakes_helper.rb
> +    this_by_year = to_by(Time.current).year
this_by_year って brewery year year でよくわからんと思ったけど、Dateクラスであるbrewery_yearからyearだけ抜き出してるのね。ほかにいい名前は思いつかないし、このままでもいいか。

2022-02-15 15:40 UTC, yonta commented on app/helpers/sakes_helper.rb
> +    this_by_year = to_by(Time.current).year
commit e7108f2e7090665af4a38fe58bec0bc09cfed7ae

2022-02-15 15:40 UTC, yonta commented on spec/helpers/sakes_helper_spec.rb
> +      end
commit 66f9c55beef5888e663be6f2ff664a44ac122280

2022-02-15 17:59 UTC, merged

2022-02-16 10:01 UTC, yonta commented
メモ：平成31年BYが消えた図。BY整理のため。

![image](https://user-images.githubusercontent.com/849256/154240985-8e1d1461-615e-48fd-887e-3e6f480803e3.png)