酒をコピーして新規作成する機能を追加
momocus/sakazuki pull request #420
Opened 2022-02-18 11:13 UTC by yonta

fix #200 

## 概要

酒showに「複製」ボタンをつけた
ここから内容をコピーしてつくれる！

酒の情報はコピーする。
ただし、レビューはすべてコピーされない。
また、瓶詰め・BYも違う可能性が高いのでコピーされない。

コピーされた項目には内容にinfo色がつくよ。

![image](https://user-images.githubusercontent.com/849256/154672429-07a40612-b94c-4daa-ae55-d1ee8252338b.png)

![image](https://user-images.githubusercontent.com/849256/154672631-602729eb-f699-4c7d-b0ed-bb16e28474ca.png)

## やったこと

- コピー機能のスペックを記述
- 酒DBを変更
- 酒コピー機能を追加
- 酒フォームのtestid形式を揃えた
  - 今まで命名規則がバラバラだった。
    - ハイフンだったりアンダーバーだったり、名前のつけかたもフォーム名が入ってたりなかったり
  - せめてフォーム内では`sake_[column_name]`で揃えた

## やってないこと

- コピー元リンクをshowに追加
  - いるかいらないか悩んでる

2022-02-25 11:31 UTC, momocus commented
コピー元リンクの表示は要らないんじゃないかなあ。ユースケースがわからん。
過去に買った同じ銘柄の酒がどうだったか確かめたいなら、まず酒の名前で検索すると思う。
酒を複数本買ったときは、別にコピー元が何とかはどうでもいい。

2022-02-25 11:33 UTC, momocus requested changes
レビュー遅くなってごめん＞＜

2022-02-25 11:33 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  def copy_sake_params(sake)
どのカラムをコピーして、どのカラムをコピーしないかの制御はViewじゃなくControllerの責務だと思う。

2022-02-25 11:33 UTC, momocus commented on app/controllers/sakes_controller.rb
> +    if params.dig(:sake, :copied_from)
どのカラムをコピーして、どのカラムをコピーしないかの制御はViewじゃなくControllerの責務だと思う。
newアクションを使いまわさず、copyアクションを追加したほうがいいんじゃないかな？
（viewを使いまわすのはいいと思う）

2022-02-26 05:12 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +    end
悩んだけどここがいい。

「コピーリンクがどこにあるか」はコピー機能の仕様とも酒showの仕様とも言える。
けど酒コピー機能としてひとくくりにまとめたほうが管理しやすいと思う。
酒showの仕様は酒の情報を表示するに特化させて、その上に乗っている追加機能と捉えた法が良い。

例えば仕様変更で酒indexにコピーリンクを置く、となったとき酒showに書いておくと変更が多いし見逃しそう。

2022-02-26 05:14 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +      click_link "copy_sake"
たしかに～

commit 2db69b0d8d75caa4292dd403be40d4e1ab9d290b

2022-02-26 05:15 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +  context "for copy value" do
あったほうわかりやすくない？
コピーされる値とされない値のテストって意味をつけておきたい。

2022-02-26 05:16 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +      end
いるか？
周りに揃えるか。

2022-02-26 05:16 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +      end
ratingは入力フォームないのでいらない

2022-02-26 05:19 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def copy_sake_params(sake)
controllerの責務は`new`で`params`を受け取るまでいいと思う。
どのカラムをコピーするかはコピー機能がどんな`param`与えるか。
コピー機能の責務。

2022-02-26 05:20 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    if params.dig(:sake, :copied_from)
アクション追加は重すぎるのでやらない。

仕様変更するわ。
むしろどれをコピーするしないとかせず、permitできるparamsをnewは受け取れるようにする。
その後、コピー機能ではparamsをレビュー以外全部にする。
そもそもinfoされるのもださかったのでやめて、メッセージに「レビューは複製されません」と追加する。

2022-02-26 06:26 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +      end
仕様変更で消えた

2022-02-26 06:26 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +      end
仕様変更でき得た

2022-02-26 06:27 UTC, yonta commented
仕様変更しました

2022-02-26 06:56 UTC, momocus commented on spec/system/copy_sakes_spec.rb
> +  context "for copy value" do
`describe "for copy value"` にしたらいいと思う。describe は入れ子になってもよかったはず。

2022-02-26 08:11 UTC, momocus reviewed
説明プリーズ

2022-02-26 08:11 UTC, momocus commented on spec/system/copy_sakes_spec.rb
> +    end
OK

2022-02-26 09:58 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def copy_sake_params(sake)
じゃあ`new`アクションで特定の`params`を監視して動作を変えるほうがいいってことかな？
それこそ`new`アクションの責務が大きくなりすぎて、copyに分けたほうがいい。

僕はわけないほうがいい。わけないならnewはなるべくシンプルで汎用的なほうがいい。
今回の変更はnewがparamsを受け付けるようにしたこと。
今までもupdateがparamsを受け付けていて、それに習ったAPIの変更。
APIがparamsで受け取るんだから、そのAPIを叩くためのparamsをリンクに仕込むのは何も問題ないと思うけど。

viewの責務というけど、それはMVCモデルでの話？
APIを叩くという想定で作ってるから、paramsをリンク経由で叩くのが自然で、viewのリンクでそれを実現するのがいいと思うけど。

2022-02-26 10:02 UTC, yonta commented on spec/system/copy_sakes_spec.rb
> +  context "for copy value" do
まじじゃん。天才～。

commit 3168c77fbc82a1cc3043ded2a3a0f196dcc238e7

2022-02-26 11:15 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def copy_sake_params(sake)
責務をContorollerに移すか

2022-02-26 11:15 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def copy_sake_params(sake)
何が正しいかわからん

2022-02-26 11:16 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def copy_sake_params(sake)
commit f5b57a5771c210fd4f37438e098bbc0c15a14d2e

2022-02-26 11:17 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def copy_sake_params(sake)
コピーボタンを押して、1回newのフォームページを挟む。
ので、copy/clone/dupのような新たなアクションを定義するのは違う気がする。
newアクションでなんとかするようにした。

2022-02-27 17:04 UTC, momocus requested changes

2022-02-27 17:57 UTC, momocus commented on app/controllers/sakes_controller.rb
> +  def default_value(sake)
default_valueメソッドがなくなったので解決

2022-02-27 17:57 UTC, momocus approved these changes

2022-02-27 17:58 UTC, merged