Rails 6.1.4にアップグレードした:rocket:
momocus/sakazuki pull request #422
Opened 2022-03-01 09:41 UTC by yonta

Rails7にあげるぞ！と思ったら、
なんと、我々はまだRails 6.1に到達していなかったのだ

## やったこと

- Gemfileとpackage.jsonの6.1.4.1を6.1.4.6に変更
- `rails app:update`コマンドを使ってRails6からRails6.1にアップデート
- Rubocopバージョンアップに従い新たなルールエラーを修正
  - `FactoryBot.`なんて今はいらなかった
- Rails6.1のデフォルト設定を使うようにした
  - formにおけるidが自動生成されなくなった
- Rails 6.1の新たなデフォルトで動かないものを修正
  - id生成されないので多くのTypeScriptが死んだ、がんばって復活させた
- 酒フォームにおける製造年月のRSpecを記述した
  - 先の変更でこっそり死んでいた
  - これからはRSpecで死んだのを検知できる

## やってないこと

- rating機能、グラフ機能のRSpecの記述
  - これも先の変更でこっそり死んでいた
  - JavaScriptのオブジェクトをクリックするテストがRSpecでかけるかわからない
  - たぶんCapybaraにはCanvasしか認識できず、Canvasのどの位置は指定できない気がする
  - Jestなどフロントエンド用テストフレームワークがいる気がしている

2022-03-01 09:42 UTC, yonta commented
/fix

2022-03-01 10:47 UTC, iteduki commented
`config/locales/en.yml`が生成されていますがこれってないといけないんでしたっけ？
不要なら消してよさそうです

2022-03-05 07:13 UTC, yonta commented
現在、ratingとgraphのテストないけど、以下の方法＋テストブラウザのサイズ指定でできるかもしれない。

https://stackoverflow.com/questions/21051216/using-rspec-capybara-selenium-to-interact-with-a-canvas-element

2022-03-05 10:01 UTC, momocus commented on db/schema.rb
> +  create_table "active_storage_attachments", force: :cascade do |t|
我々が今まで使っていたのは何だったんだ……

2022-03-05 10:52 UTC, momocus requested changes
rails app:update だと……！？　そんなコマンドがあったのか

2022-03-05 10:52 UTC, momocus commented on db/migrate/20220228150000_create_active_storage_tables.active_storage.rb
> +# This migration comes from active_storage (originally 20170806125915)
今はActive Storage使ってないから、このMigrateionは要らないんじゃないかな。
ルーティングも消しときたいから、application.rbにあるrequire（Active StorageとAction Text ）も消した方がいいかも。

参考: 
https://qiita.com/k_teluki/items/c9674499e51dd83f97f5#comment-1bab8d43669ccde652c6
https://techracho.bpsinc.jp/hachi8833/2021_03_24/104708

2022-03-05 10:52 UTC, momocus commented on db/migrate/20220228154415_add_service_name_to_active_storage_blobs.active_storage.rb
> +class AddServiceNameToActiveStorageBlobs < ActiveRecord::Migration[6.0]
同上。はActive Storage使ってないから、このMigrateionは要らないと思う。

2022-03-05 10:52 UTC, momocus commented on spec/system/sake_form_bindume_date_spec.rb
> +RSpec.describe "SakeFormBindumeDate", type: :system do
ちゃんとテスト追加して偉い

2022-03-05 13:13 UTC, momocus commented
Active StorageをオフにするのはRailsのUpdateとは別問題だし、ここでは対応しなくていいや。
rails app:updateが使えなくなるかもだし。
さておきmasterとのコンフリクトが発生しているから解消して。

2022-03-05 16:40 UTC, yonta commented on spec/system/sake_form_bindume_date_spec.rb
> +RSpec.describe "SakeFormBindumeDate", type: :system do
どや

2022-03-05 16:42 UTC, yonta commented on db/migrate/20220228150000_create_active_storage_tables.active_storage.rb
> +# This migration comes from active_storage (originally 20170806125915)
commit 48366235a743a0187602e385328b42665f004887

2022-03-05 16:42 UTC, yonta commented on db/migrate/20220228154415_add_service_name_to_active_storage_blobs.active_storage.rb
> +class AddServiceNameToActiveStorageBlobs < ActiveRecord::Migration[6.0]
commit 48366235a743a0187602e385328b42665f004887

2022-03-05 16:50 UTC, yonta commented
/fix

2022-03-07 07:42 UTC, momocus approved these changes
👍 👍 👍 👍 👍 👍 👍 👍

2022-03-07 07:42 UTC, merged