お品書きデザイン一新
momocus/sakazuki pull request #426
Opened 2022-03-05 12:48 UTC by momocus

↓こういう感じにした
https://github.com/momocus/sakazuki/wiki/%E3%81%8A%E5%93%81%E6%9B%B8%E3%81%8D

2022-03-05 17:47 UTC, yonta requested changes
右揃え

2022-03-05 17:47 UTC, yonta commented on config/locales/views/sake.ja.yml
> +      price_per_go: 一合当たりのお値段となり〼
```suggestion
      price_is_per_go: 一合当たりのお値段となり〼
```

2022-03-05 17:47 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +  <%= t(".price_per_go") %>
```suggestion
  <%= t(".price_is_per_go") %>
```

2022-03-05 17:47 UTC, yonta commented on app/views/sakes/_one_drink.html.erb
> +<div class="col-12 col-lg-6 d-flex gy-5">
gutterはcolではなくrowにつけるものだと思う

2022-03-05 17:47 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +      <%= render("one_drink", sake: sake1) %>
パーシャルビューが増えてきて対応がわかりづらくなってきた。
one_drinkだとどのビューのパーシャルかわからなくなりそう。
drink_menuのパーシャルとわかる名前にしてほしい。

2022-03-05 17:47 UTC, yonta commented on app/views/sakes/_one_drink.html.erb
> +        <div class="col-3 col-lg-2 text-end text-nowrap price_tag_border">
値段がはみ出ちゃう。
値段がはみ出る場合は右揃えにならない。
mobile版も同じ。

![image](https://user-images.githubusercontent.com/849256/156894189-4ef4d670-a90f-4f64-9a6c-d939d8d90ae7.png)

2022-03-05 17:47 UTC, yonta commented on app/views/sakes/drink_menu.html.erb
> +      <%= render("one_drink", sake: sake1) %>
sakesのリソース内だし、drink_menuもただのmenuでいい気がしてきた。
sakazuki.herok.com/menuだとやりすぎだけど、sakazuki.heroku.com/sakes/menuなら全然問題ないと思う。

そうするとパーシャルは_menu_one_drink.html.erbとか。

2022-03-07 07:48 UTC, momocus commented
間違えて一回branch消しちゃってrepopenした

2022-03-07 12:08 UTC, momocus commented on app/views/sakes/drink_menu.html.erb
> +      <%= render("one_drink", sake: sake1) %>
fixed at d838d05

2022-03-07 12:09 UTC, momocus commented on app/views/sakes/_one_drink.html.erb
> +<div class="col-12 col-lg-6 d-flex gy-5">
fixed at f45e578

2022-03-07 12:10 UTC, momocus commented on app/views/sakes/drink_menu.html.erb
> +  <%= t(".price_per_go") %>
fixed at  49d2aa9

2022-03-07 12:10 UTC, momocus commented on config/locales/views/sake.ja.yml
> +      price_per_go: 一合当たりのお値段となり〼
fixed at  49d2aa9

2022-03-07 12:11 UTC, momocus commented on app/views/sakes/_one_drink.html.erb
> +        <div class="col-3 col-lg-2 text-end text-nowrap price_tag_border">
fixed at 3609c04

2022-03-08 09:34 UTC, yonta commented on app/views/sakes/_one_drink.html.erb
> +        <div class="col-3 col-lg-2 text-end text-nowrap price_tag_border">
今って全部lgのみを判定に使っているけど、mdでおｋ？
タブレットのような中くらいの端末で2列表示するってことだよね。

2022-03-08 09:41 UTC, yonta approved these changes

2022-03-09 11:03 UTC, momocus commented on app/views/sakes/_one_drink.html.erb
> +        <div class="col-3 col-lg-2 text-end text-nowrap price_tag_border">
おｋ
タブレットくらいの幅があったら2列表示したほうがオサレ

2022-03-09 15:18 UTC, merged