酒の名前から蔵名補完を試みる機能をいれた
momocus/sakazuki pull request #433
Opened 2022-03-12 08:13 UTC by yonta

- Fix: SAKETIMESで休業中表記があるので消去処理をいれた
- Update: get_sakagura.rb/export_sakagura.rbを実行した
- Update: SAKETIMESから蔵データを取得するとき、代表銘柄も取得するようにした
- Update: 酒蔵名オートコンプリートリスト生成スクリプトを新しい蔵データリストに対応させた
- Fix: 複数の代表銘柄への対応ミスを修正
- Add: 銘柄から蔵名を補完するための銘柄リストを出力するスクリプトを追加
- Update: 酒の名前から銘柄を補完する機能を追加
- Add: SAKETIMESに載っていない銘柄を追加した
- Refactor: 蔵・酒米取得スクリプトに出力メッセージを追加した
- Refactor: Pure RubyがRailsのRubocopに怒られる箇所をdisableした
- Add: 酒の名前から銘柄によって蔵名を補完するRSpecを書いた

2022-03-14 15:25 UTC, momocus requested changes
修羅の道やね

2022-03-14 15:25 UTC, momocus commented on cli-scripts/get_kura.rb
> +  doc.map { |a| a_to_region(a) }
a_to_regionメソッド、こんくらいなら分けなくてもいいんじゃない？
```suggestion
  doc.map { |a| 
    {
      url: a_tag.attributes["href"].value,  # "北海道（13）"のようになっているので、括弧と数字を削る
      region: a_tag.content.sub(/\uff08.*\uff09/, "")
    }
   }
```

2022-03-14 15:25 UTC, momocus commented on cli-scripts/get_kura.rb
> +  meigaras = add_meigara(kura, region, meigaras)
kuraとmeigaraに何度も代入しているのがもやっとする。けどこれは私の趣味ってだけだから対応しなくてもいいや。

2022-03-14 15:25 UTC, momocus commented on cli-scripts/get_kura.rb
> +  }
appendするならmapメソッド方が簡単に書けるんじゃない？（試してない）
```suggestion
  trs.map { |tr|
    tr_to_data(tr, region)
  }
```

2022-03-14 15:25 UTC, momocus commented on cli-scripts/get_kura.rb
> +def add_meigara(kura, region, meigaras)
まじかーこれ今後ずっとメンテしていくのか。しんどくない？ほしい気持ちはわかるけども
saketimesにこれらの銘柄が追加されたらリストには重複して乗ることになるのか。重複する分には問題ないか？
ｳﾜｰ不安。

2022-03-14 15:25 UTC, momocus commented on cli-scripts/get_kura.rb
> +  in ["盛田金しゃちl酒造株式会社", "愛知県"]
typo?
```suggestion
  in ["盛田金しゃち酒造株式会社", "愛知県"]
```

2022-03-15 04:11 UTC, yonta commented on cli-scripts/get_kura.rb
> +  name.sub(/　+$/, "")
かっこいい！

2022-03-15 04:12 UTC, yonta commented on cli-scripts/get_kura.rb
> +#                       url: "https://jp.sake-times.com/sakagura/./hokkaido"},
カレントパスを表すドット。
その前に取得するリンクが`./hokkaido`のようにドット付きなの。
取らずに動くからそのまま使ってる。

2022-03-15 04:13 UTC, yonta commented on cli-scripts/get_kura.rb
> +  datas = request_all_kuras(regions)
datasはdataのArrayのようにdataの集合を表す意味で存在は許していいと思う。
xとxsのような関係。
とはいえ意味がなかったから名前は変えよう。

2022-03-15 04:13 UTC, yonta commented on cli-scripts/get_kura.rb
> +  doc.map { |a| a_to_region(a) }
`map`内に書くと以外にわかりにくかった。
なるべく名前つけて別にするほうがよかった。

2022-03-15 04:13 UTC, yonta commented on cli-scripts/get_kura.rb
> +  meigaras = add_meigara(kura, region, meigaras)
これも別にしよう。

2022-03-15 04:14 UTC, yonta commented on cli-scripts/get_kura.rb
> +  }
ほんとだ。
ここは古いスクリプトのままだからね。

2022-03-15 04:17 UTC, yonta commented on cli-scripts/get_kura.rb
> +def add_meigara(kura, region, meigaras)
必要。
これは他サイトにもない強み情報になる。

ただ、この形式でメンテしていく気はない。
まずは知っている蔵とかよく使いそうな蔵である愛知県と宮城県を追加した。
本気で全国やるなら、酒造組合とかのページからとってくる。
ただ全国統一のサイトはないから、各地方ごとにスクリプト書かないといけないのが大変。
あと酒造組合のページにも代表銘柄は無かったりすることも。
結局どこかでこういう手書きしないといけない気もする。

宮城県酒造組合の蔵元一覧ページ
https://miyagisake.jp/kuramoto/
愛知県酒造組合の蔵元紹介ページ
http://www.aichi-sake.or.jp/01-01_kuramoto-nagoya.html

2022-03-15 04:17 UTC, yonta commented on cli-scripts/get_kura.rb
> +  in ["盛田金しゃちl酒造株式会社", "愛知県"]
typo

2022-03-15 08:24 UTC, yonta commented on cli-scripts/get_kura.rb
> +  datas = request_all_kuras(regions)
いや、すでにkuraはあるのよ。
kura、meigara、regionをあわせたやつをdataって呼んでる。
なんか名前付けないといけない

2022-03-15 08:42 UTC, yonta commented on cli-scripts/get_kura.rb
> +  doc.map { |a| a_to_region(a) }
`tr_to_HOGE`にしているし、ここも別名つけといたほうが統一がとれてよい

2022-03-15 10:14 UTC, yonta commented on cli-scripts/get_kura.rb
> +  datas = request_all_kuras(regions)
すでにあるkuraをnameにして、name,meigara,regionを持つhashをkuraにしよう

2022-03-15 10:26 UTC, yonta commented on cli-scripts/get_kura.rb
> +  datas = request_all_kuras(regions)
commit f6403d318cac9e25f9d9819bade62a12e2ec1429

2022-03-15 10:26 UTC, yonta commented on cli-scripts/get_kura.rb
> +  datas = add_data!(datas)
commit f6403d318cac9e25f9d9819bade62a12e2ec1429

2022-03-19 09:46 UTC, momocus commented on cli-scripts/get_kura.rb
> +  doc.map { |a| a_to_region(a) }
ok

2022-03-19 09:53 UTC, momocus approved these changes
乙〜

2022-03-19 09:53 UTC, momocus commented
@yonta コンフリクトを解消して

2022-03-19 12:46 UTC, merged