Update: Twitter Cardででかい画像にした
momocus/sakazuki pull request #445
Opened 2022-03-16 14:24 UTC by yonta

バエル。

2022-03-21 09:22 UTC, momocus requested changes

2022-03-21 09:22 UTC, momocus commented on app/views/sakes/show.html.erb
> +  <% set_meta_tags(og: { image: { _: @sake.photos.first.image.large_twitter_card.url, width: 600, height: 600 } }) %>
height: 300じゃあないの？
```suggestion
  <% set_meta_tags(og: { image: { _: @sake.photos.first.image.large_twitter_card.url, width: 600, height: 300 } }) %>
```

2022-03-21 09:28 UTC, yonta commented on app/views/sakes/show.html.erb
> +  <% set_meta_tags(og: { image: { _: @sake.photos.first.image.large_twitter_card.url, width: 600, height: 600 } }) %>
ほんとだ！

2022-03-22 03:34 UTC, yonta commented on app/views/sakes/show.html.erb
> +  <% set_meta_tags(og: { image: { _: @sake.photos.first.image.large_twitter_card.url, width: 600, height: 600 } }) %>
commit 4b6fd210ec42afa625eb9da705a4ac5cf587e336

2022-03-23 10:05 UTC, merged