酒フォームにてフラッシュメッセージでなくフォーム直下にエラー内容を表示するようにした
momocus/sakazuki pull request #464
Opened 2022-04-10 09:08 UTC by yonta

- Update: HTML5のinput required属性を使って酒フォームの入力必須値を設定した
- Update: 入力フォームエラーが起きたときにBootstrapのクラスを追加するようにした
- Update: 酒フォームで入力値エラーがあったときはエラー箇所にメッセージが出るようにした

2022-04-11 17:49 UTC, momocus requested changes
すっごく使いやすくなったね👏

2022-04-11 17:49 UTC, momocus commented on spec/system/sake_form_validation_spec.rb
> +        expect(find(:test_id, "sake_alcohol").first(:xpath, "..")).to have_css(".is-invalid")
sake_alcoholの親要素を指定するのか。なるほど。

2022-04-12 10:53 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +  # describe "name" do
忘れてた。
これはブラウザ機能だからテストできないのよね。
リンク遷移しないとかのテスト追加しとこ。

2022-04-12 10:53 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +    context "with minus value" do
ﾅ､ﾅﾝﾀﾞｯﾃｰ!

2022-04-12 10:53 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +      it "is with error message" do
特にない。
it hasでかくか。

2022-04-12 10:54 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +        expect(find(:test_id, "sake_alcohol").first(:xpath, "..")).to have_css(".is-invalid")
そうそう。
capybaraのテストは`expect(page).to`でページ内をざっくり検索するつもりのマッチャのようで。
`find`で見つけた要素そのものがcss持ってるってマッチャが書けない。
なんで`xpath`で親要素を指定している。

2022-04-12 11:07 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +    context "with minus value" do
commit 63c063c36e9bec8a522aed8c5de8dee894f05dfa

2022-04-12 11:09 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +      it "is with error message" do
describe先の酒アルコール度数フォームの隣にエラーメッセージがあるの意だわ。
pageが持っているという意味ならhas。難しい。

2022-04-12 11:18 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +      it "is with error message" do
どっちの意でもhasで代表できるからhasで書くか

2022-04-12 11:19 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +      it "is with error message" do
commit c913df4bf3ee98759e7a23a2eb932609b9864606

2022-04-12 11:20 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +  # describe "name" do
commit aca64fc664248d4781e954967140cb92d7297628

2022-04-12 11:22 UTC, yonta commented on spec/system/sake_form_validation_spec.rb
> +    context "with minus value" do
commit 97d3df30f15203e91145b176f579f06cd3761aa9

2022-04-16 08:33 UTC, momocus approved these changes
💯

2022-04-16 08:33 UTC, merged