酒indexのデザインを新しくした！
momocus/sakazuki pull request #471
Opened 2022-04-16 06:02 UTC by yonta

after #469
fix #405

ついに新たな酒indexとなったぞ！

## やったこと

- 酒indexを新たなデザインにした
- 各種RSpecを修正した
  - 構造が大きく変わったので、testidの振り方を修正
  - 変更箇所のみリファクタ

2022-04-20 12:02 UTC, momocus requested changes
おしゃれ！

2022-04-20 14:32 UTC, yonta commented on app/views/sakes/index.html.erb
> +                  <%= link_to(sake.name, sake_path(sake)) %>
commit 4f7f3f4d73aa8b8d2b75046a7f59d9556286202e

2022-04-20 14:32 UTC, yonta commented on app/views/sakes/index.html.erb
> +                  <%= link_to(sake.name, sake_path(sake)) %>
あんまリンクの下線消しすぎるのはよくない。
アクセシビリティ的に、リンクっぽいと感じるスタイルをいじるのはよくない。

2022-04-20 14:34 UTC, yonta commented on app/views/sakes/_drink-button.html.erb
> +    <%= link_to(tag.i(class: "bi-droplet-half", style: "font-size: 0.95em") + t(".open"),
縦に並べてても前と同様にアイコンで微妙にサイズが違うく感じるのでそのまま導入している。
それよりもセミコロン抜けてるわ。

2022-04-20 14:35 UTC, yonta commented on app/views/sakes/_drink-button.html.erb
>      <%= link_to(tag.i(class: "bi-droplet", style: "font-size: 0.95em;") + t(".empty"),
同上

2022-04-20 14:35 UTC, yonta commented on app/views/sakes/_drink-button.html.erb
>      <%= link_to(tag.i(class: "bi-cup-fill", style: "font-size: 1em;") + t(".impress"),
同上

2022-04-20 14:36 UTC, yonta commented on app/views/sakes/index.html.erb
> +                      <i class="bi-three-dots-vertical fs-5"></i>
もっと押せる感出したいのは確かだわ。

2022-04-20 14:36 UTC, yonta commented on app/views/sakes/index.html.erb
> +                  <%= link_to(sake.name, sake_path(sake)) %>
例えば古いindexでは「編集」のとこが押せるのが一瞬でわかる

![image](https://user-images.githubusercontent.com/849256/164255519-d4f7c6e0-a864-4d2e-a89e-dff2c3183a05.png)

2022-04-20 14:52 UTC, yonta commented on app/views/sakes/index.html.erb
> +                      <i class="bi-three-dots-vertical fs-5"></i>
commit 059e8c684c018ceac4dad5be1f352588ce8575a8

やってみた。

2022-04-20 15:18 UTC, yonta commented
ここ揃ってないんだけど、Cardでいい感じに揃える方法がわからん～～～～

![image](https://user-images.githubusercontent.com/849256/164264760-9c7cdbf7-c672-49bd-8816-d43b90a8f6a8.png)

2022-04-20 15:26 UTC, yonta commented
どこ揃えにしても空白が目立つな・・・

![image](https://user-images.githubusercontent.com/849256/164266387-698d2e29-af78-4778-aefd-97e56d0f4350.png)

![image](https://user-images.githubusercontent.com/849256/164266467-ec680ffe-54da-4b56-bc57-cf7aba80ebd6.png)

2022-04-20 15:27 UTC, yonta commented
やっぱ下に揃えよう

2022-04-20 18:56 UTC, yonta commented on app/views/sakes/index.html.erb
> +                  <%= link_to(sake.name, sake_path(sake)) %>
色は変えたまま。
押せる感がゼロになる。

2022-04-20 18:56 UTC, yonta commented on app/views/sakes/index.html.erb
> +                      <i class="bi-three-dots-vertical fs-5"></i>
思ったよりダサいな。
戻したい。

2022-04-20 18:57 UTC, yonta commented on app/views/sakes/index.html.erb
> +                  <%= link_to(sake.name, sake_path(sake)) %>
デザインはカッコイイためにあるんじゃなく、使いやすいためにあるもの。

2022-04-20 18:58 UTC, yonta commented
これ、新しくなったのでますますsort機能いらないな。
実際使ってないし。

2022-04-21 07:24 UTC, momocus commented on app/views/sakes/index.html.erb
> +                      <i class="bi-three-dots-vertical fs-5"></i>
戻そう

2022-04-21 07:31 UTC, yonta commented on app/views/sakes/index.html.erb
> +                      <i class="bi-three-dots-vertical fs-5"></i>
commit db47eb414f8e4e3f528fefdbde5eba8deb072206 でリバーと

2022-04-21 07:31 UTC, momocus requested changes

2022-04-21 07:31 UTC, momocus commented on app/views/sakes/index.html.erb
> +                      <i class="bi-three-dots-vertical fs-5 text-primary"></i>
戻そう

2022-04-21 07:32 UTC, momocus approved these changes

2022-04-21 07:36 UTC, merged