酒の製造年月でのダミー入力フォームを使うのをやめた
momocus/sakazuki pull request #473
Opened 2022-04-17 08:31 UTC by yonta

- Remove: dummyの製造年月日をやめた
- Fix: 酒の製造年月フォームのID変更に対応した
- Refactor: 酒の更新日時のSpecの名前を変更した
- Refactor: 酒の瓶状態時間のSpecの場合分けを見直した
- Update: 製造日時とBYのSpecを分離した

2022-04-17 18:38 UTC, momocus requested changes
ダミー入力フォーム、なくせたのか

2022-04-18 14:02 UTC, yonta commented on spec/system/sake_form_bindume_date_spec.rb
> +    context "when creating new sake with current time" do
registerだと新規登録なのか更新なのか分かりづらいのでcreatingのまんまで。
sake whoes bindume year is this yearとかにしとこ

2022-04-18 14:03 UTC, yonta commented on spec/system/sake_form_bindume_date_spec.rb
> +  describe "year of bindume_date" do
まとめるべきでない。

1. systemテストであり、見えているフォームの機能をテストしている。内部の酒のデータ構造を染み出させるべきではない。
2. 年と月でテストしたい境界条件が違う。年は現在と過去くらいだが、月は年と違ってループするため1月と12月という特定月にしている。

2022-04-18 14:03 UTC, yonta commented on spec/system/sake_form_bindume_date_spec.rb
> +    context "when creating new sake with past time" do
creating sakeでいいね。

2022-04-18 14:03 UTC, yonta commented on spec/system/sake_form_brew_year_spec.rb
> +    context "when visiting new sake page on or after 7/1" do
いえーい

2022-04-18 14:08 UTC, yonta commented on spec/system/sake_form_bindume_date_spec.rb
> +    context "when creating new sake with current time" do
commit c64d25ccc9ec18537e70a8a38f08525c6a31f3e3

2022-04-18 14:09 UTC, yonta commented on spec/system/sake_form_bindume_date_spec.rb
> +    context "when creating new sake with past time" do
commit c64d25ccc9ec18537e70a8a38f08525c6a31f3e3

2022-04-18 16:45 UTC, momocus commented on spec/system/sake_form_bindume_date_spec.rb
> +  describe "year of bindume_date" do
> 1. systemテストであり、見えているフォームの機能をテストしている。内部の酒のデータ構造を染み出させるべきではない。

見えているフォームに入力した値が、DBに期待通り登録されたかのテストじゃないの？
テスト対象(expect)はsake.bindume_date.monthなんだし。

> 2. 年と月でテストしたい境界条件が違う。年は現在と過去くらいだが、月は年と違ってループするため1月と12月という特定月にしている。

境界値のテストだったのか……（テストケースが一個だけだと、もし製造年月がテストケースに書いてるのと同じ固定値になっていた場合にテストをパスしてしまうから、適当に値を変えた2つテストをしているんだと思ってた）。
ここで境界値をテストする目的は？

2022-04-18 16:53 UTC, momocus commented on spec/system/sake_form_bindume_date_spec.rb
> +  describe "year of bindume_date" do
フォームに主眼を置いてテストケース作ってるってことで了解した。

2022-04-18 16:54 UTC, merged