お品書きをmasterへマージ
momocus/sakazuki pull request #474
Opened 2022-04-17 19:03 UTC by momocus

お品書きをmasterにマージするため、以下の三つをやりました。
- いったんmasterをお品書きにマージ(a71ed4221016846624d8206f48ed1613831cb0b9)
- コンフリクトを解消(1f6c4907e6aa90efe610c9f8c79411d508e53778)
-  linterに怒られたところを修正(47a9a64b0f44c784f62bfcde6a5668f9e85fb4a1)

a71ed4221016846624d8206f48ed1613831cb0b9 ではあえてコンフリクトを解消せずにそのままマージして、次のコミットでコンフリクトを解消しました。どういう風にコンフリクトを解消したかが分かりやすくていいかもという試みです。

2022-04-18 14:52 UTC, yonta requested changes
必須は、空のエントリーポイントの削除ですね

2022-04-18 14:52 UTC, yonta commented on app/controllers/sakes_controller.rb
> +                          s: "id desc").result(distinct: true)
`distinct: true`いらなくない？
付ける必要がある場合が思いつかない

2022-04-18 14:52 UTC, yonta commented on app/javascript/sakes_menu.js
> +// empty entry point
esbuildでは空のエントリーポイントは消して。
JSのpac tagの呼び出し元で`sake_menu`を呼ばないで。

2022-04-18 14:52 UTC, yonta commented on spec/helpers/sakes_helper_spec.rb
> +    context "if the argument is nil" do
```suggestion
    context "with nil argument" do
```

2022-04-18 14:52 UTC, yonta commented on spec/helpers/sakes_helper_spec.rb
> +    context "if the argument is integer" do
```suggestion
    context "with some integer argument" do
```

2022-04-18 14:52 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(sealed_old_sake.new_arrival?).to be(false)
contextの内容はcontext直下に書くとわかりやすいと思う。
例えば以下のように

```ruby
      let(:sake) { create(:sake, bottle_level: "sealed", created_at: Time.zone.parse("2022-01-01 10:30:00")) }

      it "returns false" do
        expect(sealed_old_sake.new_arrival?).to be(false)
```

2022-04-18 14:52 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
他に合わせた形式のほうがよさそう
```suggestion
        expect(sake.selling_price).to be(nil)
```

2022-04-18 14:52 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
```suggestion
        expect(sake.selling_price).to be(nil)
```

2022-04-18 14:52 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
```suggestion
        expect(sake.selling_price).to be(nil)
```

2022-04-18 14:52 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
```suggestion
        expect(sake.selling_price).to be(nil)
```

2022-04-18 14:52 UTC, yonta commented on spec/models/sake_spec.rb
> +        stub_const("#{described_class}::SELLING_RATE", 3)
1個しかitないからこのままでもよいけど、context直下のbefore内に書くほうがよい。

2022-04-18 14:53 UTC, yonta commented
> * いったんmasterをお品書きにマージ([a71ed42](https://github.com/momocus/sakazuki/commit/a71ed4221016846624d8206f48ed1613831cb0b9))
> 
> * コンフリクトを解消([1f6c490](https://github.com/momocus/sakazuki/commit/1f6c4907e6aa90efe610c9f8c79411d508e53778))

この2つは別コミットにしないで。
`<<<<<<HEAD`のような行はdiffのコンフリクトをしめすワードであってプログラムではない。
なのでこれを解決したコミットがマージコミットであるべき。

2022-04-20 02:44 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +    context "if the argument is nil" do
同ファイルのempty_to_default specの書き方に合わせているため、変えない。

2022-04-20 02:45 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +    context "if the argument is integer" do
同ファイルのempty_to_default specの書き方に合わせているため、変えない。

2022-04-20 03:02 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(sealed_old_sake.new_arrival?).to be(false)
testこけるようになったな。なぜだー。
```ruby
    context "when sake is seald and created within 4 weeks" do
      let(:sealed_new_sake) { create(:sake, bottle_level: "sealed", created_at: Time.zone.parse("2022-01-01 10:30:00")) }

      it "returns true" do
        expect(sealed_new_sake.new_arrival?).to be(true)
      end
    end
```

```shell
$ bundle exec rspec spec/models/sake_spec.rb 
..............F.........

Failures:

  1) Sake Sake.new_arrival? when sake is seald and created within 4 weeks returns true
     Failure/Error: expect(sealed_new_sake.new_arrival?).to be(true)
     
       expected true
            got false
     # ./spec/models/sake_spec.rb:142:in `block (4 levels) in <top (required)>'

Finished in 1.98 seconds (files took 2.23 seconds to load)
24 examples, 1 failure
```

2022-04-20 03:10 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
rubocopくんがbe_nilにしろって言う
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecbenil

2022-04-20 03:10 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
同上

2022-04-20 03:10 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
同上

2022-04-20 03:10 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
同上

2022-04-20 03:13 UTC, momocus commented on app/controllers/sakes_controller.rb
> +                          s: "id desc").result(distinct: true)
確かに要らない
Fixed at e42aead28d631b0c519969f485ef78f1629b6a80

2022-04-20 03:13 UTC, momocus commented on app/javascript/sakes_menu.js
> +// empty entry point
Fixed at 5a7a1397a50cc03baea37102a1ac3d93159887e6

2022-04-20 03:25 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(sealed_old_sake.new_arrival?).to be(false)
travel_toが行われる前にletが評価されちゃうんかな？

2022-04-20 09:16 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(sealed_old_sake.new_arrival?).to be(false)
Fixed at c0d644c1b7bf40cbbf80d05def921ec62c9a15f6

2022-04-20 09:16 UTC, momocus commented on spec/models/sake_spec.rb
> +        stub_const("#{described_class}::SELLING_RATE", 3)
Fixed at c0d644c1b7bf40cbbf80d05def921ec62c9a15f6

2022-04-20 11:20 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(sake.selling_price).to be_nil
その上のBeEqの項目では`be(nil)`がgoodになってるのにｗ
Rubocopくんが言うんじゃしゃーないな。

2022-04-20 11:25 UTC, yonta approved these changes

2022-04-20 11:25 UTC, merged

2022-04-20 11:25 UTC, yonta commented
お疲れさま！