酒のformのデザインを新たにした
momocus/sakazuki pull request #478
Opened 2022-04-19 10:23 UTC by yonta

- Update: 酒のformを新たなデザインにした
- Add: 酒の名前がからのときはflashメッセージがないテストを追加

2022-04-21 17:31 UTC, yonta commented
## PC版変更前

![image](https://user-images.githubusercontent.com/849256/164517442-cd62ba10-9c46-4e11-b5b9-b941c56e035f.png)
![image](https://user-images.githubusercontent.com/849256/164517492-e4b61ad6-a8a3-4121-b770-2088df6d285f.png)
![image](https://user-images.githubusercontent.com/849256/164517545-7d36db73-11de-4a87-8eb0-203958786f92.png)

2022-04-21 17:32 UTC, yonta commented
## PC版変更後

![image](https://user-images.githubusercontent.com/849256/164517670-885bd298-1fb9-41db-ae97-04c49657c20d.png)
![image](https://user-images.githubusercontent.com/849256/164517693-711cbb16-3e1c-4843-b92f-640e684f1f37.png)
![image](https://user-images.githubusercontent.com/849256/164517725-ac7a7cf2-0916-4d99-a394-4e25df022048.png)

2022-04-21 17:35 UTC, yonta commented
## スマホ版変更前

![image](https://user-images.githubusercontent.com/849256/164518082-c465f062-9853-48bc-901d-17b1d0ec3c02.png) ![image](https://user-images.githubusercontent.com/849256/164518141-1b92cd26-96f9-421a-9b9f-2dc5cb99804d.png)
![image](https://user-images.githubusercontent.com/849256/164518186-118f2f94-6f33-49b4-851c-ce4b95d86d2d.png)

2022-04-21 17:36 UTC, yonta commented
## スマホ版変更後

![image](https://user-images.githubusercontent.com/849256/164518345-5b34c8f5-5906-4b49-9285-601eeaad5f3e.png) ![image](https://user-images.githubusercontent.com/849256/164518374-ac872723-9565-4dad-a8a6-6b619238214c.png)
![image](https://user-images.githubusercontent.com/849256/164518395-ef4c6b71-1f9a-4ad2-9fce-006980995bec.png)

2022-04-22 10:56 UTC, momocus requested changes
大筋おっけーです
細かい修正が要ります

2022-04-29 17:26 UTC, yonta commented on config/locales/views/sake.ja.yml
> +      detail: :sakes.show_detail.detail
使ってる。
詳細viewでタイポしてた。

commit e13c40569a7d93967ab7c2fb7e91356ee77a144f

2022-04-29 17:28 UTC, yonta commented on app/assets/stylesheets/sakes_form.scss
> +  @extend .w-25;
`date_select(with_css_classes: true)`で呼び出すと、各セレクターごとにHTMLのクラスが割り振られる。
年・月・日でスタイルを変えたいときに使うやつです。

![image](https://user-images.githubusercontent.com/849256/165993834-184b9247-dca5-4fa2-9ed4-eaef1c508d9c.png)

2022-04-29 17:30 UTC, yonta commented on app/assets/stylesheets/sakes_form.scss
> +  @extend .w-25;
commit 0e2d72b25e666476a2c0e95ed0ec7415d862fd0a

2022-04-29 17:32 UTC, yonta commented on app/views/sakes/_form-abstract.html.erb
> +                <%= form.label(:seimai_buai, class: "form-label") %>
そうそう。
例えば精米歩合は、showでは詳細にかかれているけど、formでは概要のほうに入れている。
showでは一番最初の表示は概要と名前をつけている。
一方で、formでは一番最初はラベル必須情報（今は名前つけされていない）という過去の名前付けしてた。
このほうが使いやすいと思う。

2022-04-29 17:33 UTC, yonta commented on app/views/sakes/_form-abstract.html.erb
> +<div class="accordion my-2" id="accordionAbstract">
ただの好みで分けている。
Bootstrapの標準を重視するなら[Always Open](https://getbootstrap.jp/docs/5.0/components/accordion/#always-open)を使うとよさそう。

やってみるかー。

2022-04-29 17:38 UTC, yonta commented on app/views/sakes/_form-abstract.html.erb
> +<div class="accordion my-2" id="accordionAbstract">
bootstrap標準に対応した

commit 60d45dbbc71feae2cde4105e0ba1f59d3b1afc98

2022-04-29 17:39 UTC, yonta commented on app/views/sakes/_form-abstract.html.erb
> +          <fieldset class="col">
`div`は汎用だけどなんの意味も持たない。
HTML5には各種意味をもったボックス・インライン要素がある。
頑張って覚えて使っていこう・・・。

2022-04-29 17:41 UTC, yonta commented on app/views/sakes/_form-abstract.html.erb
> +              <div class="w-100 d-none d-lg-block m-0"></div>
古い必須バッジ用の改行だ。いらないので削除。

commit 4d585d09a18c789bebd863789c73651bf4cbe500

2022-04-29 17:43 UTC, yonta commented on app/views/sakes/_form-abstract.html.erb
> +                  <div class="col-12 mt-2">
たしかに～🦀

2022-04-29 17:44 UTC, yonta commented on app/views/sakes/_form-abstract.html.erb
> +                  <div class="col-12 mt-2">
commit 4f0d5d73d36ebe0694e3f421a3d00ff6ed5e9dd6

2022-05-18 08:55 UTC, momocus approved these changes
💯

2022-05-18 08:56 UTC, merged