ログイン画面などユーザ系画面のデザインを一新した
momocus/sakazuki pull request #487
Opened 2022-04-21 15:36 UTC by yonta

- Update: ログイン画面のデザイン
- Update: ログイン画面のスタイルをレイアウト化した
- Update: deviseのパスワードリセット申請画面のデザイン
- Update: deviseのアカウント確認メール再送画面のデザイン
- Update: アカウントロック解除メール再送のデザイン
- Update: 招待後のパスワード設定画面のデザイン
- Update: 招待作成画面のデザイン
- Update: パスワードリセット画面のデザイン
- Update: ユーザ編集画面のデザイン
- Update: 豆腐屋さん手書きのロゴ文字をログイン画面に配置した

2022-04-21 17:37 UTC, yonta commented
## 変更前モバイル

![image](https://user-images.githubusercontent.com/849256/164518533-11709dac-239b-4e02-815c-1706a11991c0.png)

2022-04-21 17:38 UTC, yonta commented
## 変更後モバイル

![image](https://user-images.githubusercontent.com/849256/164518650-c6beb14f-fb80-4dd9-89cd-b1d3e82f8eca.png)

2022-05-18 10:10 UTC, momocus requested changes
最&高
ちょっとだけお直しお願いします

2022-05-18 10:10 UTC, momocus commented on app/views/devise/shared/_devise_layout.html.erb
> +<div class="row justify-content-center">
はーん、layoutの魔術師やん。天才。

2022-06-27 13:20 UTC, yonta commented on app/views/devise/invitations/edit.html.erb
> +<%= render(layout: "devise/shared/devise_layout") do %>
レイアウトからリンクを外した。
commit  2bce755fc2d2fdbb3b14a4c8a46a0667cd524aa2 で対応。

2022-09-04 14:53 UTC, momocus approved these changes

2022-09-04 14:54 UTC, merged