Herokuからfly.ioへ移行
momocus/sakazuki pull request #518
Opened 2022-11-16 03:03 UTC by momocus

Close #500

- fly.ioへデプロイするのに必要なDockerfileなどを追加した。
  - これまであった開発用Dockerfileは名前を変えた。
- Github Actionsでmasterへのpush時に自動Deployが走るようにした。

Note
本来ならば開発用のDockerfileと本番用のDockerfileを分ける必要はないはず。統合したい。

2022-11-16 03:06 UTC, yonta commented
> 本来ならば開発用のDockerfileと本番用のDockerfileを分ける必要はないはず。統合したい。

Dockerfile内部で条件分岐するってこと？
開発環境と本番環境ではnpmやgemの必要なパッケージが違うから、違うDockerfileが必要な気がしているんだけど。
それはそれで分岐するために`docker-compose 引数ほげほげ`みたいなコマンド呼び出しが必要になって、結局管理するためにMakefileを導入しようとかになるんじゃないかな。

2022-11-16 03:13 UTC, yonta commented
あああああ、heredoc対応してないDockerfileが増やされる～～～～うわーーーん

2022-11-16 09:03 UTC, yonta commented
>  本来ならば開発用のDockerfileと本番用のDockerfileを分ける必要はないはず。統合したい。

PRの中身みたけど、やっぱり統合は厳しそう。
fly.io用のdockerイメージは特殊なイメージを使っている。
また、本番用と違ってイメージを最小化するためにマルチステージビルドを使っている。
これは変わりにビルド時間が長いや、必要なコマンドなどのツールがイメージに含まれないなど、開発に使いづらい要素があるよ。

2022-11-16 09:17 UTC, yonta commented on fly.Dockerfile
> +# syntax = docker/dockerfile:experimental
ファイルパーミッションが自動生成の状態のままで、実行権限がついている。
`chmod -x`で実行権限を消しておいて。

2022-11-22 12:10 UTC, momocus commented on fly.Dockerfile
> +ARG NODE_VERSION=19.0.1
fixed at 2fd154bf8fbf966e75d248bf22866650f86d4727

2022-11-22 12:10 UTC, momocus commented on fly.Dockerfile
> +ARG DEPLOY_PACKAGES="postgresql-client file vim curl gzip libsqlite3-0"
fixed at 2fd154bf8fbf966e75d248bf22866650f86d4727
libsqlite3-0どころか、file vim curl gzipもいらなかったわ...

2022-11-22 12:17 UTC, momocus commented on fly.Dockerfile
> +COPY . .
Fixed at 79e91a7ed4195968a24c70f2deaa422ab05487a

2022-11-22 12:18 UTC, momocus commented on fly.Dockerfile
> +# syntax = docker/dockerfile:experimental
fixed at 2fd154bf8fbf966e75d248bf22866650f86d4727

2022-11-22 13:11 UTC, momocus commented
c8032c2bf9e2bb2210f3d2f5546df71121cb89e9 のあとmasterにrebaseしたら、Github Actionsによるcheckでこけていた。これを解消するため、以下を行った。
- prettierとrubocop で検出されたエラー修正(f2df937)
- hadolintで検出されたエラー修正 (2fd154bf8fbf966e75d248bf22866650f86d4727, 58ad230ca720a04bf38a0ae85a18388a43931a19)
- hadolintが `Dockerfile: withBinaryFile: does not exist (No such file or directory)`になっていたので、dev.Dockerfile, fly.Dockerfile の両方にhadolintがかかるようcheck.ymlを修正(8ae3604)

note:
ローカルでのフォーマットチェックに使うrun-all-checks.shでは、Dockerfileとつく名前のファイルを検索してhadolintかけるようになっていたので、`Dockerfile: withBinaryFile: does not exist (No such file or directory)`は起こらなかった。

ref:
hadolint-actions の複数ファイル実行についてのIssue [How do I run multiple files](
https://github.com/hadolint/hadolint-action/issues/3#issue-562284025)

2022-11-24 07:16 UTC, yonta commented on fly.Dockerfile
> +ARG NODE_VERSION=19.0.1
Great
dev用のDockerfileも合わせて18にしといてほしい。

2022-11-24 07:18 UTC, yonta commented on fly.Dockerfile
> +ARG DEPLOY_PACKAGES="postgresql-client file vim curl gzip libsqlite3-0"
え、.tar.gzの解凍とかもやってなかったのか。
じゃあ消しといていいね。GJ

2022-11-24 07:20 UTC, yonta commented on fly.Dockerfile
> +COPY . .
`COPY . .`のままだと必要ないDockerfileとかyarnとかGemfileもコピーされちゃう。
必要な`app`とか`bin`とかだけコピーするように書き換えて

2022-11-24 07:24 UTC, yonta requested changes
議論に追記しました。
もう少し修正を。

2022-11-24 07:24 UTC, yonta commented on .github/workflows/check.yml
> +      # lint by hadolint
```suggestion
```

2022-11-24 17:17 UTC, momocus commented on fly.Dockerfile
> +COPY . .
yarn railsのasset:precompileでyarnのファイル使うので、削除できない。
Gemfileは削除しても問題なかったけど、そもそもファイルサイズが小さいので、これだけのためにCOPYを分割するのは旨みが少ない。
`COPY . . `　のままにします。

2022-11-24 17:20 UTC, momocus commented on fly.Dockerfile
> +ARG NODE_VERSION=19.0.1
しました 16c37dc3190fbb843c6158bbfe238ddd94bf4ab6

2022-11-24 18:29 UTC, yonta commented on fly.Dockerfile
> +COPY . .
らじゃー。
`rails asset:precompile`にyarn使うんなら仕方ない。

2022-11-25 08:02 UTC, momocus commented
@yonta #527 解消のため、masterにrebaseしてforce-pushしました

2022-11-25 08:14 UTC, yonta approved these changes
Great JOB!!!!!!! 👏

2022-11-25 08:14 UTC, merged

2022-11-27 16:08 UTC, yonta commented
移行先 https://sakazuki.fly.dev/