ソート機能を削除した
momocus/sakazuki pull request #519
Opened 2022-11-19 08:41 UTC by yonta

close #482

使ってないソート機能は削除だ！

### やったこと

- Remove: 酒indexのソート機能を削除した
- Refactor: ソート機能の削除により、酒コントローラのindexをシンプルに書き直した

2022-11-19 08:55 UTC, yonta commented
酒コントローラに変更があるけど、酒コントローラのテストはないからカバレッジが少しマイナスになっちった

2022-11-20 05:23 UTC, exoego commented
`spec/requests/sake_request_spec.rb` が酒コントローラーの間接的なテストっぽいので、そこを拡充すればカバレッジは回復できそう？

2022-11-22 09:11 UTC, yonta commented
よくレポートを見たら、変更で行数が変わったせいでカバレッジが下がっただけだった。
テストで実行されない行は変更前・変更後ともに2行で変わっていない。
気にせずにレビューしていいと思う。

Actionsが失敗するのは気持ち悪いし、コードカバレッジを上げ続けるのが目的ではないから、simplecovのActionsの設定を変えてエラーにしないようにするのを検討しよう。

2022-11-25 17:19 UTC, momocus requested changes
ransackの使い方むつかしいね。
修正依頼です。

2022-11-25 17:19 UTC, momocus commented on app/controllers/sakes_controller.rb
> +    query.merge!({ s: "id desc" })
[ransackのdoc](https://activerecord-hackery.github.io/ransack/getting-started/sorting/#sorting-in-the-controller)によると、sort順は
```ruby
@searched = Sake.ransack(query)
@searched.sorts = "id desc"
```
 ってした方がよさそう。

2022-11-25 22:30 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    query.merge!({ s: "id desc" })
指摘のリファクタは、PR #529 で変更・修整します。
ここでは対応しません。

2022-11-26 09:55 UTC, merged