drink_buttonの評価する機能を削除し、開封・空にするだけで使えるようにした
momocus/sakazuki pull request #547
Opened 2023-02-09 10:01 UTC by yonta

- Refactor: drink-button -> drink_button
- Refactor: form-abstract -> form_abstract
- Refactor: form-review -> form_review
- Refactor: form-detail -> form_detail
- Refactor: float-button -> float_button
- Refactor: kura-datalist -> kura_datalist
- Refactor: sakamai-datalist -> sakamai_datalist
- Refactor: sns-share-button -> sns_share_button
- Update: drink_buttonのメッセージに酒名をつけた
- Remove: drink_buttonから評価リンクを削除した
- Remove: drink_buttonの評価のテストを削除した
- Remove: 使用されなくなったSake.unimpressed?メソッドを削除
- Add: drink_buttonの開封後に評価するリンクがあることのテストを追加
- Add: drink_buttonを使って酒を開封したときに評価するリンクを追加した
- Add: drink_buttonのレビューリンクを使うとフォームのレビューアコーディオンが開くテストを追加
- Update: 評価するリンクから編集画面に行くとレビューのアコーディオンに注目するようにした

2023-02-23 05:17 UTC, momocus requested changes
シンプルでいいUIになったね

2023-02-23 05:17 UTC, momocus commented on spec/system/sign_in_redirect_by_drinkbutton_spec.rb
> -require "rails_helper"
このファイルをdrink_buttons_spec.rbマージしてくれてありがとう。どうにかしたいと思ってたんだ。助かる。

2023-02-23 05:26 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
「レビューしますか？」だと「はい/いいえ」が必要になるな。

2023-02-23 05:38 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
日本っぽくない、他のアプリケーションで見たことない、とは思いません。
これはただのユニコードに存在する記号です。
ちょっと長めのダッシュ記号であり、使用することは普通のダッシュや絵文字を使用することと何らかわりありません。

2023-02-23 05:41 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
> "何とかのお酒を開封しました。レビューしますか？" ってメッセージがいいと思います。

これだと「お酒の名前のリンク」と「レビューするリンク」の区切りがわかりにくくなるのよね。
その対策でダッシュをいれていた。

![image](https://user-images.githubusercontent.com/849256/220829190-68b68f88-61be-4841-97c1-1d1ab9980ffa.png)

![image](https://user-images.githubusercontent.com/849256/220829007-5bb3808a-3a4e-4a46-87b8-10892ac6517d.png)

2023-02-23 05:47 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    key = ".#{key}"
天才じゃん

2023-02-23 05:51 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    key = ".#{key}"
駄目だわ。
文字列内展開で複雑なことを書くと、圧倒的に見づらくなる。

2023-02-23 05:55 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    key = ".#{key}"
commit e07e3b6f81baf923e5c3a020753cd89c11caa753 で対応

2023-02-23 06:12 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    href = "#{edit_sake_path(@sake)}?review=true#headingReview" # レビュー項目を開く
天才
commit 2d6eb16e5130241df1eaa31df5885ee28e50bdbe で対応

2023-02-23 06:13 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +  describe "label text" do
commit  14b525752fa6f02182bb90ff9357c0b2d9bbced7 で対応

2023-02-23 06:13 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(described_class.alcohol_stock(include_empty: true)).to eq(2820)
commit  14b525752fa6f02182bb90ff9357c0b2d9bbced7 で対応

2023-02-23 06:15 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +  describe "label text" do
これはdrink_buttonsのテスト。
ファイル名やファイルの先頭の`RSpec.describe "Drink Buttons" do`に書いてある。
drink_buttonsは3つドットの中の機能なので十分に指定している。

2023-02-23 06:18 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +    context "for sealed bottle" do
書けない。

この文脈の外の別なテストでも`sealed_sake`が登録されている前提で書いたテストがある。
これはグローバルな前提のlet。
`for sealed bottle`と書いているように、未開封の酒に関するテストと宣言しているだけ。

あと`let`は不可で`let!`を使う必要がある。
理由は`selaed_sake`というidを参照する前に、未開封酒のリンクが必要なテストがあるため。

2023-02-23 06:19 UTC, yonta commented on spec/system/sign_in_redirect_by_drinkbutton_spec.rb
> -require "rails_helper"
やったぜ

2023-02-23 06:31 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    key = ".#{key}"
対応できてなかった。
やはり2行必要。

2023-02-24 02:34 UTC, momocus commented on app/controllers/sakes_controller.rb
> +    key = ".#{key}"
あそっか、|| の左側が常にtureになっちゃうのか

2023-02-24 03:54 UTC, yonta commented on spec/models/sake_spec.rb
> +        expect(described_class.alcohol_stock).to eq(1620)
下記

2023-02-24 13:16 UTC, momocus commented on spec/models/sake_spec.rb
> +        expect(described_class.alcohol_stock(include_empty: true)).to eq(2820)
ごめん見逃してた

2023-02-24 13:31 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +  describe "label text" do
label、私は酒瓶に貼ってある紙のことだと勘違いしていまう。labelって単語を使わないでほしい。
describe "i18n text" はいかがですか？

2023-02-24 13:33 UTC, momocus commented on spec/system/drink_buttons_spec.rb
> +    context "for sealed bottle" do
納得しました

2023-02-24 13:51 UTC, momocus commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
「開封しました」って文字列が十分長いから、区切りはわかりやすいと思う。それでも気になるなら、ページタイトルの"日本酒リスト - 4合"みたいに、" - "でつなげばいいんじゃない？　他の箇所と統一感もあっていい。

⸺で検索しても日本語のページはほとんどヒットしないし、そもそも検索結果も少ない。

＞ちょっと長めのダッシュ記号であり、使用することは普通のダッシュや絵文字を使用することと何らかわりありません。
普通のダッシュや絵文字にしたって、どの文字をどう使うかは悩むでしょう。

2023-02-24 13:58 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
他日本語サイトで使われてないから使わない、は何も根拠にならない。
それを認めると、任意の文字で初めて使うサイトが現れないことになる。

2023-02-24 14:00 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
> ＞ちょっと長めのダッシュ記号であり、使用することは普通のダッシュや絵文字を使用することと何らかわりありません。
> 普通のダッシュや絵文字にしたって、どの文字をどう使うかは悩むでしょう。

もちろんそれはそう。どの文字を使うかは悩む。
この反論は「他のWebアプリケーションで使われてるのあまり見たことない」に対して、ただの文字なんだからそんなことを気にする必要はないと思う、の意です。

2023-02-24 14:15 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
区切り文字何もなし、は避けたい。
文字列が続いていると、リンクの終わりがどこか分かりづらい。
特に複数行になるような長い酒の名前だと、酒リンクと評価リンクの区別が難しくなる。

試してみたけど、半角ハイフンはやっぱ弱くて区切りとして見ずらいなぁという印象。
ダッシュ以上の長さがいい。

## ダブルダッシュ

![image](https://user-images.githubusercontent.com/849256/221199716-a4576b1a-d3af-4ea1-b450-39f14bfebcc7.png)

## ダッシュ

![image](https://user-images.githubusercontent.com/849256/221199928-7f69afce-1eb4-4e08-be12-01e1bd39e449.png)

## ハイフン

![image](https://user-images.githubusercontent.com/849256/221199812-3a6d14c4-3ac0-477b-9a24-6de860aeaa24.png)

2023-02-24 14:19 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
より長い名前の酒。
酒名前が長いと区切りが弱いので、よりダブルダッシュのほうがよいと思う。

## ダブルダッシュ

![image](https://user-images.githubusercontent.com/849256/221200864-ee573c52-8621-46ee-aa75-10cc5985c997.png)

## ダッシュ

![image](https://user-images.githubusercontent.com/849256/221201007-14e88ee4-b78e-4ffe-b250-a99b7254c6f7.png)

## ハイフン

![image](https://user-images.githubusercontent.com/849256/221201068-bc928c2b-b8c0-42cb-a9ac-6b6d9bb59d84.png)

2023-02-24 14:45 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +  describe "label text" do
Drink Buttonのテストなので、酒瓶ラベルはちょっと違うかなあ。
link labelとかのがいいかも。

それこそi18nは、翻訳に関するテストに見えて誤解を招く。

link textとかにしときます。

2023-02-24 15:52 UTC, momocus commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
本当はCSSとかで配置を正したい箇所を、文字でどうにかしようとしているのが良くないんだな。
とはいえ現状のflashの作りとして、CSSに手を加えにくい。
なんかもう倍角ダッシュでもいい気がしてきた。

さっき話したアイデア：
xxxxを開封しました ⸺ :pen: レビューする

2023-02-25 03:33 UTC, yonta commented on spec/system/drink_buttons_spec.rb
> +  describe "label text" do
commit ba5e4fee81fcf9fe26bdfaf1a6c06a1d098a7b60

2023-02-25 04:40 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
こんな感じにしました。
かわいいですね。

## xl以上

![image](https://user-images.githubusercontent.com/849256/221338572-68341e7d-9444-453e-bfdb-2e0188330b90.png)

## モバイル

![image](https://user-images.githubusercontent.com/849256/221338580-e72f5124-63da-4cf1-b937-746519b02b32.png)

2023-02-25 04:42 UTC, yonta commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
commit 570b097a7d2880c89cc5cf549e65bcfc6aa10a10

2023-02-25 09:17 UTC, yonta commented
rebaseしてpush

2023-02-28 03:08 UTC, momocus commented on config/locales/controllers/sakes.ja.yml
> +      open: "%{name} を開封しました。 ⸺ %{link}"
❤️

2023-02-28 03:10 UTC, momocus approved these changes

2023-02-28 03:10 UTC, merged