メタタグのタイトルに検索内容を含めるようにした
momocus/sakazuki pull request #551
Opened 2023-02-15 06:13 UTC by yonta

- Add: 酒indexのタイトルに関するビューテストを追加
- Update: 酒indexのmetaタイトルには総量でなく検索ワードをいれた

2023-02-17 04:56 UTC, momocus requested changes

2023-02-17 04:56 UTC, momocus commented on app/views/sakes/index.html.erb
> +      <% search = "#{params.dig(:q, :all_text_cont)} - " || "" %>
検索文字列が空のとき（トップページ開いたとき）にも先頭にハイフンが入っちゃってる。
![image](https://user-images.githubusercontent.com/6294782/219548655-88acdf3c-6311-4067-a377-1dd1937720f3.png)

presenceメソッドを使ったらいいかも
https://api.rubyonrails.org/classes/Object.html#method-i-presence

2023-02-17 07:05 UTC, yonta commented on app/views/sakes/index.html.erb
> +      <% search = "#{params.dig(:q, :all_text_cont)} - " || "" %>
はー、空文字忘れてた～～～～

2023-02-17 09:25 UTC, yonta commented on app/views/sakes/index.html.erb
> +      <% search = "#{params.dig(:q, :all_text_cont)} - " || "" %>
commit 8a0d7bb で修正。
わびテストは commit 96bd845

2023-02-17 14:05 UTC, momocus commented on app/views/sakes/index.html.erb
> +      <% search = "#{params.dig(:q, :all_text_cont)} - " || "" %>
2 行になるのか
Helperに切り出した方が分かりやすいんじゃない？　そうでもないかな？

2023-02-21 03:56 UTC, yonta commented on app/views/sakes/index.html.erb
> +      <% search = "#{params.dig(:q, :all_text_cont)} - " || "" %>
いいじゃん。そうしよう。

2023-02-21 08:10 UTC, yonta commented on app/views/sakes/index.html.erb
> +      <% search = "#{params.dig(:q, :all_text_cont)} - " || "" %>
commit 87c284a35b4877aa7f3c7d4040e2ada67dded23a で対応

2023-02-21 12:50 UTC, momocus approved these changes
:otsukare: :arigato:

2023-02-21 12:50 UTC, merged