酒フォームで製造年月の年と月を1つのセレクタで選ぶようにした
momocus/sakazuki pull request #556
Opened 2023-02-17 08:35 UTC by yonta

close #477
after #555

我々が本当にほしかったもの

## やったこと

- 酒formにおける製造年月の入力を年・月別々のセレクタから1つのセレクタにした
- 酒のアトリビュートの翻訳を「製造年月日」から「製造年月」に変更
  - 日なんて概念なかった
- 酒フォームの製造年月の実装に合わせて、BYもリファクタ
  - めちゃくちゃスッキリした
- フォームが変わったのに伴い、関連テストを修正

2023-02-28 02:48 UTC, yonta commented
rebase

2023-03-10 08:28 UTC, yonta commented
rebaseしました

2023-03-16 08:39 UTC, momocus requested changes
神アプデ！

2023-03-16 09:00 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def month_range
helperはprivateにできないよ。
この後mixinされる都合で、viewからはprivateにしようがprotectedにしようが、全部publicになる。

2023-03-16 09:00 UTC, yonta commented on app/helpers/sakes_helper.rb
>    def by_range
helperはprivateにできないよ。
この後mixinされる都合で、viewからはprivateにしようがprotectedにしようが、全部publicになる。

2023-03-16 09:38 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  def by_collection
commit fabb1fb314d18a2b8c096ede99fbc600d1f2458d

2023-03-16 09:39 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    flash[:info] = t(".copy", name: alert_link_tag(copied.name, sake_path(copied))) if copy
悩んだんだよねー。戻すか。

2023-03-16 09:53 UTC, yonta commented on app/controllers/sakes_controller.rb
> +    flash[:info] = t(".copy", name: alert_link_tag(copied.name, sake_path(copied))) if copy
commit 290b916fdab1986582782d96eb1bbe2f9ce2e371

2023-03-21 15:01 UTC, momocus commented on app/helpers/sakes_helper.rb
>    def by_range
privateにできないことはない（moduleをincludeしたクラスのメソッドを他のオブジェクトから参照する時とか）けども、あまり意義がないのね。
じゃあby_collectionメソッドとまとめるか、さもなくばby_rangeの単体テストを書きましょう。

2023-03-21 15:15 UTC, momocus requested changes

2023-03-21 15:15 UTC, momocus commented on app/helpers/sakes_helper.rb
> +  # @param last [Date] 最後の年月
`@param`は引数の説明だから、この2行はいらない。

2023-03-21 15:15 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +  describe "by_collection" do
by_collectionとby_rangeのテストが混ざってるように思える。
by_rangeのテストを切り出すか、さもなくばby_collectionメソッドとby_rangeメソッドを合体させた方がいい。

2023-03-21 15:15 UTC, momocus commented on spec/helpers/sakes_helper_spec.rb
> +  describe "bindume_collection" do
bindume_collectionとmonth_rangeのテストが混ざっているように思える。
month_rangeのテストを切り出すか、さもなくばbindume_collectionメソッドとmonth_rangeメソッドを合体させた方がいいと思う。

2023-03-21 15:45 UTC, yonta commented on app/helpers/sakes_helper.rb
>    def by_range
補助関数だし、テストいらないと思っている。
それを書くと言い出すと、補助関数への切り出しを行わなくなる。
テストを網羅することが目的ではない。

2023-03-21 15:59 UTC, yonta commented on app/helpers/sakes_helper.rb
> +  # @param last [Date] 最後の年月
古いドキュメントが残ってる～～。
直す。

2023-03-23 05:21 UTC, momocus approved these changes

2023-03-23 05:21 UTC, merged