画像アップロード時に.webpに変換してサイズを小さくした
momocus/sakazuki pull request #559
Opened 2023-02-18 03:33 UTC by momocus

Close https://github.com/momocus/sakazuki/issues/537
酒画像を.webpに変換してアップロードし、サイズが小さくなるようにした

本番環境でCloudinaryがどう動くかみようとしたらうっかり #558 がMergedになってしまったので、このプルリクを書いた。

2023-02-18 06:05 UTC, momocus commented
前提：
開発環境ではCloudinaryの代わりにMiniMagicを使っている。

問題：
このMiniMagicでファイル形式を.webpに変換したとき、ブラウザで画像が表示されなかった。
ブラウザでコードを確認したところ、画像のパスが変換前のxxxx.jpgになっていた。

対策：
開発環境では`process convert`とは別にファイル名を変える処理を追加した。 07eab06 

なお[CarrierWaveのReadme](https://github.com/carrierwaveuploader/carrierwave#using-rmagick)にRMagicの例が載っていた。MiniMagicも同様にする必要があったようだ。
（ファイル形式だけ変換して名前を変換してないのか？　ファイル形式も名前も変換しているが、参照先だけ古いファイル名なっているのか？　よくわかってない）

また[cloudinary's example](https://cloudinary.com/documentation/rails_carrierwave#upload_examples)にある通り、Cloudinaryでconvert するときにfilenameの変換は要らない。
（というか本番環境でfilenameを変えると、flyのデプロイが失敗した）

2023-02-18 06:07 UTC, momocus commented
CarrierWaveがほんとわからん。processとかversionとかどういう仕組みなのあれ。雰囲気で使ってる。

2023-02-18 07:56 UTC, yonta commented
動いた。

2023-02-18 07:57 UTC, yonta commented
ローカルで試すと、思ったよりも画像が圧縮されない。
これが本当なら、webp化にさらに画像の縮小も必要かも。
画像送るので、Cloudinary環境で試してみよう。

![image](https://user-images.githubusercontent.com/849256/219848910-ffe70515-7249-4611-a95a-f96a9ef4711f.png)

2023-02-18 08:21 UTC, yonta commented
Cloudinary上だと画質80/100という数値でやっているので、もう少し圧縮されて4.57MBが1.5MBくらいになった

2023-02-18 08:27 UTC, yonta commented
1.5MB換算だと、1本に4枚画像で10GBを使うと約1700本登録できる。
ざっくり年200本登録している実績だと、8年くらいでCloudinaryの無料枠がつきる。

2023-02-18 08:49 UTC, yonta commented
ざっくり、Cloudinaryで手動変換したテスト。
元画像jpg: 4.6MB
webp q_quto: 1.3MB
avif q_auto: 0.5MB

2023-02-18 08:50 UTC, yonta commented
もう全部avifでいいんじゃないかな？サファリも対応しているし。

2023-02-18 08:59 UTC, yonta requested changes
いろいろ議論した内容で変更しよう

2023-02-18 08:59 UTC, yonta commented on app/uploaders/image_uploader.rb
> +  process(convert: "webp")
production環境のみのprcessで、開発環境では変換しなくていいんじゃないかな

2023-02-18 08:59 UTC, yonta commented on app/uploaders/image_uploader.rb
> +  process(convert: "webp")
変換方法の指定は検討しよう。

- webpよりもavifのほうがいいんじゃないか
- `q_auto`でクオリティ指定しよう
- iPhone14 Pro MAXのカメラが48MPとだいぶでかい画像作れるので、現状主流の12MPくらいで上限をいれよう。
  - 具体的には、Xperia1やiPone11は12MPで4032x3024
  - widthとheightを4032かちょっと上の4050とかでlimit等をいれる
- 他のオプションは何があるか？
  - cloudinaryの手動editを参考に考える

2023-02-18 08:59 UTC, yonta commented on app/uploaders/image_uploader.rb
> +    %w[jpg jpeg gif png webp]
これってアップロードのホワイトリストじゃないっけ？
webpやavifをアップロードする人っているんだろうか。
とりあえず入れておいてはいいとも思うけど。

2023-02-20 05:58 UTC, yonta commented on app/uploaders/image_uploader.rb
> +  process(convert: "webp")
確かprocessは処理順も意味あるよね。
現状の書き方だと画像変換する前にOCRする。
OCRの文字を読み込むだけならこれが最適だけど、OCRでサムネイル切り取りだと再度OCRされそう。
理由は画像変換にcropのような画像切り抜きなどもあるので、変換前のOCR位置情報が使えない可能性があるから。
画像加工してからOCRする順番にしよう。

2023-02-21 08:01 UTC, momocus commented on app/uploaders/image_uploader.rb
> +  process(convert: "webp")
AVIFでアップロードはできるけど、AVIFで配信するのにはCloudinaryの有料アカウントが必要な模様。
AVIFで保存して、WebPで配信しよう。

2023-02-21 08:04 UTC, momocus commented on app/uploaders/image_uploader.rb
> +    %w[jpg jpeg gif png webp]
はい。ユーザーがアップロードしようしている画像（変換前）がこの拡張子以外だと、アップロードに失敗するようになる。
とりあえず入れておけばいいかなの気持ち。

2023-02-21 11:25 UTC, momocus commented on app/uploaders/image_uploader.rb
> +  process(convert: "webp")
Fixed at a55fce1dbcd26b006acf9363357a7a09b275eec8

2023-02-21 12:41 UTC, momocus commented on app/uploaders/image_uploader.rb
> +  process(convert: "webp")
画像サイズに制限を入れた 80e39564fc10122cf4b1029f631188e98bf9f3a7
AVIFでアップロードし、Webp形式で配信するようにした 858b07a9d7bc5b8cc359fc1c44194c21a639efc0
q_auto指定 f275a45b65bdfc47fd8a6b3f68e882049037b033

2023-02-23 04:12 UTC, yonta approved these changes
めっちゃ小さいパッチに収まったね。
完全に理解しているじゃん:+1:

2023-02-23 04:12 UTC, yonta commented on app/uploaders/image_uploader.rb
> +    process(convert: "webp", resize_to_fill: [600, 600]) if Rails.env.production?
素朴な疑問で、dev環境で`resize_to_fill`を削除したのはなんで？

2023-02-23 04:49 UTC, momocus commented on app/uploaders/image_uploader.rb
> +    process(convert: "webp", resize_to_fill: [600, 600]) if Rails.env.production?
dev環境で画像の変換を行わないようにしたから (a55fce1)

dev環境ではアップロード時も配信時も、画像変換は一切やらない。分かりやすくていいと思ってる。

2023-02-23 08:37 UTC, yonta commented
READMEにCloudinary保存時はavifで圧縮保存って書いておいたほうがいいかも

2023-02-24 03:56 UTC, yonta commented on app/uploaders/image_uploader.rb
> +    process(convert: "webp", resize_to_fill: [600, 600]) if Rails.env.production?
これやっておかないと、縦横比が違う写真に対して歪んだサムネイルでたり、dev環境で大量の巨大画像が読み込まれてindex重たくなるんじゃないかな。
実害がありそう。

2023-02-24 05:06 UTC, yonta approved these changes
再レビューリクエストきてたけど、前回のレビューですでにApprove出しているよ

2023-02-24 13:06 UTC, merged