酒タイトルから酒情報を補完する
momocus/sakazuki pull request #568
Opened 2023-02-24 06:34 UTC by yonta

close #379

これが欲しかった

## やったこと

- 酒の”しぼり”のtypo修正（絞り→搾り）
- 酒フォームでなぜか残っていた「火入れ状態」から状態を削除
- 名前からの酒情報補完機能のテストを追加
  - 合わせて、蔵・都道府県の補完機能のスペック名を変更
- 酒の名前から詳細情報などを補完する機能を実装した
  - 補完される項目は、特定名称、季節、酛、搾り、ろ過、火入れ、加水。

2023-02-24 23:25 UTC, exoego commented on app/javascript/autocompletion/complete_detail.ts
> +    .includes(true)
```suggestion
    .some((word) => {
      return target.includes(word)
    })
```
１つでも true が見つかった時点でスキャンを終えられる some のほうが効率が良いでしょう
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2023-02-25 01:43 UTC, yonta commented on app/javascript/autocompletion/complete_detail.ts
> +    .includes(true)
欲しかった関数だ！！
ありがとう！！

名前付けが言語によって違うので検索ミスりがち。

2023-02-25 01:54 UTC, yonta commented
/fix

2023-02-25 02:19 UTC, yonta commented
/fix

2023-02-25 02:33 UTC, yonta commented
/fix

2023-02-28 03:42 UTC, momocus requested changes

2023-02-28 03:42 UTC, momocus commented on app/javascript/autocompletion/complete_detail.ts
> + * 指定した複数文字列のいづれか1つでも含まれるかをチェックする
xいづれか
oいずれか

何箇所かあるからまとめて修正しといて

2023-02-28 03:42 UTC, momocus commented on app/javascript/autocompletion/complete_detail.ts
> +/** 補完候補 */
純粋な疑問：今回からtypescriptに（doc生成できそうな）コメントを書き始めたのはどうして？

2023-02-28 03:42 UTC, momocus commented on app/javascript/autocompletion/detail_dicts.ts
> +  { keywords: ["純米大吟醸"], completion: "junmai_daiginjo" },
特別純米が抜けてる

2023-02-28 04:00 UTC, yonta commented on app/javascript/autocompletion/complete_detail.ts
> + * 指定した複数文字列のいづれか1つでも含まれるかをチェックする
高貴な生まれだったのがまろびでてしまった

commit d9d18559afc3f748c2996633dc84925d7f12dc8b

2023-02-28 04:01 UTC, yonta commented on app/javascript/autocompletion/complete_detail.ts
> +/** 補完候補 */
なんとなく。

今まではtypedocを知らなかったんだけど、知ったから。
RubyのYARD使い始めたときに気づけばよかったね。

2023-02-28 04:01 UTC, yonta commented on app/javascript/autocompletion/complete_detail.ts
> +/** 補完候補 */
ちなみにtypedoc書いておくと、IDEでの補完やマウスオーバー時に便利になるはず。

2023-02-28 04:02 UTC, yonta commented on app/javascript/autocompletion/detail_dicts.ts
> +  { keywords: ["純米大吟醸"], completion: "junmai_daiginjo" },
Oooooooops!!!!

2023-02-28 04:08 UTC, yonta commented on app/javascript/autocompletion/detail_dicts.ts
> +  { keywords: ["純米大吟醸"], completion: "junmai_daiginjo" },
commit 7250a7b59ff6e60f1fe3bda945b685ba32741005 で修正 
commit cc5133d33449cfe39f40dc86ed4cc631c265324b で詫びテスト

2023-03-01 16:08 UTC, momocus approved these changes
🙌

2023-03-01 16:10 UTC, merged