Use share api
momocus/sakazuki pull request #569
Opened 2023-02-24 10:06 UTC by momocus

Close #548

- twitterとFacebookのシェアボタンを消した
- 
[Web_Share_API](https://developer.mozilla.org/ja/docs/Web/API/Web_Share_API)を呼び出すシェアボタンを追加した

2023-02-25 05:51 UTC, yonta requested changes
Firefoxで動かないの、泣いちゃうわね。

2023-02-25 05:51 UTC, yonta commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
シェアボタンがprimaryカラーになっている。
アイコンの時点で押せばシェアと伝わるし、本文と同じ黒のほうが見栄えがいい気がする。

2023-02-25 05:51 UTC, yonta commented on app/views/sakes/_sns_share_button.html.erb
> +<div class="row">
`btn-lg`でサイズ調整はやめたほうがよくない？
どんなサイズになるのか保証されていない。

元の通り、`fs-*`を使ってアイコンの文字サイズ指定のほうがいい気がする。

2023-02-25 05:51 UTC, yonta commented on app/javascript/share/share.ts
> +  })
素朴な疑問ですが、このキャッチは何を想定しているの？

例えばshare APIがないFirefoxではTypeErrorになるのでキャッチされない。

```console
Uncaught TypeError: navigator.share is not a function
    <anonymous> share.ts:12
    EventListener.handleEvent* share.ts:11
    <anonymous> sakes_show-905c00c806e73305c9444c03f448044816e6b921.js:16815
[share.ts:12:12](http://localhost:3000/javascript/share/share.ts)
    <匿名> share.ts:12
    (非同期: EventListener.handleEvent)
    <匿名> share.ts:11
    <匿名> sakes_show-905c00c806e73305c9444c03f448044816e6b921.js:16815
```

そもそもエラーをキャッチしている動作の意味がなくない？
キャッチされても内容を`console.error`でconsoleに出すだけで、キャッチされなくてもエラー情報はコンソールにでる。
むしろキャッチしてるほうが、メッセージ以外の情報を握りつぶしている。

2023-02-25 08:40 UTC, exoego commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
上段のハンバーガーメニューアイコンの枠線と下段のシェアアイコンの右端を合わせるより、２つのアイコンの左右が揃ってるほうがバランスが取れてるように思います。
下段のシェアアイコンにも枠線をつけて、アイコンボタンとしての統一感を出すとか

2023-02-25 09:20 UTC, yonta commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
なるほど確かに。
前はアイコン2つ並びだったので右揃えだったけど、アイコンの中心がそろってる現状のほうがいいか。

2023-03-02 09:31 UTC, momocus commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
ボタンの上下パディングを消しました 50a0e35de05e4716977daf6426cff5ecc864ac33
これにより、蔵・都道府県とシェアボタンのy軸がひどくずれてしまったので、alignの指定方法を変えました。 b0ce322b2c1de0f63408721c367f3b8ce5081f5a

2023-03-02 09:36 UTC, momocus commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
Fixed at 50a0e35de05e4716977daf6426cff5ecc864ac33
こうなった。いいじゃん。
<img width="400" alt="スクリーンショット 2023-03-02 18 32 18" src="https://user-images.githubusercontent.com/6294782/222389396-41b96c42-ec72-4146-b154-8df968c14e41.png">

2023-03-02 09:48 UTC, momocus commented on app/views/sakes/_sns_share_button.html.erb
> +<div class="row">
Fixed at 50a0e35de05e4716977daf6426cff5ecc864ac33

2023-03-02 09:53 UTC, momocus commented on app/javascript/share/share.ts
> +  })
share APIがないときにいい感じにエラー吐いてくれるかなと言う気持ちで入れていましたが、動作検証をしていませんでした。ごめんなさい。
32e958a3cb45d644336d9e741dbee9ef557f3e78 にて、例外のキャッチをやめました。

2023-03-02 14:17 UTC, yonta commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
`btn-link-secondary`なんてクラスないよね？

2023-03-02 14:23 UTC, yonta commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
lg以上のサイズのときに揃ってないね。
原因はh1タグの上部にあるマージン。
h1の上部を`mt-0`適用して、親要素の`row`に同サイズのマージントップを入れることで解決できると思う。

![image](https://user-images.githubusercontent.com/849256/222454963-70518aa1-3ee8-438d-83a0-ad5389a876db.png)

2023-03-02 14:25 UTC, yonta requested changes
別なところがズレてるので対処願います

2023-03-02 14:25 UTC, yonta commented on app/javascript/share/share.ts
> +  void navigator.share(shareData)
素朴な疑問なんだけど、このvoidは何？

2023-03-10 08:24 UTC, momocus commented on app/javascript/share/share.ts
> +  void navigator.share(shareData)
ESLintから怒られたので。
https://typescript-eslint.io/rules/no-floating-promises/

今回は`navigator.share`の例外処理はあえて入れなかったので、明示的にvoidを入れた。

2023-03-10 08:34 UTC, momocus commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
あれ？？？

2023-03-10 10:24 UTC, momocus commented on app/views/sakes/_sns_share_button.html.erb
> +    <button type="button" class="btn btn-link btn-lg pt-0" id="share_button"><i class="bi bi-share"></i></button>
Fixed at a7de7b9a3a578fc511a7fe30982b4a2495dc57db
button tag使うのやめて a tagにした上で、link-darkで文字色指定しました。

2023-03-10 13:43 UTC, yonta commented on app/javascript/share/share.ts
> +  void navigator.share(shareData)
TypeScriptのラムダ式は、1式のみのbodyを持つ場合の`{}`と`return`を省略できます。
例えば下記のlambda1とlambda2の2つは同じ意味になります。

```typescript
const lambda1 = (x) => { return x + 1 }
const lambda2 = (x) => x + 1
```

なので今回のラムダ式も`navigator.share(shareData)`という1式なので`{}`は省略できます。

2023-03-10 13:46 UTC, yonta commented on app/javascript/share/share.ts
> +  void navigator.share(shareData)
ESLintの怒られは浮動Promiseの存在です。
Promiseは非同期処理で未来に値が帰ってくるものです。
未来に値や失敗例外が帰ってきた処理がないため怒られています。

`void`すると避けれたようですが、正しい方法とは思えません。

提示したリンクにあるように、Promiseの結果を処理する空のthen節をいれるのがいいと思います。
そのほうが、結果は特に気にしないの意が入るかと。

2023-03-10 14:03 UTC, yonta requested changes

2023-03-10 14:03 UTC, yonta commented on app/javascript/share/share.ts
> +})
```suggestion
shareButton.addEventListener("click", () =>
  navigator.share(shareData).finally(() => {
    // fail, do nothing
  })
)
```

2023-03-10 14:38 UTC, merged