Update: SimpleLightboxの型ファイルを最新版に追従した
momocus/sakazuki pull request #597
Opened 2023-03-21 18:10 UTC by yonta

ﾁｮﾄｶﾀﾜｶﾙ

少し型わかってきた。
これで前より補完が強力になる。

2023-03-23 09:49 UTC, momocus requested changes

2023-03-23 09:49 UTC, momocus commented on app/javascript/simple_lightbox/simplelightbox.d.ts
> +    currentImage: any /* TODO */ | null
any型に関してwarningが3箇所出てるよ
```
  76:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  85:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  85:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```

2023-03-23 10:03 UTC, yonta commented on app/javascript/simple_lightbox/simplelightbox.d.ts
> +    currentImage: any /* TODO */ | null
うおん。
warningはexit 0しててActionsにひっかからないのか。

2023-03-23 10:08 UTC, yonta commented on app/javascript/simple_lightbox/simplelightbox.d.ts
> +    currentImage: any /* TODO */ | null
別issueにしました #599

2023-03-25 07:10 UTC, momocus approved these changes

2023-03-25 07:10 UTC, merged