Update: docker compose上でブラウザテストできるようにした
momocus/sakazuki pull request #607
Opened 2023-03-25 12:16 UTC by momocus

Close #202

やったこと
docker compose上でrspecを実行する時、リモートのfirefoxブラウザを使ってブラウザテストをできるようにした。

やってないこと
docker composeを使わずにdockerコンテナで動かすときは、リモートのfirefoxブラウザを使わない（今まで通りローカルのfirefoxを使おうとする）

2023-03-25 13:40 UTC, yonta requested changes
修正お願いします

2023-03-25 13:40 UTC, yonta commented on spec/support/capybara.rb
> +  options.add_argument("--headless")
selenium-webdriverのDocコメントにあるように、簡単な書き方ある。

ちなみに、`--headless`だと間違いで、正しくは`-headless`。
こういう間違いを防ぐためにも、用意されているメソッドは使うべき。

```suggestion
  options.headless!
```

2023-03-25 13:40 UTC, yonta commented on spec/support/capybara.rb
> +Capybara.register_driver(:remote_firefox) do |app|
他の名前が`selenium`や`selenium_headless`なので、それに揃えた名前付けにしよう。
`remote_firefox_headless`とか、`firefox_headless_remote`とか、`selenium_headless_remote`とか。

2023-03-25 13:40 UTC, yonta commented on spec/support/capybara.rb
> +  )
改行なしで1行でいいね。
```suggestion
  Capybara::Selenium::Driver.new(app, browser: :remote, options:, url:)
```

2023-03-25 13:40 UTC, yonta commented on spec/support/capybara.rb
> +  Capybara.server_host = "web"
ここの`web`って名前と、あと上のURLで使っている`selenium`の名前。
これらはソースコードに染み出させるよりも、環境変数でdocker-compose.ymlから与えるほうが設計としていいと思う。
そのほうが、あとからの再利用性が高い。

そうすると、`IN_DOCKER`変数みたいな実態のない変数を消せて、導入する変数で分岐を書ける。

2023-03-25 13:40 UTC, yonta commented on spec/support/capybara.rb
> +if ENV.fetch("IN_DOCKER", nil)
fetchでデフォルト値なんていれる必要ないよね
```suggestion
if ENV["IN_DOCKER"]
```

2023-03-25 13:40 UTC, yonta commented on spec/support/capybara.rb
> +
```suggestion
```

2023-03-25 13:45 UTC, yonta commented
本文なんだけど、見づらいから見出しタグ使ってね。
例えば##でh2相当になる。

あと、やってないことに、できないことを書いてる。
内容と見出しが一致してない。
たぶん、「わからないこと」とか「既知の未解決の課題」とかかな。

2023-03-25 13:55 UTC, yonta commented on spec/support/capybara.rb
> +if ENV.fetch("IN_DOCKER", nil)
INなのか、よくわからない。
USING_DOCKERとかなのかもしれない。

2023-03-25 14:18 UTC, yonta commented on spec/support/capybara.rb
> +Capybara.register_driver(:remote_firefox) do |app|
このドライバ登録自体もif文の中にいれてしまっていいでしょう。
オブジェクト生成する必要すらないし。

2023-03-26 14:49 UTC, momocus commented on spec/support/capybara.rb
> +  options.add_argument("--headless")
Fixed at d48f24dc597cc79bb6c6e98362f296b12c0346eb

2023-03-26 14:49 UTC, momocus commented on spec/support/capybara.rb
> +Capybara.register_driver(:remote_firefox) do |app|
Fixed at d48f24dc597cc79bb6c6e98362f296b12c0346eb
remote_firefox_headlessにしました

2023-03-26 14:50 UTC, momocus commented on spec/support/capybara.rb
> +  )
Fixed at d48f24dc597cc79bb6c6e98362f296b12c0346eb

2023-03-26 14:50 UTC, momocus commented on spec/support/capybara.rb
> +  Capybara.server_host = "web"
Fixed at d48f24dc597cc79bb6c6e98362f296b12c0346eb

2023-03-26 14:50 UTC, momocus commented on spec/support/capybara.rb
> +if ENV.fetch("IN_DOCKER", nil)
Fixed at d48f24dc597cc79bb6c6e98362f296b12c0346eb
IN_DOCKERという名前の環境変数を使うのはやめました

2023-03-26 14:51 UTC, momocus commented on spec/support/capybara.rb
> +
Fixed at d48f24dc597cc79bb6c6e98362f296b12c0346eb

2023-03-26 14:51 UTC, momocus commented on spec/support/capybara.rb
> +Capybara.register_driver(:remote_firefox) do |app|
Fixed at d48f24dc597cc79bb6c6e98362f296b12c0346eb

2023-03-26 15:01 UTC, momocus commented
### HOW TO USE
```sh
$ docker compose up -d # -dはバックグラウンドで起動するオプション
$ docker compose exec web bundle exec rspec
```

2023-03-26 16:50 UTC, yonta requested changes

2023-03-26 16:50 UTC, yonta commented on spec/support/capybara.rb
> +if ENV["REMOTE_DRIVER_HOST"]
これらの変数をdotenv.exampleファイルにも記述しておこう。

2023-03-26 16:50 UTC, yonta commented on spec/support/capybara.rb
>  Capybara.default_driver = :rack_test
`default_driver`、`javascript_driver`、`test_id`の設定を`Capybara.configure do |config|`の中にまとめよう

2023-03-26 16:50 UTC, yonta commented on docker-compose.yml
docker-composeでテストの回し方コメントに書いてあるね。
この内容をREADME.mdにいれよう。

2023-03-27 04:27 UTC, momocus commented on spec/support/capybara.rb
> +if ENV["REMOTE_DRIVER_HOST"]
53ef755d42154bc360525383573d905570612ecb でやりました

2023-03-27 04:28 UTC, momocus commented on spec/support/capybara.rb
>  Capybara.default_driver = :rack_test
Fixed at 4644ae2552ee6cd7a307988e36d8a9990d6f78ea

2023-03-27 04:28 UTC, momocus commented on docker-compose.yml
Fixed at 67d19acc271d08cd6f8a15f3cb140c7e538f2d32

2023-03-27 04:30 UTC, momocus commented
/fix

2023-03-27 06:59 UTC, yonta reviewed
いいと思います！

2023-03-27 06:59 UTC, yonta commented on README.md
> +  - 別シェルで`docker compose up`しておくか、`docker compose up -d # バックグラウンドで起動`した状態で、以下のコマンドを実行する
- インラインcodeでワンラインコメントを使うと見ずらい
- 他が「～する」の1行なので合わせたほうがかっこいい

こんなんどうでしょ

```suggestion
- 起動している Docker コンテナでテストを実行すする
```

2023-03-27 06:59 UTC, yonta commented on dotenv.example
> +# CAPYBARA_SERVER_HOST=
コメントアウトしてあるし、例えば一般的にこんな設定だよを書いておこう。
というか僕が忘れるから書いておいてほしい。
検索キーワードにもなるし。

```suggestion
# CAPYBARA_APP_HOST=http://host.docker.internal
# CAPYBARA_SERVER_HOST=0.0.0.0
# REMOTE_DRIVER_HOST=localhost
# REMOTE_DRIVER_PORT=4444
```

2023-03-27 07:00 UTC, yonta approved these changes
いいと思います！

2023-03-27 09:58 UTC, merged