opened_atとemptied_atのデフォルト処理をModelに移した
momocus/sakazuki pull request #616
Opened 2023-03-28 01:39 UTC by momocus

Fix: #613

2023-03-28 05:23 UTC, yonta requested changes
たぶんバグを含んでいると思う

2023-03-28 05:23 UTC, yonta commented on app/models/sake.rb
> +    sake.emptied_at = sake.updated_at if bottle_level_in_database == :empty
ここおかしくない？
`_in_database`が変更前の`old`相当だと思うんだけど。
以前の状態がemptyだったら更新になってる。

つまり空のボトルの名前を変更すると、空にした日付が更新されてしまう。

2023-03-28 05:23 UTC, yonta commented on app/models/sake.rb
> +    sake.emptied_at = sake.updated_at if bottle_level_in_database == :empty
これを検知するには、`./spec/system/sake_form_bottle_level_spec.rb`に変更されないテストの追加がいるな。

2023-03-28 06:27 UTC, momocus commented on app/models/sake.rb
> +    sake.emptied_at = sake.updated_at if bottle_level_in_database == :empty
'./spec/system/bottle_level_datetimes_spec.rb'に書く方がよさそう

2023-03-28 10:16 UTC, momocus commented on app/models/sake.rb
> +    sake.emptied_at = sake.updated_at if bottle_level_in_database == :empty
詫びテスト書いて修正しました

2023-03-28 14:48 UTC, yonta requested changes
テスト通るのおかしくない？

2023-03-28 14:49 UTC, yonta commented on app/models/sake.rb
> +    sake.emptied_at = sake.updated_at if sake.emptied_at == "empty"
いつも書き換えられてないから、`Time.current`に1秒以内に近くて許されているのか

2023-03-28 14:53 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
`sealed`な酒を作るときは、`created_at`、`opened_at`、`emptied_at`の全部を指定しないとだめだね。
デフォルトで`Time.current`が入力されるので、変更したときに正しいか正しくないかわからなくなっちゃう。

2023-03-28 14:53 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
> +    created_at = 7.days.ago
同上

2023-03-28 14:53 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
> +    let(:sake) { create(:sake, bottle_level: "opened", created_at:, opened_at:) }
同上で、これも`emptied_at`に、`created_at`と同じ日時を指定しないといけない。

2023-03-28 14:53 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
> +    let!(:sake) { create(:sake, bottle_level: :sealed, opened_at: Date.new(2000, 1, 1)) }
これもそうで、
`created_at`、`sealed_at`、`emptied_at`を指定しないと怪しくなる。

2023-03-29 09:28 UTC, momocus commented on app/models/sake.rb
> +    sake.emptied_at = sake.created_at if sake.empty?
`before_create`のときは`created_at`使える。これからDBに登録する値が参照できる。
`after_initialize`や`before_validation`だと使えない。

2023-03-29 10:47 UTC, closed without merging

2023-03-29 10:47 UTC, momocus commented
クローズしました