Flashメッセージ表示関連をヘルパーに切り出した
momocus/sakazuki pull request #619
Opened 2023-03-28 07:19 UTC by yonta

Flashメッセージの大幅見直し！

close #610

## 今までの問題点

- flashメッセージに関する操作が各所に散らばっていた
  - 酒コントローラ、フラッシュビュー
  - flashのユーザ要求が変更されると、コントローラもビューも変更される。
    - 依存関係が、`酒コントローラ ← flash要求仕様 → フラッシュビュー`のようになっていた。
    - flashがユーザ要求なので、`酒コントローラ → flashモジュール ← フラッシュビュー`で、flashモジュールにflash要求仕様が依存すべき
- これはflashの設計が、キーとメッセージをいれるしかできないため。
  - aタグを含むなど、複雑なメッセージが扱いづらい　
## 設計

- Flashへの入力
  - FlashHelperは使わず、今までどおりに使える
    - `flash.alert`や`flash.notice`が使える
    - RailsやDeviseの生成するメッセージがこの方式で入るため、捨てない
  - 機能別に新しい入力方法を使う
    - 例えば酒の更新なら、`flash[:update_sake] = message`のように入力する
- Flashの出力
  - Flashの出力のビューは_flash.html.erb
  - ここで内容をつくるのにFlashHelperを使う

## やったこと

- Add: FlashHelperのテストを追加
- Add: FlashHelperを作成した
- Update: 新たなFlashHelperを使ってflashメッセージ機能を書き直した
- Fix: flashメッセージ翻訳の移動に対応して、既存テストを修正

2023-04-05 14:42 UTC, momocus requested changes
依存関係を逆にするとは……さては天才か？

2023-04-06 06:45 UTC, yonta commented on app/helpers/flash_helper.rb
> +  end
OK

2023-04-06 06:48 UTC, yonta commented on app/helpers/flash_helper.rb
> +  end
HASHだとORが使えないからメモリ効率は悪くなる

2023-04-06 07:35 UTC, yonta commented on app/helpers/flash_helper.rb
> +  end
commit e29222519255296cf2e4da888758dce3f2539367 で修正

2023-04-06 08:06 UTC, momocus approved these changes

2023-04-06 08:06 UTC, merged