emptied_at, opened_atまわりのテストを修正
momocus/sakazuki pull request #620
Opened 2023-03-30 04:42 UTC by momocus

#616 で見つかったバグフィックスやリファクタ

2023-03-30 09:12 UTC, yonta requested changes
まだ間違った動作も通るテストですん。

2023-03-30 09:12 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
>      let(:sake) { create(:sake, bottle_level: "sealed", created_at:) }
ここも一緒。
`emptied_at`を初期化する必要がある。
おすすめの初期化値は`created_at`と同じ`7.days.ago`かな。

2023-03-30 10:54 UTC, momocus commented on spec/system/bottle_level_datetimes_spec.rb
>      let(:sake) { create(:sake, bottle_level: "sealed", created_at:) }
opened_at に直接値をセットするより、システムテストとしてはtravel_toした方がよいかも
- 酒を登録する
- travel_toで7日後に行く
- 酒を開封する
- expect: opened_atが7日後の日時になっている

2023-03-31 04:47 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
>      let(:sake) { create(:sake, bottle_level: "sealed", created_at:) }
そうね！

変にテスト時に作る酒にアトリビュートセットを追加するのはやはり変だしよくない。
システムテスト的にも、ユーザの行う動作をテストにそのまま書くべきだ。

なので過去にトラベルして酒を作成してから、現在に開封するテストにすべき。

2023-04-06 03:43 UTC, momocus commented on spec/system/bottle_level_datetimes_spec.rb
>      let(:sake) { create(:sake, bottle_level: "sealed", created_at:) }
いろいろ修正しました。リレビューお願いします🙇

2023-04-06 08:41 UTC, yonta requested changes
7日後の4日後は何日後？
わからない！

2023-04-06 08:41 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
> +    travel_to(num.days.after)
この場合、`travel_to`にdoブロックを渡すと、操作が終わったら戻ってこれるみたい。
この書き方いいね。

https://qiita.com/mightysosuke/items/72f764fc237422b423b0

2023-04-06 08:41 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
> +  def edit_bottle_level(sake, bottle_level)
editするだけにsakeオブジェクトを渡すのは過剰な設計だと思う。
pathかidさえあれば、十分に酒の編集ができる。

2023-04-06 08:41 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
> +    travel_to(num.days.after)
例えば、各テストでの要素はこうなる。
この書き方なら、「7日後に移動して、4日後に移動して、だから11日前と比較して…」みたいな計算もいらない！

```ruby
before do
  id = travel_to(7.days.ago) do
    sign_in(user)
    create_sake("sealed") # create_sakeがidを返すようにするとよい、具体的にはpage.current_path.split("/")[2]
  end
  visit sakes_path          # devise timeout
  edit_bottle_level(id, "opened")
end
```

2023-04-07 13:55 UTC, momocus commented on spec/system/bottle_level_datetimes_spec.rb
> +  end
travel_and_re_sign_inは廃止して、そのままtravel_toを使うようにしました。

2023-04-07 13:56 UTC, momocus commented on spec/system/bottle_level_datetimes_spec.rb
>      sign_in(user)
このbeforeブロックを消しました

2023-04-07 13:59 UTC, momocus commented on spec/system/bottle_level_datetimes_spec.rb
> +    travel_to(num.days.after)
travel_toにブロックを渡して過去に戻るようにしました。
ただし過去と現在の時間移動が増え、実行に時間がかかるようになりました。

2023-04-07 13:59 UTC, momocus commented on spec/system/bottle_level_datetimes_spec.rb
> +  def edit_bottle_level(sake, bottle_level)
引数をidで渡すようにしました

2023-04-07 14:52 UTC, yonta approved these changes
えーやん！

2023-04-07 14:52 UTC, yonta commented on spec/system/bottle_level_datetimes_spec.rb
> +  # 引数で指定したbottle_levelの酒を登録する
ここにYARDつけておけばいいんじゃない？

2023-04-07 14:53 UTC, merged