fix: docker composeを立ち上げなおすと画像が消える #608
momocus/sakazuki pull request #648
Opened 2023-08-28 14:42 UTC by momocus

Close #608

publicをバインドマウントして、画像が残るようになった。

2023-09-07 07:56 UTC, yonta requested changes
publicには2種類の内容があって1行のマウントでは対応できない。
コメント見て修正よろ。

2023-09-07 07:56 UTC, yonta commented on docker-compose.yml
> +      - ./public:/sakazuki/public:cached
publicには2種類のファイルが入っていて、これだと不完全だと思う。
その2種類とは下記。

1. 404.htmlのようにHTMLエラーコード時に表示されるページ
2. public/uploadsのように、dev環境においてユーザがアップロードした画像保存フォルダ

1は動作させるのに必要なのに、現在のDockerfileでマウントされてなくて問題。
こちらはマウントで良いと思う。

2はマウントすると良くないと思う。
理由は、Dockerで動作させたときと、手元のrailsコマンドで動作させたときに、同じuploadsフォルダを使いまわして整合性が取れなくなる。
違う動作のときは違うリソースを使うべき。

なので1のためにpublicのマウントは入れる。
一方で、2のために、public/uploadsはDockerボリュームを作ってそれをマウントするのが良いと思う。

2023-09-15 13:20 UTC, momocus commented on docker-compose.yml
> +      - ./public:/sakazuki/public:cached
fixed at 3c80d92

dev環境で存在しないページにアクセスすると404.htmlじゃなくてRailsのRouting Error画面が表示される。404.htmlがどう表示されるか確認したいときにはdevelopment.rbで`config.consider_all_requests_local = false`にするといいゾ！

https://qiita.com/hirotakasasaki/items/db3bc993a2ba48b3e882

2023-09-15 17:02 UTC, yonta commented on docker-compose.yml
> +      - ./public:/sakazuki/public:cached
豆知識だ

2023-09-16 09:11 UTC, yonta commented on docker-compose.yml
> +      - ./public:/sakazuki/public:cached
さておき、404.htmlとかもかっこよくしたいね

2023-09-16 09:13 UTC, yonta approved these changes
Great!

2023-09-16 09:13 UTC, merged