letter_openerへのリンクをdev環境で追加
momocus/sakazuki pull request #670
Opened 2023-10-03 05:00 UTC by yonta

close #669

## やったこと

- Test/Prod環境でレターオープナーへのリンクがないテストを追加
- letter_openerへのリンクを、下部のデバッグ情報に追加

2023-10-11 22:40 UTC, momocus requested changes

2023-10-11 22:40 UTC, momocus commented on spec/views/layouts/application.html.erb_spec.rb
> +    visit root_path
test環境でリンクがどうなっていようがどうでもいいし、productionにリンクがないことをテストするのがいいと思う。
before 節でこう書けば、Rails.envをスタブ化してテストできるぞい。

```ruby
allow(Rails).to receive(:env).and_return(ActiveSupport::StringInquirer.new("production"))
```

2023-10-13 06:57 UTC, yonta commented on spec/views/layouts/application.html.erb_spec.rb
> +    visit root_path
おかのした！

2023-10-13 07:19 UTC, yonta commented on spec/views/layouts/application.html.erb_spec.rb
> +    visit root_path
commit e1ecb0d9b40002c899cbaeb7edba28df0aac36ef で対応

2023-10-14 11:16 UTC, momocus requested changes

2023-10-14 11:16 UTC, momocus commented on spec/views/layouts/application.html.erb_spec.rb
> +      it "is not in production and test environment" do
```suggestion
      it "doesn't have the link to letter_opener" do
```

context:  本番環境の場合
it:  レターオープナーへのリンクを持ってない
みたいな英文が自然だと思う。

2023-10-14 11:24 UTC, yonta commented on spec/views/layouts/application.html.erb_spec.rb
> +      it "is not in production and test environment" do
これは主語はdescribeで述べられている「letter_opener link」。
なので、提案された文章では「リンクがリンクを持たない」という意味になってしまう。
なので「リンクが存在しない」という意味の元の文がいい。

2023-10-14 11:28 UTC, momocus commented on spec/views/layouts/application.html.erb_spec.rb
> +      it "is not in production and test environment" do
では、
it doesn't exist in production environment
がいいと思います。

2023-10-14 11:31 UTC, momocus commented on spec/views/layouts/application.html.erb_spec.rb
> +      it "is not in production and test environment" do
理由
- 「本番環境では〜」はすでにcontextで書いているのでitに要らない
- letter_opener link is not だと「レターオープナーのリンクではない」という意味になると思う

2023-10-14 11:37 UTC, yonta commented on spec/views/layouts/application.html.erb_spec.rb
> +      it "is not in production and test environment" do
OK
じゃあ it does not exist でいいね

2023-10-14 11:39 UTC, yonta commented on spec/views/layouts/application.html.erb_spec.rb
> +      it "is not in production and test environment" do
> letter_opener link is not だと「レターオープナーのリンクではない」という意味になると思う

これはbe notだから存在しないという意味が近くて、リンクではない、ではないと思う。
強いて言えば、「レターオープナーのリンクは違う」のほうが正しいんじゃないかな

2023-10-14 11:55 UTC, yonta commented on spec/views/layouts/application.html.erb_spec.rb
> +      it "is not in production and test environment" do
commit 90a8561e186006ad308ba58d0b3b13a139bc4896  で対応

2023-10-14 16:05 UTC, momocus approved these changes

2023-10-14 16:05 UTC, merged