Add annotate
momocus/sakazuki pull request #78
Opened 2020-08-19 12:54 UTC by iteduki

# 概要
annotate gemを追加
各モデルのスキーマ情報をファイルにコメントとして書き出してくれる便利なGem

## annotate
https://github.com/ctran/annotate_models

2020-08-19 14:27 UTC, yonta requested changes

2020-08-19 14:27 UTC, yonta commented on Gemfile
> +  gem "annotate"
springの説明コメントと`gem "spring"`の間に入って分断してるので、入れる場所を変えてください。
百合の間に男を入れないで。

2020-08-19 14:29 UTC, yonta commented
なにこのgem、便利！

2020-08-19 14:30 UTC, yonta commented
個人的な好みとして、gemの追加とgemのインストールはまとめたコミットでいいなと思っている。

2020-08-19 14:32 UTC, yonta approved these changes

2020-08-19 14:35 UTC, yonta requested changes

2020-08-19 14:35 UTC, yonta commented on Gemfile
> +  gem "annotate"
色々操作ミスったけど、この対処だけお願いします。

2020-08-19 14:52 UTC, iteduki commented
developmentの下に追記して`rubocop -a` すればええやろと思ってました。過信してましたね > 記述位置

2020-08-19 16:03 UTC, yonta commented on config/routes.rb
> +
`rubocop -a`で行われない変更が入ってる

2020-08-19 23:39 UTC, iteduki commented on config/routes.rb
> +
自分の手元で`annotate --routes`を試してたものをデフォルト設定と勘違いして入れてしまってました。ので削除
(rubocopの際にannotateも同時に走らせるような設定があった気がしたけど気のせいかもしれない)

2020-08-20 08:47 UTC, yonta approved these changes

2020-08-20 08:47 UTC, yonta commented
👏

2020-08-20 09:08 UTC, momocus approved these changes
👍

2020-08-20 09:09 UTC, merged