Add docker
momocus/sakazuki pull request #85
Opened 2020-10-03 02:32 UTC by iteduki

# 何をしているか
Dockerで環境を作ることにより開発者間での環境差分をなくして開発できるようにする

Docker化は公式のものを参考に作成
https://docs.docker.com/compose/rails/

# 残タスク
- [ ] node-sassのエラー
- [ ] gem周りのキャッシュ化
- [ ] node周りのキャッシュ化

2021-01-12 06:59 UTC, yonta requested changes
VS Code、改行を入れないのつらい

2021-01-12 06:59 UTC, yonta commented on .dockerignore
> +public/packs
ファイル末尾改行をつけてくれ～～～

2021-01-12 06:59 UTC, yonta commented on .dockerignore
> +public/packs
他ファイルも同上

2021-01-12 06:59 UTC, yonta commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
手順通りやったら`db:create`で`yarn install --check-files`しろってエラーでてしまった。
`docker-composer run --rm web yarn install --check-files`が必要？
自分の環境がWSL2 + Docker for Windowsなので、ちょっと特殊なせいは否めないので教えて。

```console
$ docker-compose run --rm web bunle exec rails db:create
Creating network "sakazuki_default" with the default driver
Pulling db (postgres:)...
latest: Pulling from library/postgres
6ec7b7d162b2: Pull complete
a7d6065bfd90: Pull complete
1b99004acb42: Pull complete
e11ab41f0489: Pull complete
eaa59f6a7cf0: Pull complete
e27743da9368: Pull complete
10ffdd8ade29: Pull complete
bdaa066489bc: Pull complete
18fcf6a7b457: Pull complete
7e48453e674b: Pull complete
d6a3ea95116d: Pull complete
0cd33e8b20bb: Pull complete
85eddbec7cca: Pull complete
a4a32e0796c6: Pull complete
Digest: sha256:0813fa9554ed0132488c271fbe1e559a861b44a368f40ec01b3bbb8c28789db5
Status: Downloaded newer image for postgres:latest
Creating sakazuki_db_1 ... done
Creating sakazuki_web_run ... done
/usr/bin/entrypoint.sh: line 8: exec: bunle: not found
$ docker-compose run --rm web bundle exec rails db:create
Creating sakazuki_web_run ... done
warning Integrity check: System parameters don't match
error Integrity check failed
error Found 1 errors.


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.22.5
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

2021-01-12 06:59 UTC, yonta commented on README.md
> +## Dockerの場合
```suggestion
## How to use with Docker
```

2021-01-12 07:16 UTC, yonta commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
ひょっとして、既存ファイルがあるとよくない？🤔

2021-01-12 10:03 UTC, yonta commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
`tmp/db/`のファイルの権限が`999:docker`になってしまった。つらい。

2021-01-13 18:02 UTC, yonta commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
ちゃんとWSL2 + Docker fow Windows + wsl.confでautomountのmetadataなしでやった。
やっぱりダメだった。
次はLinux仮想マシンで再トライするわ…。

```console
$ docker-compose run --rm web bundle exec rails db:create
sakazuki-docker_db_1 ... done
Creating sakazuki-docker_web_run ... done
error Couldn't find an integrity file
error Found 1 errors.


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.22.5
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

2021-01-14 00:18 UTC, iteduki commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
> 手順通りやったら`db:create`で`yarn install --check-files`しろってエラーでてしまった。
ここの部分は`webpacker.yml` で `check_yarn_integrity: false`するか `node_modules`を退避させたら突破できるかも？

2021-01-14 03:34 UTC, momocus requested changes
一部手を入れたけどMacBookで動かせた🤗

2021-01-14 03:34 UTC, momocus commented on README.md
> +  password: password # 追加
developmentだけでなくtestの方もusernameとpassword設定しないとエラー出る

2021-01-14 03:34 UTC, momocus commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
```suggestion
docker-compose run --rm web yarn install --check-files
docker-compose run --rm web bundle exec rails db:create
```

2021-01-14 03:34 UTC, momocus commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
PostgresQLのユーザー名、パスワード、ホスト名は環境変数で設定するようにできない？

2021-01-14 03:34 UTC, momocus commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
MacBookではこれやったら動いた

2021-01-14 13:05 UTC, yonta commented on Dockerfile
> +COPY package.json /sakazuki/package.json
yarn.lockのコピーもいる気がする

2021-01-14 16:23 UTC, yonta commented
レビューじゃなくコメントで書くわ。

Windowsでなく仮想マシンUbuntuで試したけど、Windowsのときと同じエラー出た。
やはり`yarn install --check-files`しろと言われる。

いてづきさんの言う通り、`webpacker.yml`で`check_yarn_integrity: false`オプションつければ確かに通りそう。
けどせっかくレポジトリに`yarn.lock`いれてバージョン固定してるのに、Dockerに限らず`yarn check --integrity`をしなくするのは避けたい。
あと`Dockerfile`で最新版のnodeモジュールを`RUN yarn`で取得しているはずなのに、どうして`yarn check`落ちるのかもわからない…。

```console
$ docker-compose run --rm web bundle exec rails db:create
Creating network "sakazuki_default" with the default driver
Pulling db (postgres:)...
latest: Pulling from library/postgres
a076a628af6f: Pull complete
d54fa0e0eb76: Pull complete
8950a7ea6876: Pull complete
1cc02b1df09e: Pull complete
06f548e51228: Pull complete
74665692d4ea: Pull complete
235e34eb13ab: Pull complete
4ad7ef5e2e79: Pull complete
76670339b0f8: Pull complete
496fa0539f99: Pull complete
f32ecbdf3b52: Pull complete
7536b8fe81ac: Pull complete
71dfc17927aa: Pull complete
fd48bac409bb: Pull complete
Digest: sha256:ec74afc9fa969a235462c27017a3fe73a05c9d4725d7e4afbe2ba6eb82fdfc87
Status: Downloaded newer image for postgres:latest
Creating sakazuki_db_1 ... done
Creating sakazuki_web_run ... done
error Couldn't find an integrity file                                          
error Found 1 errors.                                                          


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.22.5
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

2021-01-14 16:34 UTC, yonta commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
現状はローカルのDBで動かす際は、`config/database.yml`にdotenvでDBのアカウント・パスを記述しています。

- `config/database.yml`、コメント省略
```yml
development:
  <<: *default
  database: sakazuki_development
  username: <%= ENV["POSTGRESQL_NAME"] %>
  password: <%= ENV["POSTGRESQL_PASS"] %>
```

なので、sakazuki-webイメージのsakazukiにDBのユーザ・パスを伝えるために、sakazuki-webイメージの`.env`ファイルに書き出すか環境変数に入れないといけない。

2021-01-14 16:34 UTC, yonta commented on README.md
> +docker-compose run --rm web bundle exec rails db:create
Macもやっぱりyarnいるか～

2021-01-14 16:37 UTC, yonta commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
あ、でも`host`の追記はいるのか。ふむ。

2021-01-14 16:38 UTC, yonta commented on README.md
> +  password: password # 追加
エラーはどのタイミング？
`docker-compose run --rm web bundle exec rails db:create`したときでいいかな？
だとしたら、READMEの順番を直さないといけない。

2021-01-17 04:48 UTC, kjfsm commented on .dockerignore
> +public/packs
VSCodeの設定によるやつですね

2021-01-17 04:49 UTC, kjfsm commented
うまく動かなかったので死です。
Dockerfileでパイプライン使うときはこれつけとくのがおすすめです（ダイイングメッセージ）
https://qiita.com/nossy/items/0f5572d84f4617207378

2021-01-17 05:03 UTC, kjfsm commented
aptg-get install するときにバージョンつけるとnodeのバージョン違いで死んだりしない気がする

2021-01-18 05:18 UTC, iteduki commented on .dockerignore
> +public/packs
つけました https://github.com/momocus/sakazuki/pull/85/commits/aa736cfa1d55ab09aec75da7fe4b546b0ed1e511

2021-01-18 05:21 UTC, iteduki commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
おそらく`host`の指定がないときは`localhost`になっているのではないかと思われる
なので `host: <%= ENV['MYSQL_HOST'] || 'localhost' %>` みたいな感じでいけるのか試してみます
(可能なら`host: localhost`を記述してみて動作が変わらないか試してみてほしいです)

2021-01-18 06:12 UTC, iteduki commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
docker-composeも`.env`から環境変数を取れる  
https://docs.docker.com/compose/environment-variables/

なので`host`の指定をちゃんと検証できたら環境変数で出来るはず（試します

2021-01-18 10:08 UTC, yonta commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
わいわい、これができれば超イケてる

2021-01-18 10:10 UTC, yonta commented
> うまく動かなかったので死です。

どの手順でどんなエラーで動かなかったのか教えてもらえると、いてづきさんがきっとやってくれる（投げ

2021-01-18 15:02 UTC, iteduki commented on Dockerfile
> +COPY package.json /sakazuki/package.json
確かに。追加しました 
 https://github.com/momocus/sakazuki/pull/85/commits/3fc728ef0f0d22eb10fa31c5d138f549c934f0f2

2021-01-18 16:52 UTC, yonta commented
> apt-get install するときにバージョンつけるとnodeのバージョン違いで死んだりしない気がする

nodeのバージョンについてmasterのREADMEに記載してありませんでした。
追加をし、v12以降を対象としました。

いてづきさんのnodejs setupはv12を指定してとってきています。
ので、aptコマンドでnodejsのバージョンを固定しなくても大丈夫と思います。

あとは問題が起きてからで良さそう。

2021-01-20 08:29 UTC, yonta commented
気づいたんだけど、`docker-compose.yml`でマウント指定している。
これでは、`docker build`で作った`node_modules`を含むimageの`/sakazuki`が、
ローカルの`./`で上書きされてないかな。

```yml
    volumes:
      - .:/sakazuki
```

以下のコマンドでコンテナに入って、`ls /sakazuki`で中身を覗くと違う`/sakazuki/node_modules`になってる（もしくはnode_modulesが存在しない）。

- `dokcer run -it sakazuki_docker_web bash`
- `dokcer run --mount type=bind,src=$(pwd),dst=/sakazuki -it sakazuki_docker_web bash`

今のSakazukiには永続化するものはDBデータしかないから、`db`の`tmp/db`マウントだけでいい気がする。

2021-01-20 08:45 UTC, momocus commented
StackOverflowに同じ問題が載っていたわ。
https://stackoverflow.com/questions/58933929/yarn-packages-out-of-date-when-running-rails-app-in-docker

よんたも言っている通り、`web`のマウント削除したら、`docker-compose run --rm web bundle exec rails db:create`成功しました！

2021-01-20 13:53 UTC, kjfsm commented
これ使うといろいろ教えてくれるのでおすすめ。
https://github.com/hadolint/hadolint

2021-01-20 14:07 UTC, yuina1056 commented on docker-compose.yml
> +    image: postgres
postgresのバージョンは固定しなくて大丈夫ですかね？
postgresのバージョン差異で動かなくなるクエリがある可能性あるので

2021-01-22 05:25 UTC, yonta commented on docker-compose.yml
> +    image: postgres
考え直した。
確かにlatest指定は急にアップデートかかって再ビルドとか予想外のコストが発生しそう。
13指定しておくのが良さそう。

2021-01-26 14:36 UTC, iteduki commented
momocusさんからのPRはマージしました
だいぶとっちらかってしまったので良き形のコミットに整形してもらって大丈夫です

2021-01-26 17:09 UTC, yonta commented
スカッシュして作り直した => #141

2021-01-27 07:05 UTC, momocus commented
#141 をmasterにマージしました！　ありがとういてづきさん！　ありがとう冷蔵庫の民！

2021-01-27 07:05 UTC, closed without merging