写真を登録できるようにした
momocus/sakazuki pull request #89
Opened 2020-11-17 10:22 UTC by momocus

#9 に対応

☑Cloudinaryを利用して画像をアップロードする
□開発環境ではCloudinaryにアップロードせず、ローカルストレージに画像を保存する

- Cloudinary & CarrierWave での複数画像アップロードは、下記のサンプルプロジェクトを参考にした。
  - https://github.com/cloudinary/cloudinary_gem/issues/266#issuecomment-325043316

---
めも
　「carrierwave cloudinary multiple」でぐぐったら[こちら](https://github.com/Vitalijus/multiple-file-upload-with-carrierwave-to-cloudinary)のサイトも引っかかった。
　↑のサイトではacepts_nested_attributes_for というActiveRecordメソッドを使って、1対多の関係にあるオブジェクトを関連付けている。しかしRailsの中の人が、このメソッドの使用は非推奨とのことだった。
　おそらく1対多の関係があるならモデルを切り離して（正規化して）おけということだと思う。
　

2020-11-26 06:46 UTC, yonta requested changes

2020-11-26 06:46 UTC, yonta commented on .gitignore
> +config/cloudinary.yml
developmentでもこのファイルが無いと、index/showが`cl_***`タグエラーで動かない

2020-11-26 06:46 UTC, yonta commented on app/views/sakes/_form.html.erb
> -      <%= form.file_field :photo, { class: "form-control-file" } %>
酒を登録または編集を失敗すると登録画像が残らない。
なんとか画像を引き継げないかな。

### 再現方法

1. 酒の名前欄を空にする
2. 新規画像を参照する
3. 登録ボタンを押す
4. 名前が無いのでエラーし、登録した画像が消える

2020-11-26 06:46 UTC, yonta commented on app/controllers/sakes_controller.rb
> +  before_action :set_sake, only: %i[show edit update destroy show_photo]
読んでみると、`set_sake`は`@sake = [idでsakeの取得]`だけど、photoに`@sake`使ってるところある？

2020-11-26 06:46 UTC, yonta commented on app/controllers/sakes_controller.rb
> -  def show
これは今回のPR内容じゃないね。
次からは入れないでね。

小さな変更なので、 PR無しでmasterにコミットしちゃっていいと思う。

2020-11-26 06:46 UTC, yonta commented on app/views/sakes/_form.html.erb
> +        <%= t(".please_check_if_you_want_to_delete") %>
周りに合わせて`delete_photo`とかでいいと思う

2020-11-26 06:46 UTC, yonta commented on app/controllers/sakes_controller.rb
> -  def show
show.html.erbの大量の変更点もこれだね

2020-11-26 08:32 UTC, momocus commented on app/controllers/sakes_controller.rb
> -  def show
はいー

2020-11-26 08:41 UTC, momocus commented on .gitignore
> +config/cloudinary.yml
1d422f8 にて修正しました

2020-11-26 08:41 UTC, momocus commented on app/controllers/sakes_controller.rb
> +  before_action :set_sake, only: %i[show edit update destroy show_photo]
使用していなかったので削除しました b28216e

2020-11-26 08:43 UTC, momocus commented on app/controllers/sakes_controller.rb
> -  def show
はいー🐰
PRと分けるべきでした。ごめんなさい。

2020-11-26 08:43 UTC, momocus commented on app/views/sakes/_form.html.erb
> +        <%= t(".please_check_if_you_want_to_delete") %>
修正しました 34a3c33

2020-11-26 09:03 UTC, momocus commented on app/views/sakes/_form.html.erb
> -      <%= form.file_field :photo, { class: "form-control-file" } %>
難しいので別Issue立てました #95

2020-11-26 09:07 UTC, momocus commented
@yonta 再レビューお願いします。
あとこのプルリクの[最初のところ](https://github.com/momocus/sakazuki/pull/89#issue-522298870)に、Seeds.rbの書き方について追記したのでご確認お願いします。

2020-11-26 17:12 UTC, yonta commented on .gitignore
> +config/cloudinary.yml
この修正でもエラーは置きないが、adhocすぎない？
以前のDBのパスワード、パスワード再設定のアドレス、の値の扱いとともに直したほうがいい。

よくある方法はdirenvを使う方法。
ただし、各自の.bashrcなどで.envを読み込む設定が必要

- https://qiita.com/ntkgcj/items/6ca19c9decf929714970#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E8%A8%AD%E5%AE%9A

Railsならdotenvというgemを使うのが楽らしい。
ymlファイルでも`<%= ENV["SECRET_PASSWORD"] %>` のように使えるようだ。

 - https://github.com/bkeepers/dotenv

2020-11-29 12:57 UTC, momocus commented on .gitignore
> +config/cloudinary.yml
railsのcredentialsっていう機能が良さそうなのでこれを使う方向で考えます。

参考
https://guides.rubyonrails.org/security.html#environmental-security
https://zenn.dev/banrih/articles/f22f0a70bbead2a02110

2020-11-30 08:38 UTC, momocus commented on .gitignore
> +config/cloudinary.yml
2882593 にて、 1d422f8 の変更をRevertしました。
credentialsの導入は #97 に分けました。

2020-11-30 08:46 UTC, yonta approved these changes
:+1:

2020-11-30 08:46 UTC, merged

2020-11-30 08:46 UTC, yonta commented
ボーテ！:100: